datastore/README.md, integration-test/pom.xml, pom.xml
Config for running the integration tests against postgresql
=> Add docs and configuration for postgres

integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java, integration-test/src/test/java/org/jboss/pnc/integration/RestTest.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductVersionEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/ProjectEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/TriggerBuildEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/provider/ProductProvider.java, pnc-rest/src/main/java/org/jboss/pnc/rest/provider/ProjectProvider.java, pnc-rest/src/main/java/org/jboss/pnc/rest/restmodel/ProductRest.java, pnc-ui/app/scripts/pnc-configurations.js, pnc-ui/app/scripts/pnc-projects.js, pnc-ui/app/scripts/pnc-results.js
Project and Build Configurations are not anymore based on Product and ProductVersion paths (i.e. 
http://<PNC>/pnc-web/rest/project, http://<PNC>/pnc-web/rest/project/XX/configuration )
=> Refactoring of REST APIs

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
=> make the aprox url more resilient by appending /api if it's not already in there

pnc-model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, pnc-rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationRest.java, pnc-ui/app/scripts/pnc-configurations.js, pnc-ui/app/scripts/pnc-results.js, pnc-ui/app/views/configuration_add.html, pnc-ui/app/views/configurations.html, pnc-ui/app/views/results.html, pom.xml
Update UI to match model changes to build configuration
=> [NC-404] UI Update

datastore/src/main/java/org/jboss/pnc/datastore/repositories/ArtifactRepository.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildCollectionRepository.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationRepository.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepository.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductRepository.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductVersionProjectRepository.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductVersionRepository.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProjectRepository.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/UserRepository.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildRecordsTest.java, integration-test/src/test/java/org/jboss/pnc/integration/RSQLTest.java, pnc-rest/pom.xml, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductVersionEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/ProjectEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/UserEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, pnc-rest/src/main/java/org/jboss/pnc/rest/provider/ProductProvider.java, pnc-rest/src/main/java/org/jboss/pnc/rest/provider/ProjectProvider.java, pnc-rest/src/main/java/org/jboss/pnc/rest/provider/UserProvider.java, pnc-rest/src/main/java/org/jboss/pnc/rest/repository/EmptyRSQLAdapter.java, pnc-rest/src/main/java/org/jboss/pnc/rest/repository/RSQLAdapter.java, pnc-rest/src/main/java/org/jboss/pnc/rest/repository/RSQLAdapterFactory.java, pnc-rest/src/main/java/org/jboss/pnc/rest/repository/RSQLDataStoreSelectorAdapter.java, pnc-rest/src/main/java/org/jboss/pnc/rest/repository/RSQLNodeTraveller.java, pnc-rest/src/main/java/org/jboss/pnc/rest/repository/Transformer.java, pom.xml
Allows parsing query parameters and convert them into Spring Data Specifications.
Here is an example for querying user:
* `username==demo-user;email==demo-user@pnc.com`
More examples of RSQL (taken from https://github.com/jirutka/rsql-parser):
- `name=="Kill Bill";year=gt=2003`
- `name=="Kill Bill" and year>2003`
- `genres=in=(sci-fi,action);(director=='Christopher Nolan',actor==*Bale);year=ge=2000`
- `genres=in=(sci-fi,action) and (director=='Christopher Nolan' or actor==*Bale) and year>=2000`
- `director.lastName==Nolan;year=ge=2000;year=lt=2010`
- `director.lastName==Nolan and year>=2000 and year<2010`
- `genres=in=(sci-fi,action);genres=out=(romance,animated,horror),director==Que*Tarantino`
- `genres=in=(sci-fi,action) and genres=out=(romance,animated,horror) or …
=> RSQL implementation

maven-repository-manager/pom.xml
To be fixed in https://github.com/project-ncl/pnc/issues/142
=> #142 @Ignored looping tests

datastore/src/main/java/org/jboss/pnc/datastore/predicates/BuildConfigurationPredicates.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/RestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/assertions/JsonMatcher.java, integration-test/src/test/java/org/jboss/pnc/integration/matchers/ResponseAssertion.java, integration-test/src/test/java/org/jboss/pnc/integration/template/JsonTemplateBuilder.java, integration-test/src/test/resources/buildConfiguration_template.json, pnc-rest/pom.xml, pnc-rest/src/main/java/org/jboss/pnc/rest/configuration/JaxRsActivator.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/LegacyBuildConfigurationEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java, pnc-rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationRest.java
Hey @alexcreasy @vibe13 !
New configuration REST is ready. The old one still works but not for long. As soon as I get all new endpoints up and running I will start removing old stuff. 
Please let me know if you'd like me to preserve them (and tell for how long).
=> NCL-388 NCL-391 NCL-394 NCL-397 New Configuration REST endpoint implementation

pom.xml
disable integration-test execution by default => execution need activate profile with -Pintegration-test
=> remove activation property, we want to skip integration-test by default

common/pom.xml, datastore/pom.xml, ear-package/pom.xml, integration-test/pom.xml, pnc-model/src/main/java/org/jboss/pnc/model/BuildRecordSet.java, pnc-model/src/main/java/org/jboss/pnc/model/ProductVersion.java, pnc-model/src/main/java/org/jboss/pnc/model/builder/BuildRecordSetBuilder.java, pnc-model/src/main/java/org/jboss/pnc/model/builder/ProductVersionBuilder.java, pnc-rest/src/main/java/org/jboss/pnc/rest/restmodel/ProductVersionRest.java
=> Model updates

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
Improve readability of db initializer
Add two example projects
=> Minor improvements to demo data initializer

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/DatastoreTest.java, pnc-model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
* Now everything needs to be saved separately
* This will hopefully prevent us from accidentally removing data, just like it happened in NCL-608
=> NCL-608 Removed persisting cascades

integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationSetRestTest.java, integration-test/src/test/resources/buildConfigurationSet_template.json, pnc-model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java, pnc-model/src/main/java/org/jboss/pnc/model/ProductVersion.java, pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationSetEndpoint.java, pnc-rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationSetProvider.java, pnc-rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationSetRest.java
- Fix bug in POST operation
- Add PUT and DELETE operations
=> [NCL-452] Add rest for build config set

pnc-ui/app/app.js, pnc-ui/app/index.html, pnc-ui/app/websockets/_websockets.js, pnc-ui/app/websockets/views/websockets.html, pnc-ui/app/websockets/websockets-controllers.js, pnc-ui/bower.json
This is a "dummy" implementation of Angular JS. 
How to use it:
* Navigate to `/#!/websockets` and wait a little bit.
* You should observe notifications sent each 30 sec
=> NCL-565 Example implementation of Websockets and Angular JS

docker-environment-driver/src/main/java/org/jboss/pnc/environment/docker/DockerEnvironmentDriver.java, docker-environment-driver/src/main/java/org/jboss/pnc/environment/docker/DockerRunningEnvironment.java, docker-environment-driver/src/test/java/org/jboss/pnc/environment/docker/DockerEnvironmentDriverRemoteTest.java, jenkins-build-driver/src/main/java/org/jboss/pnc/jenkinsbuilddriver/JenkinsRunningBuild.java, jenkins-build-driver/src/test/java/org/jboss/pnc/jenkinsbuilddriver/test/JenkinsDriverRemoteTest.java, maven-repository-manager/pom.xml, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenCompletedPromotion.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRunningPromotion.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver01Test.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver02Test.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver03Test.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver04Test.java, pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildCoordinator.java, pnc-core/src/test/java/org/jboss/pnc/core/test/mock/BuildDriverMock.java, pnc-core/src/test/java/org/jboss/pnc/core/test/mock/EnvironmentDriverMock.java, pnc-core/src/test/java/org/jboss/pnc/core/test/mock/RepositoryManagerMock.java, pnc-core/src/test/java/org/jboss/pnc/core/test/mock/RepositorySessionMock.java, pnc-spi/src/main/java/org/jboss/pnc/spi/builddriver/BuildDriver.java, pnc-spi/src/main/java/org/jboss/pnc/spi/environment/EnvironmentDriver.java, pnc-spi/src/main/java/org/jboss/pnc/spi/environment/RunningEnvironment.java, pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java, pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/CompletedRepositoryPromotion.java, pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java, pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RunningRepositoryPromotion.java, pnc-ui/.gitignore, pom.xml
Renaming RepositoryConfiguration to RepositorySession, and decoupling promotion from artifact extraction.
=> Rename RepositoryConfiguration & decouple promotion from extraction

README.md, pnc-processes/pom.xml, pnc-processes/src/main/resources/META-INF/kmodule.xml, pnc-processes/src/main/resources/jboss/productReleaseQEHandoffProcess.bpmn, pnc-processes/src/main/resources/log4j.properties, pnc-processes/src/test/java/org/jboss/pnc/processes/ProcessTest.java, pnc-processes/src/test/java/org/jboss/pnc/processes/util/TestUserTaskWorkItemHandler.java, pom.xml
Pull request contains initial implementation of pnc-processes module. During unit tests I encountered <code>IllegalClassFormatException: Error while instrumenting class org/drools/compiler/lang/DRL6Lexer</code>, thus also changing jacoco configuration to include just org.jboss.pnc.* classes.
=> PNC processes

pom.xml
@rnc Sorry, this was a silly mistake :D
=> Fixed executing remote tests without turning on its profile

pom.xml, test-arquillian-container/pom.xml
This avoids having to repeatedly specify the file://... or https://... on the command line.
=> Add ability to specify EAP URL in local pnc.cfg

.gitignore, README.md, pom.xml, test-arquillian-container/pom.xml
=> Build fixes

maven-repository-manager/README.md
Adding install/update instructions for AProx instances to maven-repository-driver README.
=> Updating maven repo driver README with install/update

README.md
=> NCL-794 Fix module name

pnc-ui/app/footer.htm, pnc-ui/app/index.html, pnc-ui/pom.xml, pom.xml, test-arquillian-container/pom.xml
@alexcreasy  @vibe13  : can you review please
=> NCL 766 : Update versions during build

pnc-ui/app/common/util/views/header.buttons.html, pnc-ui/app/common/util/views/header.html, pnc-ui/app/common/util/views/header.title.html, pom.xml
@alexcreasy - updated for Angular include issues.
=> NCL-831 Remove copyright from include files. Update excludes

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenCompletedDeletion.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRunningDeletion.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesConfSetGroupTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesProductVersionGroupTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualDeletionOfBuildRepoTest.java, pnc-core/src/main/java/org/jboss/pnc/core/content/ContentIdentityManager.java, pnc-core/src/test/java/org/jboss/pnc/core/test/mock/RepositoryManagerMock.java, pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java, pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/CompletedRepositoryDeletion.java, pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RunningRepositoryDeletion.java, pom.xml
* tell m2eclipse to ignore directory-maven-plugin
* implement deleteBuild(BuildRecord) which is not automatically called anywhere
=> Implement build-artifact deletion (manual operation)

ui/Gruntfile.js
REST proxy configuration in `rest-config.json` does not work for me when using `grunt serve` with custom `--target`, as described in `ui/README.md`
For example:
Let `rest-config.json` be
```
{
"endpointsLocalhost": "localhost",
"dev": "1.2.3.4"
}
```
Command `grunt serve --target=dev` creates proxy for `localhost` instead of `1.2.3.4`.
This fix should resolve the issue.
=> Fixed REST endpoint proxy config in Web UI.

model/src/main/java/org/jboss/pnc/model/BuildRecord.java
Describe difference and relation between latestBuildConfiguration and
buildConfigurationAudited
=> [NCL-769] Add comments to describe build configuration links

model/pom.xml, model/src/test/java/org/jboss/pnc/model/BasicModelTest.java, model/src/test/java/org/jboss/pnc/model/ModelTestDataFactory.java, model/src/test/resources/META-INF/persistence.xml
Test the model directly without the full JavaEE container.
Just use hibernate and h2 database.
=> [NCL-749] Add db model tests

ui/app/app.js, ui/app/error.html, ui/app/services.js
* NCL-777 - Pnc UI web - properly handle the 401 & 403 responses from REST endpoints
* NCL-824 - UI flicker is somtimes noticeable when navigating (when authentication is enabled)
=> NCL-777 & NCL-824

integration-test/src/test/resources/test-ds.xml, model/pom.xml, model/src/main/java/org/jboss/pnc/model/BuildConfigSetRecord.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, pom.xml, rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationAuditedRest.java, rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationRest.java, rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordRest.java, test-arquillian-container/pom.xml
Reverts project-ncl/pnc#432
This PR causes errors on my local deployment and on the autodeploy server:
```
10:37:46,502 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014612: Operation ("deploy") failed - address: ([("deployment" => "ear-package.ear")]) - failure description: {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.persistenceunit.\"ear-package.ear/datastore.jar#primary\" is missing [jboss.naming.context.java.jboss.datasources.NewcastleTestDS]"]}
```
reverting for now.
=> Revert "Ncl 929"

build-coordinator/src/main/java/org/jboss/pnc/core/builder/BuildCoordinator.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/BuildSetTask.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/BuildTask.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/DatastoreAdapter.java, build-coordinator/src/test/java/org/jboss/pnc/core/test/buildCoordinator/ReadDependenciesTest.java, build-coordinator/src/test/java/org/jboss/pnc/core/test/buildCoordinator/event/StatusUpdatesTest.java, build-coordinator/src/test/java/org/jboss/pnc/core/test/mock/DatastoreMock.java, datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualPromotionOfBuildSetRepoTest.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, model/src/main/java/org/jboss/pnc/model/BuildRecordSet.java, spi/src/main/java/org/jboss/pnc/spi/datastore/Datastore.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordSetPredicates.java
Link the build record to the performed build record set for the current product
milestone for each related product version.
=> [NCL-1009] Link a completed build record to the product milestones

common/pom.xml, pom.xml
=> Revert "Ncl 1033 "

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, ui/bower.json
* more logging output in repo session to trace what's returned
* add resolutions section to bower.json (ui module) to resolve 'no suitable version' error on CentOS 7
=> ignored file suffixes in repo driver session

common/src/main/resources/pnc-config.json, docker-environment-driver/src/main/docker/common/Dockerfile, docker-environment-driver/src/main/docker/common/settings.xml, docker-environment-driver/src/main/docker/common/setup-proxy-server.sh, docker-environment-driver/src/main/java/org/jboss/pnc/environment/docker/DockerEnvironmentDriver.java, docker-environment-driver/src/test/resources/pnc-config.json, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/DockerEnvironmentDriverModuleConfig.java, moduleconfig/src/main/resources/pnc-config.json
...and propagate into settings.xml
=> Introduce nonProxyHosts configuration for docker environment

ui/app/common/restclient/services/Build.js, ui/app/record/_record.js, ui/app/record/record-directives.js
This attempts to fix an issue in the Records page due to refactorings in #517 .
There is also another commit to add displayName for both the log and output tab of records, so that the breadcrumbs show the record id.
=> Fix record view

integration-test/src/test/java/org/jboss/pnc/integration/ProductReleaseRestTest.java, integration-test/src/test/resources/productRelease_template.json, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java, model/src/main/java/org/jboss/pnc/model/Product.java, model/src/main/java/org/jboss/pnc/model/ProductMilestone.java, model/src/main/java/org/jboss/pnc/model/ProductRelease.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, model/src/main/java/org/jboss/pnc/model/Project.java, model/src/main/java/org/jboss/pnc/model/User.java
- Uniqueness on `name`:
* BuildConfiguration.java
* BuildConfigurationSet.java
* Product.java
* Project.java
- Uniqueness on `version` and `product_id`:
* ProductVersion.java
- Uniqueness on `version` and `productVersion_id`:
* ProductMilestone.java
* ProductRelease.java
- Uniqueness on `username` and/or `email`:
* User.java
Note: Right now the web-ui will fail to capture those uniqueness
violations that might occur while creating any of the models above.
Future work will go on making the web-ui aware of any model errors.
=> [NCL-1201] Add some uniqueness constraints on the model

rest/src/main/java/org/jboss/pnc/rest/restmodel/ArtifactRest.java, rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordRest.java, rest/src/main/java/org/jboss/pnc/rest/restmodel/ProductReleaseRest.java
This annotation should likely be added here, as it is for Configuration's BuildStatus field.
=> add ApiModelProperty for status

build-coordinator/src/main/java/org/jboss/pnc/core/BuildDriverFactory.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/coordinator/BuildCoordinator.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/coordinator/BuildScheduler.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/coordinator/BuildSchedulerFactory.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/coordinator/bpm/BpmBuildScheduler.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/coordinator/local/LocalBuildScheduler.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/datastore/DatastoreAdapter.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/executor/BuildExecutionTask.java, build-coordinator/src/main/java/org/jboss/pnc/core/builder/executor/BuildExecutor.java, build-coordinator/src/main/java/org/jboss/pnc/core/exception/CoreException.java, build-coordinator/src/test/java/org/jboss/pnc/core/BuildDriverFactoryTest.java, build-coordinator/src/test/java/org/jboss/pnc/core/test/buildExecutor/BuildExecution.java, build-coordinator/src/test/resources/testConfig.json, common/src/main/resources/pnc-config.json, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleprovider/PncConfigProvider.java, moduleconfig/src/main/resources/pnc-config.json, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java, rest/src/test/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpointTest.java
@slaskawi Do you find ok the renaming build-driver config to more general?
=> Add BuildScheduler selector.

build-coordinator/src/test/java/org/jboss/pnc/core/test/mock/RepositorySessionMock.java, docker-environment-driver/src/test/java/org/jboss/pnc/environment/docker/DockerEnvironmentDriverRemoteTest.java, jenkins-build-driver/src/test/java/org/jboss/pnc/jenkinsbuilddriver/test/JenkinsDriverRemoteTest.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositoryConstants.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractRepositoryManagerDriverTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesConfSetGroupTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesProductVersionGroupTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/DownloadTwoThenVerifyExtractedArtifactsContainThemTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadTwoThenVerifyExtractedArtifactsContainThemTest.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pom.xml, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
also implement direct promotion to shared-releases group
=> Update for AProx 0.24.0 with group promotion feature

rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductEndpoint.java
A few tweaks to the swagger api-docs declarations.
=> REST Tweaks

openshift-environment-driver/src/main/resources/openshift.configurations/v1_pnc-builder-pod.json
Based on https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go
=> NCL-1052 Added network capability to the pod

ui/app/common/util/confirm-click.js, ui/app/common/util/views/confirm-click.html
This is done by integrating modals with PNC.
=> [NCL-533] Improve confirmation panels

ui/app/import/product/ProductImportCtrl.js, ui/app/import/product/directive/ProductImportBCForm/product-import-bc-form.html
@jbartece verify and merge pls
=> Updated product import left-side form.

ui/app/common/util/confirm-click.js, ui/app/controllers.js, ui/app/import/product/ProductImportCtrl.js, ui/app/import/product/directive/ProductImportBCForm/ProductImportBCForm.js, ui/app/import/product/directive/ProductImportBCForm/product-import-bc-form.html, ui/app/import/product/directive/ProductImportStartForm/ProductImportStartForm.js, ui/app/import/product/directive/ProductImportStartForm/product-import-start-form.html, ui/app/import/product/directive/ProductImportTree/ProductImportTree.js, ui/app/import/product/directive/ProductImportTree/product-import-tree.html, ui/app/import/product/views/import.product.html, ui/app/index.html
Main changes:
- Disabled buttons when loading
- Validate all checked BC before finish
- Additional validations
- Menu can reset the import
- Disable next level analysis button when succesful
- Wait for finish of analysis & redirect to created product
=> Multiple product import fixes & tweaks.

ui/app/import/product/ProductImportCtrl.js
=> Do not validate form when existing BC is used.

integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java, rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationRest.java
=> Revert "Validating BC.name"

ui/app/configuration/_configuration.js, ui/app/project/_project.js
=> Remove temp. workarounds for NCL-1304, bug already fixed.

integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/test/java/org/jboss/pnc/model/BasicModelTest.java
@alexcreasy @matejonnet this should be cherry picked to 0.7 branch also
=> NCL-1354- Improved names for cloned BuildConfigurations - CLEANED

rest/src/main/java/org/jboss/pnc/rest/restmodel/ProductVersionRest.java
@alexcreasy @matejonnet this should be cherry picked to 0.7 branch also
=> Ncl 1447 / NCL-1338- CurrentMilestoneId attribute is not updated in ProductVersion

ui/app/common/templates/footer.tmpl.html
This important commit updates the footer of the webpage to the current year.
This commit is very important to the integrity of the webpage.
=> Happy New Year 2016! :)

ui/.gitignore, ui/Gruntfile.js
- Ports other than 8080 to be used
- Multiple active profiles with different configurations (proxying to
different servers)
- More configuration options
=> [NCL-1581] Enhanced grunt proxy configuration

ui/app/configuration-set/views/configuration-set.add.configuration.html, ui/app/configuration-set/views/configuration-set.create.html, ui/app/configuration-set/views/configuration-set.detail.html, ui/app/configuration/views/configuration.create.html, ui/app/configuration/views/configuration.detail-main.html, ui/app/import/product/directive/CreateProjectModal/create-project-modal.html, ui/app/import/product/directive/ProductImportBCForm/product-import-bc-form.html, ui/app/import/product/directive/ProductImportStartForm/product-import-start-form.html, ui/app/milestone/views/milestone.create-update.html, ui/app/product/views/product.create.html, ui/app/product/views/product.detail.html, ui/app/product/views/product.version.create.html, ui/app/product/views/product.version.html, ui/app/project/views/project.create.html, ui/app/project/views/project.detail.create-bc.html, ui/app/project/views/project.detail.html, ui/app/release/views/release.create-update.html
We add the upper input limit based on the database contraints.
Also, a few validations were added.
=> [NCL-1525] validate input length

build-coordinator/src/main/java/org/jboss/pnc/core/builder/datastore/DatastoreAdapter.java, datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, pnc-mock/src/main/java/org/jboss/pnc/mock/datastore/DatastoreMock.java, spi/src/main/java/org/jboss/pnc/spi/datastore/Datastore.java
Some refactoring caused an illegal operation to be performed outside of a transaction
=> [NCL-1618] Fix saving build record when running a build

ui/app/import/product/ProductImportCtrl.js, ui/app/import/product/directive/ProductImportBCForm/ProductImportBCForm.js, ui/app/import/product/directive/ProductImportBCForm/product-import-bc-form.html
The Product Import process should send keys 'environmentId' and
'projectId' instead of 'environment: {id: }' and 'project: {id: }'
=> [NCL-1620] Product->Import sends wrong data about enviroment and project

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/BuildRecordSpringRepository.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildRecordsTest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductReleaseEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, rest/src/main/java/org/jboss/pnc/rest/swagger/response/BuildRecordIds.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java
added method getAllBuildsInDistributedRecordsetOfProductRelease to ProductReleaseEndpoint
=> [NCL-995] Retrieve BuildRecords associated with a product release

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/BuildRecordSpringRepository.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildRecordsTest.java, model/src/main/java/org/jboss/pnc/model/ProductRelease.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductReleaseEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, rest/src/main/java/org/jboss/pnc/rest/swagger/response/BuildRecordIds.java
=> Porting of NCL-995 to 0.8 branch

ui/app/common/pagination/directives/pager.html, ui/app/styles/directives.css
@alexcreasy Thought that adding the total number of pages would be good, plus tooltips
=> Add tooltips and total page number to pagination directive

ui/app/common/pagination/directives/search-field.html, ui/app/common/pagination/directives/search-field.js, ui/app/styles/directives.css
(cherry picked from commit 512eaf78afc4c2a59bbe0b9a85cb5df8f82bc758)
=> Fixed several UX issues with UI search fields

build-coordinator/src/main/java/org/jboss/pnc/core/builder/datastore/DatastoreAdapter.java
Append the error message to the build log instead of overwriting the build log.
=> [NCL-1722] Store the build log if it's available during a system failure

datastore/src/main/java/org/jboss/pnc/datastore/predicates/rsql/AbstractTransformer.java, datastore/src/main/java/org/jboss/pnc/datastore/predicates/rsql/RSQLNodeTravellerPredicate.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildsRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/client/AbstractRestClient.java, integration-test/src/test/java/org/jboss/pnc/integration/client/util/BuildConfigurationAuditedDeserializer.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationAudited.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationAuditedRest.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildExecutionConfigurationRest.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildTaskEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/RunningBuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/UserEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
@alexcreasy Initial implementation for archived and running builds.
Examples of how it will work:
by userId : pnc-rest/rest/builds?q=(user.id==1)
by username: pnc-rest/rest/builds?q=(user.username==demo-user) / pnc-rest/rest/builds?q=(user.username=like=demo-user)
by buildconfigurationid: pnc-rest/rest/builds?q=buildConfigurationAudited.idRev.id==1
by buildconfigurationname: pnc-rest/rest/builds?q=buildConfigurationAudited.name==jboss-modules-1.5.0
NOTE: some endpoints are duplicated to verify correct functioning, will be polished later
=> Ncl 1157 rsql

build-coordinator/src/main/java/org/jboss/pnc/core/builder/coordinator/BuildCoordinator.java, rest-model/src/main/java/org/jboss/pnc/rest/utils/JsonOutputConverterMapper.java
An attempt to fix build retrying for twitter4j
=> [NCL-1706] sealing removing submitted task

ui/app/common/restclient/services/EnvironmentDAO.js
@alexcreasy Hi, there is missing PR for v0.8
=> Cannot search for Demo Environment in BC create

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
both promotions to shared-imports and build output.
=> [NCL-1827] Delete group (merged) metadata for promoted artifacts

ui/app/record/directives/pnc-live-log/pncLogCanvas.js
=> [NCL-1809] Add auto-toggle of autoscroll based on the user's scroll

ui/app/_pnc.js, ui/app/common/directives/pnc-select-items.js, ui/app/common/directives/views/pnc-select-items.html, ui/app/common/restclient/services/ReportDAO.js, ui/app/config.json, ui/app/index.html, ui/app/report/_report.js, ui/app/report/report-controllers.js, ui/app/report/views/product.shipped.artifacts.html, ui/app/styles/app.css, ui/app/styles/directives.css, ui/bower.json
@jbartece @alexcreasy @matejonnet Please review. I also added the new config param (DA_REPORT_REST_URL in ui/app/config.json) to the following Jenkins configs:
- http://10.8.49.240:8081/view/Newcastle/job/PNC_MASTER_SNAPSHOT/
- http://10.8.49.240:8081/view/Newcastle/job/PNC_v0.8_DEPLOY/
- http://10.8.49.240:8081/view/Newcastle/job/PNC_Pull_Requests/
- http://10.8.49.240:8081/view/Newcastle/job/PNC_MASTER_1_SNAPSHOT/
- http://10.8.49.240:8081/view/Newcastle/job/PNC_DEMO_DEPLOY/
=> Ncl 1881 - UI for alignment reports: show shipped artifacts in a product

rest/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConstants.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigSetRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationSetEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildEnvironmentEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildTaskEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/LicenseEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductMilestoneEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductReleaseEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductVersionEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProjectEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/RunningBuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/UserEndpoint.java
=> Fix typo in swagger constant INVLID_CODE

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildQueue.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildCoordinator.java
1. proper logging on error when build ends with error (unlike exception, error is rethrown)
1. fixed synchronization of buildQueue
=> NCL-1965 marking build as system error on Error

ui/app/common/restclient/services/ReportDAO.js, ui/app/config.json, ui/app/index.html, ui/app/report/_report.js, ui/app/report/report-controllers.js, ui/app/report/views/different.artifacts.in.products.html
@alexcreasy @jbartece It can be done much better, and there are many possible improvements to do, but this is what I can commit to for now, very little time.
Please review. Thanks!
=> NCL-1887 - UI for alignment reports: difference between the list of artifacts for 2 products

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/notifications/buildTask/BuildStatusNotifications.java, moduleconfig/src/main/resources/pnc-config.json, rest/src/main/java/org/jboss/pnc/rest/notifications/websockets/NotificationsEndpoint.java
=> Ncl 2034 build remains in unknown status

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java, ui/app/product/directives/pncProductVersionMilestones/pnc-product-version-milestones.html, ui/app/product/directives/pncProductVersions/pnc-product-versions.html, ui/app/product/directives/pncProductVersions/pncProductVersions.js
Just minor cleanup and improvements
=> Minor fixes

ui/app/common/authentication/directives/pncRequiresAuth.js, ui/app/configuration-set/_configuration-set.js, ui/app/configuration-set/views/configuration-set.detail.html, ui/app/configuration/_configuration.js, ui/app/configuration/views/configuration.detail-main.html, ui/app/product/_product.js, ui/app/product/views/product.detail.html, ui/app/product/views/product.version.html, ui/app/project/_project.js, ui/app/project/views/project.detail.html
(cherry picked from commit 084b1b7947a3398a7977c7e821242fa68974f24f)
=> NCL-1296 Disable action buttons when not logged in

web/src/main/java/org/jboss/pnc/web/UIConfigurationServlet.java
=> Use field injection and flush for stream in UIConfigurationServlet

web/src/main/java/org/jboss/pnc/web/UIConfigurationServlet.java
(cherry picked from commit c17c40a9aec919e2105a1c94168e9852d86cedab)
=> NCL-2073 Lazy loading of UI configuration

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositoryConnectionInfo.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AllSessionUrlsForBuildAreAlikeTest.java
=> NCL-1956 Use separate deployment URL to deploy directly to hosted repo

ui/app/common/restclient/services/BuildsDAO.js
(cherry picked from commit a73fda99346e5de87bfae39a494723ee1dc61e11)
=> NCL-2118 Fix search functionality on builds.list view

web/pom.xml, web/src/main/resources/META-INF/beans.xml
Cherry-picked from the v0.9 branch where the changes were made.
=> Fix problem with CDI in web configuration

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleprovider/PncConfigProvider.java, web/src/main/java/org/jboss/pnc/web/UIConfigurationServlet.java
=> claryfing ui config reading in ui config servlet

model/src/main/java/org/jboss/pnc/model/Artifact.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java, model/src/main/java/org/jboss/pnc/model/BuildEnvironment.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, model/src/main/java/org/jboss/pnc/model/License.java, model/src/main/java/org/jboss/pnc/model/Product.java, model/src/main/java/org/jboss/pnc/model/ProductMilestone.java, model/src/main/java/org/jboss/pnc/model/ProductRelease.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, model/src/main/java/org/jboss/pnc/model/Project.java, model/src/main/java/org/jboss/pnc/model/User.java
This prevents the app from trying to insert a string that is longer than the db column allows
=> [NCL-2198] Add size validation for all string fields in the model

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
Previously, the specific constraint violations were not added to the message
=> [NCL-2198] Fix error message for artifacts with constraint violations

ui/app/_pnc.js, ui/app/common/events/_events.js, ui/app/common/notifications/_notifications.js, ui/app/common/notifications/pncDrawerNotificationController.js, ui/app/common/notifications/pncNotify.js, ui/app/common/notifications/pncToastNotificationController.js, ui/app/common/notifications/views/heading.html, ui/app/common/notifications/views/notification-body.html, ui/app/common/notifications/views/notification-footer-include.html, ui/app/common/notifications/views/subheading.html, ui/app/configuration-set/directives/pncBCTab/pncBCTab.js, ui/app/configuration/configuration-controllers.js, ui/app/configuration/directives/pnc-configuration-create-panel/pncConfigurationCreatePanel.js, ui/app/import/product/ProductImportCtrl.js, ui/app/import/product/directive/CreateProjectModal/CreateProjectModal.js, ui/app/import/product/directive/ProductImportBCForm/ProductImportBCForm.js, ui/app/index.html, ui/app/services.js
This is the first commit adding the ability to create fancy toast
notifications.
* New Features Added
With that, we'll be able to show toast notifications with a link in
it. The link will execute a callback where, for example, you can open
a new link.
You can also add a kebab menu (declicous!) to perform several actions,
where each action will have a callback function associated with it.
* Notification Drawer
This commit also adds support for a notification drawer, where all the
notifications displayed are shown there also. This is useful in case
you missed a notification.
Clicking on the notification in the drawer will mark the notification
as read.
Clicking on 'X' on the notification when it is first shown will also
mark the notification as read in the notification drawer.
* pncNotify …
=> [NCL-2142] UI toasts notification needs improving

integration-test/src/test/java/org/jboss/pnc/integration/ProductVersionRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/client/ProductVersionRestClient.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/ProductVersionRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductVersionEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/ProductVersionProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/ProductVersionProviderTest.java
to allow bulk changing of associations
=> NCL-2450 Add PUT /prouct-versions/:id/build-configuration-sets endpoint

ui/app/common/events/_events.js
Link will redirect to the Builds link
=> [NCL-2142] Use link for Builds notifications

ui/app/configuration-set/directives/pncBCTab/pncBCTab.js, ui/app/import/product/ProductImportCtrl.js, ui/app/import/product/directive/CreateProjectModal/CreateProjectModal.js, ui/app/import/product/directive/ProductImportStartForm/ProductImportStartForm.js, ui/app/import/product/directive/ProductImportTree/ProductImportTree.js, ui/app/import/product/directive/ProductImportTree/TreeFactory.js, ui/app/product/directives/pncProductVersionBCSets/pncProductVersionBCSets.js, ui/app/product/directives/pncProductVersionBCs/pncProductVersionBCs.js, ui/app/report/report-controllers.js
(cherry picked from commit ced67af2ba37461e56de781084625eee99d8abfc)
=> NCL-2480 Incorrect use of the Lodash 3.x method fixed

ui/app/index.html
@thescouser89 tut, tut... always cleaning up after you :P
=> Fix login button styling

ui/app/record/directives/pnc-build-details/pnc-build-details.html, ui/app/styles/directives.css
(cherry picked from commit 2250cf1d5d5dd9833ecc7027dc7c9c2dff6c15be)
=> NCL-2515 Fixes external SCM url display on build-record.default view

ui/app/common/restclient/services/BpmDAO.js, ui/app/configuration/directives/pnc-configuration-create-panel/pncConfigurationCreatePanel.js
Do not merge this yet, UI & BPM support for this must be available at the same time.
=> NCL-2520 buildConfigurationSetIds parameter added

ui/app/configuration/directives/pnc-configuration-create-panel/pnc-configuration-create-panel.html
(cherry picked from commit d576e3ae422bff39c1c0c6e9ee2fdaf9494d2ca1)
=> NCL-2548 change gerrit user validation for internal scm repo

build-executor/pom.xml, build-executor/src/test/java/org/jboss/pnc/executor/IndyPromotionValidationtest.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/IndyPromotionValidationTest.java, pom.xml
Improve indy promotion validation error format.
Added debug test for this.
=> NCL-1903: improve indy promotion validation error format.

integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationSetRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/client/BuildConfigurationSetRestClient.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationSetRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationSetEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationSetProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/BuildConfigurationSetProviderTest.java
=> NCL-2401 Add PUT /build-configurations-sets/:id/build-configurations

integration-test/src/test/java/org/jboss/pnc/integration/ProductVersionRestTest.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, model/src/test/java/org/jboss/pnc/model/BasicModelTest.java, model/src/test/resources/basic-model-test-data.xml, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/ProductVersionRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductVersionEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/ProductVersionProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/ProductVersionProviderTest.java
Change brew tag prefix to be a classic attribute
=> Add attributes to the ProductVersion

ui/app/configuration-set-record/_record.js
(cherry picked from commit def6751306e9e9864c0e6bd4b91838be47d6d31b)
=> NCL-2608 Fix Group Builds button on primary navbar

ui/app/import/product/directive/ProductImportStartForm/product-import-start-form.html
(cherry picked from commit 747b0c4eab8c0b7a0b986d39c90b26a3d6311921)
=> NCL-2664 Improve form field help for optional repositories field

ui/app/product/views/product.version.html
(cherry picked from commit 9f937b36e5b70abf9e18d7fa0436322d6201e304)
=> NCL-2649 Add BREW_TAG_PREFIX to product version view

ui/app/report/_report.js, ui/app/report/report-controllers.js
(cherry picked from commit c856dac0ea4463d9294c1ee760ea17a5aa01e8ec)
=> NCL-2650 Fixes issue with diff a project and against product report

ui/app/milestone/views/milestone.close.html, ui/app/milestone/views/milestone.detail.html, ui/app/product/directives/pncProductVersionMilestones/pnc-product-version-milestones.html
(cherry picked from commit 103843470efede5c9eb1264e5f7f2c025d68a4aa)
=> NCL-2683 Rename milestone release to milestone close

openshift-environment-driver/src/main/resources/openshift.configurations/pnc-builder-pod.json
https://docs.openshift.org/latest/dev_guide/managing_images.html#image-pull-policy
=> [NCL-2909] Use latest builder images on Openshift

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/UIModuleConfig.java
(cherry picked from commit 5c25157236bcf620f6c5d1e289192f8510b4fd12)
=> NCL-3014 Put user's guide link into the pnc config

ui/bower.json
(cherry picked from commit 1ef09b42c7640b9bc8cf4f54c1a65a80836bf48b)
=> NCL-3059 Fixes Very high CPU usage on BuildConfiguration page

rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java, ui/app/build-records/views/build-records.detail.repour-result.html, ui/app/build-records/views/build-records.detail.result.html
=> Revert "NCL-3062 Improve speed of log file loading in UI"

ui/app/_pnc.js, ui/app/build-configs/_build-configs.js, ui/app/build-groups/_build-groups.js, ui/app/common/authentication/_authentication.js, ui/app/index.html, ui/bower.json
- Fixed state definition error
- Update states requiresAuth code to use new ui-router APIs
- Remove component routing hack
=> Upgrade angular-ui-router to 1.0.3

ui/app/index.js, ui/app/pnc.module.js
Handle cases where keycloak.js is not available due to certificate error.
=> [NCL-1494] Fail gracefully when not able to load keycloak.js

rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
This commit attempts to solve NCL-3111, where triggering a build group
will also start the 'deleted' build configurations.
If the user 'deletes' a build configuration, the build configuration is
actually archived, but still present in the database. However, the build
configuration set still points to the build configuration archived.
When the build configuration set build is triggered, Orch gets all the
build configurations for this build configuration set and builds it even
though some of those build configurations are archived.
So the possible solutions are:
- alter the build configurations built for a build configuration set to
ones that are not archived
- delete the link between the build configuration and its build
configuration sets when it gets archived
This commit chooses the …
=> [NCL-3111] archived buildconfig removed in buildconfigset

ui/app/build-configs/directives/pnc-create-build-config-wizard/pnc-create-build-config-wizard.html, ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js
(cherry picked from commit c17badb6686e02ba1506ae8d1916014904a3e0de)
=> NCL-3299 v1.2 Make wizard enforce validation

ui/app/index.html
(cherry picked from commit a108f392dd1da2d35e201c8382ca786fbdc062f5)
=> Fixed index.html dependencies

pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ProductVersionRepositoryMock.java, rest/src/main/java/org/jboss/pnc/rest/provider/ProductMilestoneProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/AbstractMilestoneReleaseTest.java
Please note that the data in this gif are all mock data.
=> [NCL-3112] Remove current flag from released milestone

ui/app/index.html
(cherry picked from commit b0b1d01aad51fa0a7065d7e9001dc5c8889f7afc)
=> Re-fixed index.html dependencies, after patternfly upgrade

ui/app/build-configs/directives/pnc-create-build-config-wizard/pnc-create-build-config-wizard.html, ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js
- NCL-3302 Wizard is still navigable after completion
- NCL-3303 Wizard next button incorrectly labelled on completion
(cherry picked from commit 1f9f8c04ab048cfe70f9119fb4f0b0be56cc0b5c)
=> Fixes NCL-3302 / NCL-3303 v1.2

ui/app/build-configs/directives/pnc-create-build-config-wizard/pnc-create-build-config-wizard.html, ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js
- NCL-3302 Wizard is still navigable after completion
- NCL-3303 Wizard next button incorrectly labelled on completion
=> Fixes NCL-3302 / NCL-3303

ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js
…errors are not correctly displayed.
(cherry picked from commit e06e616e5c477b6563524879be84f71bf3bef01c)
=> NCL-3359 v1.2

ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js
(cherry picked from commit fc532d5813124ad4c9fd9937514a4eabb68dd93a)
=> NCL-3405 Fix TypeError when productVersion not present

build-coordinator/pom.xml, build-coordinator/src/main/java/org/jboss/pnc/coordinator/TemporaryBuildsCleaner.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/TemporaryBuildsCleanupScheduler.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorFactory.java, common/src/main/java/org/jboss/pnc/common/util/TimeUtils.java, common/src/test/java/org/jboss/pnc/common/test/util/TimeUtilsTest.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigSetRecordRepositoryImpl.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java, datastore/src/test/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryTest.java, integration-test/src/test/java/org/jboss/pnc/integration/TemporaryBuildsCleanerTest.java, model/src/main/java/org/jboss/pnc/model/Artifact.java, model/src/main/java/org/jboss/pnc/model/BuildConfigSetRecord.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, model/src/test/java/org/jboss/pnc/model/AbstractModelTest.java, model/src/test/java/org/jboss/pnc/model/ArtifactTest.java, model/src/test/java/org/jboss/pnc/model/BasicModelTest.java, model/src/test/java/org/jboss/pnc/model/BuildRecordTest.java, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildConfigSetRecordRepositoryMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildConfigSetRecordPredicates.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildConfigSetRecordRepository.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriverTest.java
NOT READY TO BE MERGED - missing binding to the deletion of temporary builds, more tests should be written
=> [NCL-3511]: Create a scheduler for regular cleanup of temporary builds

model/src/main/resources/db-update/00001-from-1.2.0-to-1.3.0.sql
...in 1.2->1.3 migration script.
Also update id values in comments that were outdated after dropping one of the inserts.
=> [v1.3] Add sequence as default id value in TemporaryRepo

model/src/main/resources/db-update/00001-from-1.2.0-to-1.3.0.sql
=> Add sequence as default id value in TemporaryRepo

ui/app/build-records/views/build-records.detail.html, ui/app/common/pnc-client/resources/BuildRecord.js
(cherry picked from commit 942036610f16b7dd476d83cc8e5e51062c475d6e)
=> NCL-3458-v1.3 Cannot cancel a build that is waiting for dependencies

ui/app/build-records/views/build-records.detail.html, ui/app/common/pnc-client/resources/BuildRecord.js
merge conflicts]
(cherry picked from commit 15199b0cda5712cd2c967957b0ec390ca5caf980)
=> NCL-3458 Cannot cancel a build that is waiting for dependencies [Fixed

rest/src/main/java/org/jboss/pnc/rest/notifications/websockets/DefaultNotifier.java
ConcurentModificationException
=> [NCL-3674]: Use CopyOnWriteArrayList in Default notifier to prevent - 1.3

rest/src/main/java/org/jboss/pnc/rest/notifications/websockets/DefaultNotifier.java
ConcurentModificationException
=> [NCL-3674]: Use CopyOnWriteArrayList in Default notifier to prevent - master

rest/src/main/java/org/jboss/pnc/rest/utils/BpmNotifier.java
=> [NCL-3695]: Don't use toString method to pass parameters to Maitai - master

rest/src/main/java/org/jboss/pnc/rest/trigger/BuildTriggerer.java
=> [NCL-3734]: Fix lazyInizializationException when triggering a build w… - 1.3

rest/src/main/java/org/jboss/pnc/rest/trigger/BuildTriggerer.java
=> [NCL-3734]: Fix lazyInizializationException when triggering a build w… - master

ui/app/build-records/directives/pnc-build-record-push-button/pncBuildRecordPushButton.js
(cherry picked from commit 5501623e694c7f43c5e5715e9ae39580c86b53ee)
=> [v1.3] NCL-3747 Update UI to handle new response format from REST API

common/src/main/java/org/jboss/pnc/common/monitor/PullingMonitor.java
Monitor bug
-----------
The 'monitor' bug inside `PullingMonitor` class happens in situations
where the `monitor` runnable is run before `runningTaskReference` is set
with the running task since the runnable is scheduled to run before
`runningTaskReference` is set.
In those cases, we just skip this runnable run and re-run it on the next
scheduled interval with the assumption that `runningTaskReference` will
be set before the next re-run.
Without the fix, if the condition is true, we'll try to remove from the
'runningTasks' ConcurrentSet object a null object
('runningTaskReference' contains a null object, that null object is
assigned to variable 'runningTask' inside the runnable). This causes the
'remove' method to throw a NullPointerException.
Ironically, the NullPointerException is …
=> [v1.2] Fix monitor bug and builder image not starting

ui/app/build-records/directives/pnc-build-record-push-button/pnc-build-record-push-button.html
(cherry picked from commit 531c47faf73e2a03efa538800a347f756e35c6ec)
=> [v1.3] NCL-3680 Trigger login page on clicking [Push to Brew] button on build

ui/app/build-configs/directives/pnc-configuration-create-panel/pnc-configuration-create-panel.html, ui/app/build-configs/directives/pnc-create-build-config-general-form/pnc-create-build-config-general-form.html
(cherry picked from commit 8a4f1f57a17186c2aa3e38bcd294d571edf3e71b)
=> Add no spellcheck browser hint to buildscript textareas

README.md, ear-package/pom.xml, metrics/pom.xml, metrics/src/main/java/org/jboss/pnc/metrics/MetricsConfiguration.java, metrics/src/main/java/org/jboss/pnc/metrics/exceptions/NoPropertyException.java, pom.xml
=> Adding metrics reporting using dropwizard metrics

README.md, integration-test/src/test/resources/application.xml, metrics/src/main/java/org/jboss/pnc/metrics/MetricsConfiguration.java, rest/pom.xml, rest/src/main/java/org/jboss/pnc/rest/configuration/JaxRsActivator.java, rest/src/main/java/org/jboss/pnc/rest/configuration/metrics/GeneralRestMetricsFilter.java, rest/src/main/java/org/jboss/pnc/rest/configuration/metrics/TimedMetric.java, rest/src/main/java/org/jboss/pnc/rest/configuration/metrics/TimedMetricFilter.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigSetRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java
This PR includes:
- Add ability to specify rate of reporting data to Graphite
- Track all REST request metrics
- Track specific REST request metrics
=> [v1.3] Track REST endpoint metrics

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
While submitting a build, and sending build requests in quick
succession, we can create a race condition where the Coordinator does
not detect that we are sending the same build twice. By synchronizing
the build method by using a lock object, we ensure that this situation
does not happen.
=> [v1.3][NCL-3854] Add sychronization to build methods

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
While submitting a build, and sending build requests in quick
succession, we can create a race condition where the Coordinator does
not detect that we are sending the same build twice. By synchronizing
the build method by using a lock object, we ensure that this situation
does not happen.
=> [NCL-3854] Add synchronization to build methods

auth/src/main/java/org/jboss/pnc/auth/keycloakutil/util/HttpUtil.java
It is not enough to set the hostname verifier. It ignores errors when
the server hostname does not match the hostname the cerstificate was
issued for. We also have to use a trust manager that trusts everything
for cases when the certificate is not issued by a trusted authority.
=> [NCL-3855] Fix ignoring errors in SSL handshake

auth/src/main/java/org/jboss/pnc/auth/keycloakutil/util/HttpUtil.java
It is not enough to set the hostname verifier. It ignores errors when
the server hostname does not match the hostname the cerstificate was
issued for. We also have to use a trust manager that trusts everything
for cases when the certificate is not issued by a trusted authority.
=> [v1.3][NCL-3855] Fix ignoring errors in SSL handshake

model/src/main/resources/db-update/00001-from-1.2.0-to-1.3.0.sql
The fields are:
- buildlog
- repourlog
=> [v1.3] Add SQL instruction to populate md5/sha256/size for buildrecord

auth/pom.xml, bpm/pom.xml, build-coordinator/pom.xml, build-executor/pom.xml, causeway-client/pom.xml, common/pom.xml, datastore/pom.xml, demo-data/pom.xml, ear-package/pom.xml, indy-repository-manager/pom.xml, integration-test/pom.xml, messaging-spi/pom.xml, messaging/pom.xml, metrics/pom.xml, model/pom.xml, moduleconfig/pom.xml, openshift-environment-driver/pom.xml, pnc-mock/pom.xml, pom.xml, process-managers/pom.xml, rest-model/pom.xml, rest/pom.xml, spi/pom.xml, termd-build-driver/pom.xml, test-common/pom.xml, ui/pom.xml, web/pom.xml
The version was 1.4.0-SNAPSHOT, which could cause issues, because the same version is in branch v1.4.
=> Update version to 2.0.0-SNAPSHOT

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/CancelledBuildTest.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/ProjectBuilder.java, pnc-mock/src/main/java/org/jboss/pnc/mock/coordinator/BuildCoordinatorMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/executor/BuildExecutorMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/model/builders/TestProjectConfigurationBuilder.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/RunningBuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/trigger/BuildTriggerer.java, spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildCoordinator.java
@matejonnet Could you please advise with MDC in the new endpoint
=> [NCL-3896] Cancel BuildConfigSet endpoint

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, model/src/main/java/org/jboss/pnc/model/TargetRepository.java
=> NCL-4034 - cache targetRepository by identifier and path.

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java
=> Handle error while completing execution.

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
(cherry picked from commit 6cc2a10)
=> NCL-3983 - Fetch all BR properties when building dependency graph.

datastore/pom.xml, datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/ArtifactRepositoryImpl.java, datastore/src/test/java/org/jboss/pnc/datastore/DeploymentFactory.java, datastore/src/test/resources/logback.xml, datastore/src/test/resources/test-persistence.xml, model/src/main/java/org/jboss/pnc/model/Artifact.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ArtifactRepositoryMock.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ArtifactRepository.java
(cherry picked from commit 1a17feb)
=> Batch query to find all the artifacts.

ui/app/build-records/RecordResultController.js, ui/app/build-records/directives/pnc-build-details/pnc-build-details.html, ui/app/common/pnc-client/resources/BuildRecord.js
(cherry picked from commit 25850995871a3d4275776eaf8f2c3f27464d5475)
=> NCL-4050-v1.4

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
Skip promotion for generic proxy dependencies
=> [NCL-4088] No package type generic-http on Indy

ui/app/common/pnc-client/resources/RepositoryConfiguration.js, ui/app/repository-configurations/components/pncRepositoryConfigurationLink/pnc-repository-configuration-link.html, ui/app/repository-configurations/components/pncRepositoryConfigurationLink/pncRepositoryConfigurationLink.js, ui/app/repository-configurations/components/pncRepositoryConfigurationsList/pnc-repository-configurations-list.html, ui/app/repository-configurations/components/pncRepositoryConfigurationsList/pncRepositoryConfigurationsList.js, ui/app/repository-configurations/detail/pnc-repository-configuration-detail-page.html, ui/app/repository-configurations/repository-configurations.module.js
(cherry picked from commit ab6119ae70bdc9dc6481dc126d816de816c3cf54)
=> [v1.4] NCL-4048 Use human friendly identifier for RCs instead of DB ID

ui/app/styles/app.css
(cherry picked from commit d141ef423504d54c398562f41d681f5b9c1286bd)
=> [v1.4] NCL-4051 Increase size of build script widget in BC edit view

rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/BuildConfigurationProviderTest.java
=> [NCL-4115]: Fix NPE when using endpoint /build-configurations/{id}/up… - master

rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/BuildConfigurationProviderTest.java
=> [NCL-4115]: Fix NPE when using endpoint /build-configurations/{id}/up… - 1.4

constants/pom.xml, dto/pom.xml, dto/src/main/java/org/jboss/dto/BuildEnvironmentRef.java, facade/pom.xml, model/pom.xml, notifications/pom.xml, notifications/src/main/webapp/WEB-INF/web.xml, pom.xml, rest-api/pom.xml, rest-api/src/main/java/org/jboss/pnc/rest/api/BuildConfigurationEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConstants.java, rest-new/pom.xml, rest-new/src/main/webapp/WEB-INF/web.xml
I created new branch **rest-refactor** based from master, so the PRs can be merged into it and the master branch will keep working without breakage from the refactor. This PR is for that branch.
I included also a few example files, just to be sure I did it correctly.
=> [NCL-3881] Introduce new modules for REST Refactor

dto/src/main/java/org/jboss/pnc/dto/validation/constraints/RefHasId.java, dto/src/main/java/org/jboss/pnc/dto/validation/validators/RefHasIdValidator.java
Usage e.g.:
```java
@RefHasId(groups = WhenCreatingNew.class)
private final ProjectRef project;
@RefHasId(groups = {WhenCreatingNew.class, WhenUpdating.class})
protected final BuildEnvironmentRef environment;
@RefHasId(groups = {WhenCreatingNew.class, WhenUpdating.class}, optional = true)
private final ProductVersionRef productVersion;
```
=> Add @RefHasId validation constraint

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigSetRecordRepositoryImpl.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationSetRestTest.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java, model/src/main/resources/db-update/00003-from-1.4.0-to-2.0.0.sql, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildConfigSetRecordRepositoryMock.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationSetRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationSetEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationSetProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/BuildConfigurationSetProviderTest.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildConfigSetRecordPredicates.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildConfigurationSetPredicates.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildConfigSetRecordRepository.java
Implemented by archival of entity
=> [NCL-3702] Cannot delete BuildConfigSet

.github/PULL_REQUEST_TEMPLATE.md
Right now the checklist will ask the user if:
- she has added a changelog line if appropriate
- she has added a unit test if appropriate
=> Add PR template to add checklist for each PR

CHANGELOG.md, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java
=> [NCL-4214]: Temporary builds won't be assigned to a milestone anymore - 1.4

CHANGELOG.md, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java
=> [NCL-4214]: Temporary builds won't be assigned to a milestone anymore

pom.xml
The problematic dependency versions having CVE were found by Github
=> Update dependency versions to get CVE fixes

CHANGELOG.md, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/bpm/RepositoryCreationProcessRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BpmEndpoint.java
=> [NCL-4077] Send ref info to repo creation process

CHANGELOG.md, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
This reverts commit 6568e05b4e62e8f93fcf5b13db6d44147d66c141.
=> Revert "[NCL-4189] Execute debug scripts if debug mode on"

model/src/main/resources/db-update/00003-from-1.4.0-to-2.0.0.sql
=> Add schema update for buildtype column in BC

ui/app/build-records/directives/pnc-build-tree/pnc-build-tree.html, ui/app/build-records/directives/pnc-build-tree/pncBuildTree.js
=> NCL-4190 Improve Build Tree performance

ui/app/common/authentication/authentication.module.js, ui/app/pnc.module.js
=> NCL-4241 Fix error state transition

ui/app/build-records/RecordArtifactsController.js
=> [master] NCL-4257 Fixes: Unable to filter dependencies by repo type

ui/app/build-records/RecordArtifactsController.js
=> [v1.4] NCL-4257 Fixes: Unable to filter dependencies by repo type

CHANGELOG.md, rest/src/main/webconfig/auth/web.xml
=> [NCL-4236] Relax role constraint for authenticated users

CHANGELOG.md, bpm/src/main/java/org/jboss/pnc/bpm/task/BpmBuildTask.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/local/LocalBuildScheduler.java, model/src/main/java/org/jboss/pnc/model/utils/ContentIdentityManager.java
=> [NCL-4235]: Fix build content ID is not unique

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/ExpliciteDependenciesTest.java
=> Propagate force rebuild to dependencies.

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/DemoDataConfig.java, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleprovider/ModuleConfigFactory.java, moduleconfig/src/main/resources/pnc-config.json
* [NCL-3518] implemented loading internal repositories from pnc-config files
=> [NCL-3518] update demo data to contain valid SCM info

CHANGELOG.md, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-4219] Add generic proxy content promotion and set the promotion target as readonly

CHANGELOG.md, integration-test/src/test/java/org/jboss/pnc/integration/ProductVersionRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/client/ProductMilestoneRestClient.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductVersionEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/ProductVersionProvider.java, ui/app/common/restclient/services/ProductMilestoneDAO.js, ui/app/product/product-controllers.js, ui/app/product/product.module.js, ui/app/product/views/product.version.html
* [NCL-4117] added restriction on a user when trying to update product version name in the scenario of version having a closed milestone (both REST and UI)
* [NCL-4117] added integration test
=> [NCL-4117] restricting of editing Product Version name due to having closed milestone

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.4][NCL-4219] Fix target repo name for generic proxy content promotion

CHANGELOG.md, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java
=> [NCL-4294] Orch uses wrong credentials to create Indy repositories

CHANGELOG.md, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
=> [v1.4][NCL-4294] Orch uses wrong credentials to create Indy repositories

constants/src/main/java/org/jboss/pnc/enums/BPMTaskStatus.java, constants/src/main/java/org/jboss/pnc/enums/ReleaseStatus.java, dto/src/main/java/org/jboss/pnc/dto/internal/bpm/BPMNotification.java, dto/src/main/java/org/jboss/pnc/dto/internal/bpm/BPMTask.java, dto/src/main/java/org/jboss/pnc/dto/internal/bpm/BuildResult.java, dto/src/main/java/org/jboss/pnc/dto/internal/bpm/MilestoneReleaseResult.java, dto/src/main/java/org/jboss/pnc/dto/internal/bpm/ProcessProgressUpdate.java, dto/src/main/java/org/jboss/pnc/dto/internal/bpm/RepositoryCreationError.java, dto/src/main/java/org/jboss/pnc/dto/internal/bpm/RepositoryCreationSuccess.java, dto/src/main/java/org/jboss/pnc/dto/response/SSHCredentials.java, process-managers/src/test/java/org/jboss/pnc/managers/ProductMilestoneReleaseManagerTest.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BpmEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildTaskEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerGraphs.java, rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java, rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerSingletons.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/bpm/ProcessProgressUpdate.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/causeway/MilestoneReleaseResultRest.java, rest-model/src/test/java/org/jboss/pnc/restmodel/serialization/ProcessProgressUpdateTest.java, rest/src/main/java/org/jboss/pnc/rest/trigger/BuildExecutorTriggerer.java, rest/src/test/java/org/jboss/pnc/rest/provider/MilestoneReleaseTest.java
The BuildResult DTO is empty ATM. It was too complex for me to solve it quickly.
=> Implement remaining DTOs

CHANGELOG.md, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPushResultPredicates.java
=> [NCL-4300] build push status not updated 

model/src/main/java/org/jboss/pnc/model/ProductMilestone.java, model/src/main/java/org/jboss/pnc/model/ProductRelease.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, model/src/test/java/org/jboss/pnc/model/ProductMilestoneTest.java, model/src/test/java/org/jboss/pnc/model/VersionPatternTest.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/ProductMilestoneRest.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/ProductVersionRest.java
=> NCL-4269 - milestone and product release version

CHANGELOG.md, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPushResultPredicates.java
=> [NCL-4300] [v1.4] build push status not updated

rest/src/main/resources/buildConfigurationSupportedGenericParameters.properties
=> Add CUSTOM_PROJECT_MANIPULATOR_PARAMETERS to buildconfig

CHANGELOG.md, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.4][NCL-4274] An artifact from dependencies tab not found in Indy 

CHANGELOG.md
=> Cut version 1.4.3

CHANGELOG.md, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=>  [NCL-4274] An artifact from dependencies tab not found in Indy

ui/app/common/templates/footer.tmpl.html
=> New year, new footer

ui/app/common/templates/footer.tmpl.html, ui/bower.json
=> [v1.4] New year, new footer

rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildEnvironmentRest.java
=> Remove deprecated methods imageRepositoryUrl

rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java
=> Register ResteasyJackson2Provider.

rest-api/pom.xml, rest-api/src/main/java/org/jboss/pnc/client/ApacheHttpClient43EngineWithRetry.java, rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java, rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java, rest-api/src/test/resources/logback.xml
=> Add request re-try handler.

rest-api/src/main/java/org/jboss/pnc/client/DefaultRemoteCollection.java
=> Add total hits to the RemoteCollection.

CHANGELOG.md, rest/src/main/java/org/jboss/pnc/rest/provider/ProductVersionProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/ProductVersionProviderTest.java
=> [v1.4][NCL-4333] PNC-REST allows to set closed milestone as current

integration-test/src/test/java/org/jboss/pnc/integration/ProjectRestTestNewClient.java, processor/src/main/java/org/jboss/pnc/processor/ClientGenerator.java, rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java, rest-api/src/main/java/org/jboss/pnc/client/Configuration.java, rest-api/src/main/java/org/jboss/pnc/client/DefaultRemoteCollection.java, rest-api/src/main/java/org/jboss/pnc/client/RemoteCollectionConfig.java, rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java, rest-api/src/test/java/org/jboss/pnc/client/RemoteCollectionTest.java
=> NCL-4380 - fix java client page loader.

CHANGELOG.md, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.4][NCL-4274] Fix target repository of redhat dependencies

CHANGELOG.md, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-4274] Fix target repository of redhat dependencies

dto/src/main/java/org/jboss/pnc/dto/RunningBuildCount.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/RunningBuildsCountRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/RunningBuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java
=> [NCL-4392] Expose info about num of building and enqued builds

CHANGELOG.md, build-coordinator/src/main/java/org/jboss/pnc/coordinator/notifications/buildTask/BuildStatusMQNotifications.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/notifications/buildTask/MessageSenderProvider.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/notifications/buildTask/MessageSenderProviderTest.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorFactory.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractRepositoryManagerDriverTest.java, messaging-spi/src/main/java/org/jboss/pnc/messaging/spi/MessageSender.java, messaging-spi/src/main/java/org/jboss/pnc/messaging/spi/MessagingConfigurationException.java, messaging/pom.xml, messaging/src/main/java/org/jboss/pnc/messaging/DefaultMessageSender.java, messaging/src/main/java/org/jboss/pnc/messaging/UnreliableMessageSender.java, messaging/src/test/java/org/jboss/pnc/messaging/BaseMessageSenderTest.java, messaging/src/test/java/org/jboss/pnc/messaging/SysConfigProducer.java, messaging/src/test/java/org/jboss/pnc/messaging/UnreliableMessageSenderTest.java, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java, pnc-mock/src/main/java/org/jboss/pnc/mock/common/SystemConfigMock.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/DebugEndpoint.java
=> Add unreliable message sender.

CHANGELOG.md, causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/Build.java, causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/MavenBuild.java, process-managers/src/main/java/org/jboss/pnc/managers/BuildResultPushManager.java
=> Make buildRootVersion optional and add validation for buildRootName.

ui/app/build-records/directives/pnc-enter-brew-tag-name-modal/pnc-enter-brew-tag-name-modal.html
=> Fix typo: candiate -> candidate

ear-package/pom.xml, pom.xml, rest-new/pom.xml, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/webapp/WEB-INF/web.xml, rest-new/src/main/webconfig/auth/web.xml, rest-new/src/main/webconfig/noauth/web.xml
=> [NCL-4421] Add JAX-RS activator for new rest

integration-test/src/test/resources/application.xml, pom.xml, rest-new/pom.xml
=> Try to fix deployment

rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/AbstractEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java
=> [NCL-4351] RestEasy workaround

CHANGELOG.md, integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
* [X ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [X ] Have you added unit tests for your change?
=> NCL-4441 Create REST endpoint to restore a Build Config to a specific audited revision

ui/app/build-configs/detail/build-groups-tab/pnc-build-config-build-groups-tab.html, ui/app/build-configs/detail/build-groups-tab/pncBuildConfigBuildGroupsTab.js, ui/app/build-configs/detail/dependants-tab/pnc-build-config-dependants-tab.html, ui/app/build-configs/detail/dependants-tab/pncBuildConfigDependantsTab.js, ui/app/build-configs/detail/dependencies-tab/pnc-build-config-dependencies-tab.html, ui/app/build-configs/detail/details-tab/pnc-build-config-details-tab.html, ui/app/build-configs/detail/details-tab/pncBuildConfigDetailsTab.js, ui/app/build-configs/detail/pnc-build-config-detail-main.html, ui/app/build-configs/detail/revisions-tab/pnc-revisions-details.html, ui/app/build-configs/detail/revisions-tab/pncRevisionsDetails.js, ui/app/build-configs/directives/pnc-build-configs-data-table/pnc-build-configs-data-table.html, ui/app/build-configs/directives/pnc-build-configs-data-table/pncBuildConfigsDataTable.js, ui/app/build-groups/directives/pnc-build-groups-data-table/pnc-build-groups-data-table.html, ui/app/build-groups/directives/pnc-build-groups-data-table/pncBuildGroupsDataTable.js, ui/app/common/pnc-client/resources/BuildConfiguration.js
=> NCL-3635-ii Requested improvements

facade/pom.xml, facade/src/main/java/org/jboss/pnc/facade/providers/AbstractProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductReleaseProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildConfigurationProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/GroupConfigurationProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductReleaseProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductVersionProvider.java, facade/src/main/java/org/jboss/pnc/facade/validation/ConflictedEntryValidator.java, facade/src/main/java/org/jboss/pnc/facade/validation/ValidationBuilder.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductEndpoint.java, rest-new/pom.xml, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/AbstractEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductReleaseEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductVersionEndpointImpl.java
=> [NCL-4397] Product REST endpoint implementation

ui/app/build-configs/detail/revisions-tab/pncRevisionsDetails.js, ui/app/common/pnc-client/resources/BuildConfiguration.js
=> NCL-3635 Fixes bug with notifications when restoring a revision of a BC

rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java
=> Update base path of REST 2.0 client

pom.xml
=> Update Indy version to 1.7.4

facade/pom.xml, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationSupportedGenericParametersProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProjectProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildConfigurationProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildConfigurationSupportedGenericParametersProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/GroupConfigurationProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/ProjectProvider.java, facade/src/main/resources/buildConfigurationSupportedGenericParameters.properties, model/src/main/java/org/jboss/pnc/model/BuildConfigurationAudited.java, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProjectEndpointImpl.java
This commit does not contain the implementation of some endpoints for
triggering a build. This will be provided in a future commit.
Part of the reason for not implementing some endpoints is because it'll take time to get it ready to commit and during that time this might create more merge conflicts.
It'll also be nice for REST client users to be able to play with more available REST endpoints in the meantime.
=> [NCL-4398] Implement BuildConfig/Project REST endpoints

dto/src/main/java/org/jboss/pnc/dto/response/ErrorResponse.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/AllOtherExceptionsMapper.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/BuildConflictExceptionMapper.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/ValidationExceptionExceptionMapper.java
=> Add exception mappers for new REST

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/UserProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/EnvironmentProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/SCMRepositoryProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/UserProvider.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/EnvironmentEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/SCMRepositoryEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/UserEndpointImpl.java
Missing SCMRepository creation: will implement later
=> [NCL-4396] User, SCMRepository, Environment REST endpoints

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AllSessionUrlsForBuildAreAlikeTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesConfSetGroupTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesProductVersionGroupTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/DependencyUrlIncludesTrackingIdAndGeneratedBuildGroupNameTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/DownloadTwoThenVerifyExtractedArtifactsContainThemTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ExcludeInternalRepoByNameTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ExcludeInternalRepoByRegexTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ExtraDependencyRepositoriesTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ImportDepVerifyPromotionToSharedImportsTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/IndyPromotionValidationTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadOneThenDownloadAndVerifyArtifactHasOriginUrlTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadTwoThenVerifyExtractedArtifactsContainThemTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildGroupRemovedAfterArtifactExtractionTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildRepoPromotionToUntestedBuildsGroupTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualDeletionOfBuildRepoTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualPromotionOfBuildRepoTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositoryManagerMock.java, rest/src/main/resources/buildConfigurationSupportedGenericParameters.properties, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java
…fy public repository required by the build
=> [NCL-4439]: Add a new generic parameter for extra Repos

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/AllSessionUrlsForBuildAreAlikeTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/BuildGroupIncludesConfSetGroupTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/BuildGroupIncludesProductVersionGroupTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/DependencyUrlIncludesTrackingIdAndGeneratedBuildGroupNameTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/DownloadTwoThenVerifyExtractedArtifactsContainThemTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExcludeInternalRepoByNameTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExcludeInternalRepoByRegexTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExtraDependencyRepositoriesTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ImportDepVerifyPromotionToSharedImportsTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/IndyPromotionValidationTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/UploadOneThenDownloadAndVerifyArtifactHasOriginUrlTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/UploadTwoThenVerifyExtractedArtifactsContainThemTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyBuildGroupRemovedAfterArtifactExtractionTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyBuildRepoPromotionToUntestedBuildsGroupTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyManualDeletionOfBuildRepoTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyManualPromotionOfBuildRepoTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ExtraDependencyRepositoriesTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositoryManagerMock.java, rest/src/main/resources/buildConfigurationSupportedGenericParameters.properties, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java
=> [NCL-4439]: Add a new generic parameter for extra Repos - m

openshift-environment-driver/pom.xml, openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriver.java, openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pom.xml
This PR includes those 2 improvements to PNC 2.0:
- Track the number of openshift pod attempts, success, failed(and reason), retries
- Track a build final state (DONE, DONE_WITH_ERRORS, CANCELLED, SYSTEM_ERROR, etc)
=> Improve metrics by using GaugeMetrics (2.0)

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java, pom.xml
This PR includes 1 improvements to PNC 1.4.5:
- Track a build final state (DONE, DONE_WITH_ERRORS, CANCELLED, SYSTEM_ERROR, etc)
=> [v1.4] Improve metrics by using GaugeMetrics

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.4][NCL-4387] Simplify computation of target repo path for downloads

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildTaskEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/utils/BpmNotifier.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/TermdFileTranser.java
=> NCL-4482 - fix http post encoding.

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.4][NCL-4536] Promote also checksums

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-4536] Promote also checksums

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleaner.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanerAsyncInvoker.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java
=> [NCL-4142]: Fix deletion of temporary builds

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleaner.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanerAsyncInvoker.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java
=> [NCL-4142]: Fix deletion of temporary builds - M

model/src/main/java/org/jboss/pnc/model/Artifact.java
=> Clarify DELETED and TEMPORARY artifact qualities

constants/src/main/java/org/jboss/pnc/enums/ArtifactQuality.java
=> Clarify DELETED and TEMPORARY artifact qualities - M

rest-api/pom.xml, rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java, rest-api/src/main/java/org/jboss/pnc/client/ResteasyJackson2ProviderWithDateISO8601.java, rest-api/src/main/java/org/jboss/pnc/rest/jackson/JacksonProvider.java, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
Format Instant class into ISO8601 for dates in REST endpoint
Related: https://github.com/project-ncl/cli/pull/27
=> [NCL-4597] Format Instant class into ISO8601 for dates in REST endpoint

model/src/main/java/org/jboss/pnc/model/BuildRecord.java
=> Fix log size calculation.

datastore/src/main/java/org/jboss/pnc/datastore/predicates/rsql/RSQLNodeTravellerPredicate.java, facade/src/main/java/org/jboss/pnc/facade/rsql/EntityRSQLNodeTraveller.java, integration-test/src/test/java/org/jboss/pnc/integration/RSQLTest.java
=> [NCL-4484] RSQL like query now also accepts unix-like wildcard characters

CHANGELOG.md, build-executor/src/main/java/org/jboss/pnc/executor/BuildTypeToRepositoryType.java, constants/src/main/java/org/jboss/pnc/enums/BuildType.java
=> [NCL-4584] Add support for Gradle build type

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java, spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildTask.java
=> [v1.6][NCL-4334] Prevent adding builds to a closed milestone

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java, spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildTask.java
=> [NCL-4334] Prevent adding builds to a closed milestone

bpm/src/main/java/org/jboss/pnc/bpm/task/BpmBuildTask.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/local/LocalBuildScheduler.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionConfiguration.java, build-executor/src/test/java/org/jboss/pnc/executor/BuildEnvironmentTest.java, build-executor/src/test/java/org/jboss/pnc/executor/BuildExecutionBase.java, causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/MavenBuild.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildTasksRestTest.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, model/src/main/resources/db-update/00006-from-1.5.1-to-1.6.0.sql, pnc-mock/src/main/java/org/jboss/pnc/mock/executor/BuildExecutionConfigurationMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/spi/BuildExecutionConfigurationMock.java, process-managers/src/main/java/org/jboss/pnc/managers/BuildResultPushManager.java, process-managers/src/main/java/org/jboss/pnc/managers/ProductMilestoneReleaseManager.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildExecutionConfigurationRest.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordRest.java, rest-model/src/test/java/org/jboss/pnc/restmodel/serialization/BuildExecutionConfigurationTest.java, rest/src/test/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpointTest.java, rest/src/test/java/org/jboss/pnc/rest/provider/MilestoneReleaseTest.java, rest/src/test/java/org/jboss/pnc/rest/provider/MilestoneTestUtils.java, rest/src/test/java/org/jboss/pnc/rest/serialization/BuildExecutionConfigurationTest.java, spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionConfiguration.java
=> [NCL-4652]: Update orchestrator to add extra field for scmTag

ui/app/build-configs/buildTypes.js
=> [NCL-4584] Add Gradle build type selector to UI

facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConstants.java, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
=> Impl BuildEndpoint and NCL-3766: archive link of src

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
=> [NCL-3766] Generate download link, not UI link

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, facade/src/main/resources/buildConfigurationSupportedGenericParameters.properties, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/OpenshiftEnvironmentDriverModuleConfig.java, openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriver.java, openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/environmentdriver/EnvironmentDriverMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/environmentdriver/EnvironmentDriverWithFailedContainerInitializationMock.java, rest/src/main/resources/buildConfigurationSupportedGenericParameters.properties, spi/src/main/java/org/jboss/pnc/spi/environment/EnvironmentDriver.java
This is a backport of the NCL-4538 commit in v1.4/v1.5/v1.6/v1.7 branch
to master branch
=> [NCL-4538] Add new BUILDER_POD_MEMORY parameter

ui/app/common/pnc-client/pagination/pfFilterAdaptor.js
=> [master] NCL-4705 Artifact list view filter doesn't work

causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/Build.java, causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/MavenBuild.java
=> [NCL-4653] Update Cuaseway client for scmTag

rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java
This is useful for NCL-3766, to redirect to the correct link to download
the sources
=> [NCL-3768] Allow base client to redirect

.github/PULL_REQUEST_TEMPLATE.md
=> Update PR template to use changelog wiki

constants/src/main/java/org/jboss/pnc/enums/BuildCoordinationStatus.java
=> Set 'REJECTED_ALREADY_BUILT' status to 'final'

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
=> [NCL-4568] Add creationCompletablefuture creation

indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/AbstractRepositoryManagerDriverTest.java, pom.xml
=> NCL-4761 - Upgrade Indy client to latest version

facade/src/main/java/org/jboss/pnc/facade/mapper/api/BuildMapper.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
=> [NCL-4796] Implement getSpecific for builds

causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/BuildImportRequest.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildRecordPushTest.java, process-managers/src/main/java/org/jboss/pnc/managers/BuildResultPushManager.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordPushRequestRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordPushEndpoint.java
=> [NCL-4799] Add flag for Brew Push build reimport

termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
=> [v1.7][NCL-4823] Use env var ${HOME} to determine home path

termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
=> [NCL-4823] Use env var ${HOME} to determine home path

model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
=> [v1.7] When cloning, clone the buildtype also

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanupScheduleWorker.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanupScheduler.java
=> [NCL-4717]: Code cleanup in the TemporaryBuildsCleanup* classes 

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanupScheduleWorker.java
=> Improve logging in TemporaryBuildsCleanupScheduleWorker

ui/app/artifacts/artifacts.module.js, ui/app/artifacts/components/pnc-artifact-link/pnc-artifact-link.html, ui/app/artifacts/components/pnc-artifact-link/pncArtifactLink.js, ui/app/artifacts/detail/pnc-artifacts-detail-page.html, ui/app/artifacts/detail/pncArtifactsDetailPage.js, ui/app/artifacts/list/pnc-artifacts-list.html, ui/app/build-records/directives/pnc-build-record-link/pnc-build-record-link.html, ui/app/build-records/directives/pnc-build-record-link/pncBuildRecordLink.js, ui/app/build-records/directives/pnc-build-records-data-table/pnc-build-records-data-table.html, ui/app/build-records/directives/pnc-build-records-data-table/pncBuildRecordsDataTable.js, ui/app/build-records/directives/pnc-build-records-list/pnc-build-records-list.html, ui/app/common/filters/fileSize.js, ui/app/common/filters/filters.module.js, ui/app/common/pnc-client/resources/Artifact.js, ui/app/styles/directives.css
=> [master] NCL-4434 Artifact detail view

facade/src/main/java/org/jboss/pnc/facade/BuildTriggerer.java, facade/src/main/java/org/jboss/pnc/facade/impl/BuildTriggererImpl.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java, rest/src/main/java/org/jboss/pnc/rest/trigger/BuildTriggerer.java, spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildCoordinator.java
=> [NCL-4797]: Add implementation of an endpoint /builds/cancel

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleaner.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanupScheduleWorker.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanupScheduleWorkerImpl.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanupScheduler.java
=> [NCL-4717]: Temporary builds cleaner hits transaction limit and gets rollbacked - master

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanupScheduler.java
=> Run TemporaryBuildsCleanupScheduler on midnight

ui/.jshintrc, ui/app/artifacts/artifacts.module.js, ui/app/artifacts/components/pnc-artifact-link/pnc-artifact-link.html, ui/app/artifacts/components/pnc-artifact-link/pncArtifactLink.js, ui/app/artifacts/detail/pnc-artifacts-detail-page.html, ui/app/artifacts/detail/pncArtifactsDetailPage.js, ui/app/artifacts/list/pnc-artifacts-data-table.html, ui/app/artifacts/list/pnc-artifacts-list-page.html, ui/app/artifacts/list/pnc-artifacts-list.html, ui/app/artifacts/list/pncArtifactsDataTable.js, ui/app/artifacts/list/pncArtifactsList.js, ui/app/artifacts/list/pncArtifactsListPage.js, ui/app/build-records/directives/pnc-build-record-link/pnc-build-record-link.html, ui/app/build-records/directives/pnc-build-record-link/pncBuildRecordLink.js, ui/app/build-records/directives/pnc-build-records-data-table/pnc-build-records-data-table.html, ui/app/build-records/directives/pnc-build-records-data-table/pncBuildRecordsDataTable.js, ui/app/build-records/directives/pnc-build-records-list/pnc-build-records-list.html, ui/app/common/filters/fileSize.js, ui/app/common/filters/filters.module.js, ui/app/common/pnc-client/pagination/pfFilterAdaptor.js, ui/app/common/pnc-client/resources/Artifact.js, ui/app/index.html, ui/app/pnc.module.js, ui/app/styles/directives.css
(cherry picked from commit ab19a18dbaa03c3e2c69f869231edd1d5d47acf8)
=> [v1.7] NCL-4705, NCL-4434, NCL-4435 Backport artifact views to v1.7

constants/src/main/java/org/jboss/pnc/enums/BuildPushStatus.java, dto/src/main/java/org/jboss/pnc/dto/requests/BuildPushRequest.java, facade/src/main/java/org/jboss/pnc/facade/BrewPusher.java, facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java, process-managers/src/main/java/org/jboss/pnc/managers/BuildResultPushManager.java, process-managers/src/main/java/org/jboss/pnc/managers/Result.java, process-managers/src/test/java/org/jboss/pnc/managers/ResultSerializationTest.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
=> [NCL-4795] Implement Brew push endpoints

constants/src/main/java/org/jboss/pnc/constants/Attributes.java, constants/src/main/java/org/jboss/pnc/constants/Patterns.java, dto/src/main/java/org/jboss/pnc/dto/Build.java, dto/src/main/java/org/jboss/pnc/dto/BuildRef.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/BuildMapper.java, integration-test/src/test/java/org/jboss/pnc/integration/ProductVersionRestTest.java, model/src/main/java/org/jboss/pnc/model/Artifact.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, model/src/test/java/org/jboss/pnc/model/BasicModelTest.java
This change is needed to be merged before the Causeway part!
=> [NCL-4254] added field for DTO and moved a const

datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/AbstractRepository.java, facade/src/main/java/org/jboss/pnc/facade/providers/AbstractProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java, model/src/main/java/org/jboss/pnc/model/Artifact.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/RepositoryMock.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/Repository.java
=> [NCL-4801]: Use flushAndRefresh method to resolve issues with storing artifacts

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java, rest/src/main/java/org/jboss/pnc/rest/provider/ArtifactProvider.java
=> [NCL-4917] Fix storage and display of generic http downloads' paths

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, rest/src/main/java/org/jboss/pnc/rest/provider/ArtifactProvider.java
=> [v1.7] [NCL-4917] Fix storage and display of generic http downloads' paths

build-coordinator/pom.xml, build-executor/pom.xml, datastore/pom.xml, demo-data/pom.xml, pom.xml, spi/pom.xml
=> Downgrade to EAP 7.2

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinationTest.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/ProjectWithFailedDependenciesBuildTest.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/ProjectWithFailedTransitiveDependenciesBuildTest.java
=> [NCL-4110] Store reason for rejected build

constants/src/main/java/org/jboss/pnc/constants/Attributes.java, facade/src/main/java/org/jboss/pnc/facade/mapper/BrewNameWorkaround.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/ArtifactMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/BuildMapper.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, integration-test/src/test/java/org/jboss/pnc/integration/ProductVersionRestTest.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, model/src/test/java/org/jboss/pnc/model/BasicModelTest.java
=> [NCL-4889] Add workarounds for Brew build name/version as attributes

pom.xml
=> NCL-4923 - Monitor all the JVM processes consumption in the pod

pom.xml
=> [master] NCL-4923 - Monitor all the JVM processes consumption in the pod

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java, facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducer.java, facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java, facade/src/main/java/org/jboss/pnc/facade/util/MergeIterator.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildIteratorTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java, facade/src/test/java/org/jboss/pnc/facade/util/MergeIteratorTest.java, pom.xml, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/UserEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProjectEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/UserEndpointImpl.java
=> [NCL-4771] implement build list returning endpoints

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildConfigurationRSQLMapper.java
=> [NCL-4974] Fixed rsql mapping typo for BCs

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-4917] Fix generic http path computation

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.7] [NCL-4917] Fix generic http path computation

facade/src/main/java/org/jboss/pnc/facade/mapper/api/ArtifactMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/BuildConfigurationMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/BuildConfigurationRevisionMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/BuildMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/EnvironmentMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/GroupBuildMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/GroupConfigurationMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/ProductMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/ProductMilestoneMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/ProductReleaseMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/ProductVersionMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/ProjectMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/SCMRepositoryMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/TargetRepositoryMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/UserMapper.java
=> Added null check to Mappers

auth/src/main/java/org/jboss/pnc/auth/DefaultKeycloakServiceClient.java, auth/src/test/java/org/jboss/pnc/KeycloakServiceClientTest.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorFactory.java, causeway-client/src/test/java/org/jboss/pnc/causewayclient/CausewayClientRemoteTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/AbstractRepositoryManagerDriverTest.java, integration-test/src/test/java/org/jboss/pnc/AbstractTest.java, integration-test/src/test/java/org/jboss/pnc/integration/deployments/Deployments.java, integration-test/src/test/java/org/jboss/pnc/integration_new/setup/Deployments.java, integration-test/src/test/java/org/jboss/pnc/mock/auth/KeycloakServiceClientMock.java, integration-test/src/test/resources/beans-use-mock-remote-clients.xml, messaging/src/test/java/org/jboss/pnc/messaging/SysConfigProducer.java, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java, pnc-mock/src/main/java/org/jboss/pnc/mock/common/SystemConfigMock.java
=> Cache access tokens.

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildConfigurationRSQLMapper.java
=> [RR] Better exception message when repository creation conflicts

bpm/src/main/java/org/jboss/pnc/bpm/model/RepositoryCreationDataWrapper.java, facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BpmEndpoint.java
=> [NCL-4956] Properly deserialize Maitai content

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositoryManagerMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositorySessionMock.java, pom.xml, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
=> [v1.7][NCL-4910] Drop Indy client cache

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRunningDeletion.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java, moduleconfig/src/test/java/org/jboss/pnc/common/json/moduleconfig/MavenRepoDriverModuleConfigTest.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositoryConnectionInfo.java
=> Code cleanups

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositoryManagerMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositorySessionMock.java, pom.xml, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositoryConnectionInfo.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
=> [NCL-4910] Drop Indy client cache

facade/src/main/java/org/jboss/pnc/facade/mapper/api/GroupConfigurationMapper.java, facade/src/main/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderImpl.java, integration-test/src/test/java/org/jboss/pnc/integration_new/GroupConfigEndpointTest.java
=> [NCL-4952] Map Group Configs DTOs to DB entities as active

facade/src/main/java/org/jboss/pnc/facade/rsql/ComparatorRSQLNodeTraveller.java, facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducer.java, facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java, facade/src/test/java/org/jboss/pnc/facade/rsql/RSQLPredicateProducerTest.java
=>  [NCL-4898] implement RSQLProducer DTO getComparator

constants/src/main/java/org/jboss/pnc/constants/Attributes.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/EJBExceptionMapper.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/UnauthorizedExceptionMapper.java
@matedo1 This should resolve your message and status code issues.
=> [RR] fixed REST Exception handling when EJBException is thrown

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildConfigurationProvider.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildConfigurationAuditedRepository.java
=> [NCL-4770]: Add implementation of REST endpoint /build-configuration/{id}/revisions/{rev}/restore

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildIteratorTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
=> [NCL-4771] Fix build list RSQL query and getAll endpoint

rest-new/src/main/webconfig/auth/web.xml
=> Restrict PATCH requests.

rest-new/src/main/java/org/jboss/pnc/rest/provider/RespondWithStatusFilter.java
=> [NCL-4965] Fix NPE on RespondWithStatusFilter

model/src/main/java/org/jboss/pnc/model/RepositoryConfiguration.java
=> [NCL-3992] treat empty string as null for the externalUrl in the RepositoryConfiguration

model/src/main/java/org/jboss/pnc/model/RepositoryConfiguration.java
=> [v1.7] [NCL-3992] treat empty string as null for the externalUrl in the RepositoryConfiguration

dto/src/main/java/org/jboss/pnc/dto/Build.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/BuildMapper.java, facade/src/main/java/org/jboss/pnc/facade/mapper/api/GroupBuildMapper.java
=> [NCL-4228] [RR] Expose groupBuild in Build DTO

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupBuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
=> [NCL-4965] Add @RespondWithStatus for ACCEPTED_CODE

rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/AllOtherExceptionsMapper.java
=> [RR] registered ExceptionMappers and code cleanup

rest-api/src/main/java/org/jboss/pnc/rest/annotation/RespondWithStatus.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupConfigurationEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductReleaseEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductVersionEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProjectEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/RespondWithStatusFilter.java
=> Rework annotation RespondWithStatus not to parse String in every request

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupBuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
=> [NCL-4965] Fix compile error

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildConfigurationProvider.java, integration-test/src/test/java/org/jboss/pnc/integration_new/SCMRepositoryEndpointTest.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/SCMRepositoryEndpointImpl.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildConfigurationPredicates.java
=> [NCL-4946] add /scm-repositories/{id}/build-configs endpoint

rest-new/src/main/java/org/jboss/pnc/rest/provider/RespondWithStatusFilter.java
=> [NCL-4965] Remove check for OPTIONS http header

pom.xml
=> Update to pncmetrics 1.1.2

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConstants.java
=> [NCL-4960] Add better description for create-and-sync

pom.xml
=> [v1.7][NCL-5014] Update Indy client to fix the jhttpc Timer's thread closing

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/TargetRepositoryRepositoryImpl.java, model/src/main/java/org/jboss/pnc/model/TargetRepository.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/TargetRepositoryRepositoryMock.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/TargetRepositoryPredicates.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/TargetRepositoryRepository.java
=> NCL-5015 - improve target repository linking.

facade/pom.xml
=> Remove unsued deps for mapper in facade

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
=> NCL-5037 - fix targetRepository optimization.

ui/.jshintrc, ui/app/common/pnc-client/resources/helpers/patchHelper.js, ui/app/common/pnc-client/resources/helpers/resourceHelper.js, ui/app/common/pnc-client/resources/resources.module.js, ui/app/index.html, ui/bower.json
=> NCL-5038 UI support for PATCH methods

ui/app/common/restclient/services/BuildConfigurationDAO.js
=> NCL-5054 fixes The build config search does not work from project view

ui/app/build-records/RecordDetailController.js, ui/app/build-records/directives/pnc-build-details/pnc-build-details.html, ui/app/build-records/directives/pnc-build-details/pncBuildDetails.js, ui/app/build-records/views/build-records.detail.html, ui/app/common/pnc-client/resources/helpers/buildStatusHelper.js
=> Ncl 5059 master

ui/app/build-records/RecordDetailController.js, ui/app/build-records/directives/pnc-build-details/pnc-build-details.html, ui/app/build-records/directives/pnc-build-details/pncBuildDetails.js, ui/app/build-records/views/build-records.detail.html, ui/app/common/pnc-client/resources/helpers/buildStatusHelper.js
-  NCL-5059 UI displays incorrect scary warning next to SCM repo on BuildRecord page
-  NCL-4304 Plain Text Log is not available when a build is in progress
=> [1.7] NCL-5059 NCL-4304

rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BpmEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BpmEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildTaskEndpoint.java
=> [NCL-4395] Implementation of BPMEndpoint

dto/src/main/java/org/jboss/pnc/dto/ArtifactRef.java, dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRef.java, dto/src/main/java/org/jboss/pnc/dto/BuildRef.java, dto/src/main/java/org/jboss/pnc/dto/GroupBuildRef.java, dto/src/main/java/org/jboss/pnc/dto/GroupConfigurationRef.java, dto/src/main/java/org/jboss/pnc/dto/ProductMilestoneRef.java, dto/src/main/java/org/jboss/pnc/dto/ProductRef.java, dto/src/main/java/org/jboss/pnc/dto/ProductReleaseRef.java, dto/src/main/java/org/jboss/pnc/dto/ProductVersionRef.java, dto/src/main/java/org/jboss/pnc/dto/ProjectRef.java, dto/src/main/java/org/jboss/pnc/dto/TargetRepositoryRef.java
by ignoring unknown properties
=> [NCL-4954] Enable full DTOs to be used as Refs

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/DebugEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/DebugEndpoint.java
=> [NCL-4913]: Implement Debug endpoints

facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordPushEndpoint.java
=> [NCL-5078] fixed callback url for brew-push

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.7] NCL-4600 Do not rely on error field only in promotion result

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> NCL-4600 Do not rely on error field only in promotion result

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java, pom.xml
This is prepared for the moment when Indy 1.8.3 gets released.
=> [NCL-5014] Fix closing of Timer threads in Indy client

pom.xml
Cannot be merged until Indy 1.8.3 is released.
=> [v1.7] [NCL-5014] Update Indy to released version

facade/src/main/resources/buildConfigurationSupportedGenericParameters.properties, model/src/main/resources/db-update/10001-from-1.7.x-to-2.0.0.sql, rest/src/main/resources/buildConfigurationSupportedGenericParameters.properties
=> NCL-4888 - Change EXECUTION_ROOT_NAME parameter name

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
=> Fix generic parameter look-up in BrewPush.

common/src/main/java/org/jboss/pnc/common/mdc/MDCUtils.java, rest/src/main/java/org/jboss/pnc/rest/configuration/MDCLoggingFilter.java
=> Clear MDC on new requests.

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [1.7] [NCL-5093] Do not promote NPM metadata

indy-repository-manager/src/test/resources/infinispan.xml
=> Fix infinispan schema url

ui/app/build-records/directives/pnc-build-record-link/pncBuildRecordLink.js, ui/app/build-records/directives/pnc-build-tree/pnc-build-tree-link.html, ui/app/common/components/pnc-build-status/pnc-build-status.html, ui/app/common/events/events.module.js, ui/app/configuration-set-record/views/record.detail.output.html
* [X ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
=> NCL-5110 Backport fix for broken back button to v1.7

facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/ArtifactProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/EnvironmentProviderTest.java
=> [NCL-4999] implemented test for EnvironmentProvider

facade/src/main/java/org/jboss/pnc/facade/providers/ProductProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductProviderImplTest.java
=> [NCL-5003] Unit test for ProductProvider

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/ArtifactProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildConfigProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
=> [NCL-4996] implemented tests for BCProvider

constants/src/main/java/org/jboss/pnc/enums/JobNotificationType.java, dto/src/main/java/org/jboss/pnc/dto/notification/RepositoryCreationFailure.java, facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
=> typo in JobNotificationType

facade/src/main/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/EnvironmentProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductVersionProviderTest.java
=> [NCL-5005] ProductVersionProvider unit tests

facade/src/main/resources/buildConfigurationSupportedGenericParameters.properties, facade/src/test/java/org/jboss/pnc/facade/providers/BuildConfigurationSupportedGenericParametersProviderTest.java
=> [NCL-4997] BCSupportedGenericParametersProvider unit test

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [NCL-5093] Filter NPM metadata also from saving to DB

facade/src/main/java/org/jboss/pnc/facade/providers/UserProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/UserProviderImplTest.java
=> [NCL-5007] Unit tests for UserProvider

ui/bower.json
I also created patternfly related github issue https://github.com/patternfly/patternfly/issues/1187
=> NCL-5126 Force jQuery version

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-5107] log time it took through Indy promotion process

rest/src/main/java/org/jboss/pnc/rest/provider/ArtifactProvider.java
=> [NCL-5124] Fix download url for NPM dependencies

pom.xml
This will give us rate of error for our REST endpoints
CC: @vibe13
=> Update pncmetrics to 1.1.3

pom.xml
This will give us error rates for our REST endpoints
CC: @vibe13
=> [v1.8] Update pncmetrics to 1.1.3

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, pom.xml
=> [v1.7][NCL-5129] Fix processing NPM scoped downloads

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, pom.xml
=> [v1.8][NCL-5129] Fix processing NPM scoped downloads

facade/src/main/java/org/jboss/pnc/facade/providers/ProductReleaseProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductReleaseProviderTest.java
=> [NCL-5004] Add ProductReleaseProviderTest

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java, openshift-environment-driver/src/main/resources/openshift.configurations/pnc-builder-pod.json
=> Pass logging context to the build environment.

ui/app/index.html, ui/bower.json
Otherwise patternfly.notification module is not able to load
=> Downgrade angular-patternfly to 5.0.1

integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildConfigurationEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildConfigurationSerializationTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/GroupConfigEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/GroupConfigurationEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/SCMRepositoryEndpointTest.java
=> Move endpoint tests to 'endpoint' module

facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
This commit also triggers extra validation on updates
=> [NCL-5002] Add ProductMilestoneProviderTest

integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/EnvironmentEndpointTest.java
=> [NCL-4984] Implement Environment Endpoint Test

integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ProductReleaseEndpointTest.java
=> [NCL-4989] Implement Product Release Endpoint Test

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.7] [NCL-5150] Fix processing of scoped paths in NPM downloads 

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.8] [NCL-5150] Fix processing of scoped paths in NPM downloads

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.8] Artifact promotion enhancements

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- unify error processing when reading result of dependencies promotion
- do not try promotion rollback when promotion failed
- do not store NPM package metadata into downloads list
=> [v1.7] Artifact promotion enhancements

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> Better handling dependencies promotion

facade/src/main/java/org/jboss/pnc/facade/providers/UserProviderImpl.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/UserEndpointTest.java, model/src/main/java/org/jboss/pnc/model/User.java
=> [NCL-4993] Add UserEndpointTest

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/GroupBuildRSQLMapper.java
=> [NCL-5162] created GroupBuildRSQLMapper

common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java, rest-new/src/main/java/org/jboss/pnc/rest/RequestLoggingFilter.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildTaskEndpoint.java
=> Fix adding process context.

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionSession.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositorySessionMock.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
=> [v1.8][NCL-5105] Delete build group when a build is cancelled

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionSession.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositorySessionMock.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
=> [NCL-5105] Delete build group when a build is cancelled

auth/src/main/java/org/jboss/pnc/auth/KeycloakLoggedInUser.java
=> [NCL-5164]: Do not print user token to logs

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildRSQLMapper.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/GroupBuildRSQLMapper.java
=> [NCL-5182] upgrade Build and GBuild RSQL mappers

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java, facade/src/main/java/org/jboss/pnc/facade/util/GraphDtoBuilder.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/GroupBuildEndpointImpl.java
=> [NCL-5175] [RR] implement dependency graph endpoints

facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildConfigProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderTest.java
=> [NCL-5001] add GroupConfigurationProvider unit tests

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
This is based on the fact that PNC 2.0 will show all userLog logs to the
user via UI
=> [NCL-5107] Show to user steps in promotion

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> Fix typo on IndyRepositorySession

build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorDeployments.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildConfigurationEndpointTest.java, mapper/src/main/java/org/jboss/pnc/mapper/BuildBCRevisionFetcher.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
=> [NCL-4981] Implement Build Configuration Endpoint Test

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationAuditedRepositoryImpl.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildsRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/UserRestTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildConfigurationAuditedRepositoryMock.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildConfigurationAuditedRepository.java
…Records; collect all BuildConfigurationAudited entities in one query rather than looping
@thescouser89 @matejonnet @jbartece Trying to optimize heavy endpoint
=> [v1.8] NCL-5184 - Optimize queries to minimize CPU load and DB usage when hitting particular endpoints

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java
=> [v1.8][NCL-5107] Call the right method to pass buildExecutionSession

facade/src/main/java/org/jboss/pnc/facade/providers/GroupBuildProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/GroupBuildProviderTest.java
=> [NCL-5000] create GroupBuildProviderTest

dto/src/main/java/org/jboss/pnc/dto/Product.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ProductEndpointTest.java
=> [NCL-4987] Add Patch integration test for Product Endpoint

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java
=> [NCL-5008] Add SCMRepositoryProviderTest

rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java
=> Remove unnecessary boxing and unboxing

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java
=> [v1.8] [NCL-5192] fix temporaryBuilds falsely rebuilding if there is newer persistent record

common/src/main/java/org/jboss/pnc/common/util/UrlUtils.java, model/src/main/java/org/jboss/pnc/model/RepositoryConfiguration.java, model/src/test/java/org/jboss/pnc/model/RepositoryConfigurationTest.java
=> [NCL-4506] fix normalization of URLs

integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildConfigurationEndpointTest.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupConfigurationEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/GroupConfigurationEndpointImpl.java
No, I removed some :smiling_imp:
=> Remove DELETE operations on Build and Group Config endpoints

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationAuditedRepositoryImpl.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildConfigurationAuditedRepositoryMock.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildConfigurationAuditedRepository.java
=> NCL-5184 - Optimize queries to minimize CPU load and DB usage when hitting particular endpoints

pom.xml
=> Update Postgres dialect to the latest PostgreSQL95Dialect

dto/src/main/java/org/jboss/pnc/dto/response/Edge.java, dto/src/main/java/org/jboss/pnc/dto/response/Graph.java, dto/src/main/java/org/jboss/pnc/dto/response/Vertex.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/GroupBuildEndpointTest.java
=> [NCL-4985] Add GroupBuildEndpointTest

bpm/src/main/java/org/jboss/pnc/bpm/model/BuildDriverResultRest.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/event/StatusUpdatesTest.java, build-executor/src/test/java/org/jboss/pnc/executor/BuildDriverFactoryTest.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, pnc-mock/src/main/java/org/jboss/pnc/mock/builddriver/BuildDriverBase.java, pnc-mock/src/main/java/org/jboss/pnc/mock/builddriver/BuildDriverResultMock.java, pom.xml, spi/src/main/java/org/jboss/pnc/spi/builddriver/BuildDriver.java, spi/src/main/java/org/jboss/pnc/spi/builddriver/BuildDriverResult.java, spi/src/main/java/org/jboss/pnc/spi/builddriver/exception/BuildDriverException.java, termd-build-driver/pom.xml, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultCompletedBuild.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocationCompletion.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdRunningBuild.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriverTest.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdServer.java
=> Store build output log checksum to BuildRecord.

model/src/main/resources/db-update/10001-from-1.7.x-to-2.0.0.sql
=> Add update table query to add buildoutputchecksum

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/TermdBuildDriverModuleConfig.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/ClientFactory.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/DefaultFileTranser.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/FileTranser.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/AbstractLocalBuildAgentTest.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/LivenessProbeTest.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriverTest.java
=> Build environment liveness probe.

mapper/src/main/java/org/jboss/pnc/mapper/BuildBCRevisionFetcher.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java
=> [NCL-5257] Map also entities from BCA in BuildBCRevisionFetcher

ear-package/pom.xml, integration-test/src/test/java/org/jboss/pnc/integration_new/EAPModulesAccessTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/setup/Deployments.java, integration-test/src/test/resources/arquillian.xml, pom.xml
=> Add missing EAP module dependencies.

rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
=> Fix slashes in auth URL in OpenAPI

common/src/main/java/org/jboss/pnc/common/util/UrlUtils.java, model/src/main/java/org/jboss/pnc/model/RepositoryConfiguration.java, model/src/main/resources/db-update/00006-from-1.4.4-to-1.4.5.sql, model/src/main/resources/db-update/00006-from-1.7.1-to-1.8.0.sql, model/src/test/java/org/jboss/pnc/model/RepositoryConfigurationTest.java
=> [NCL-4506] [v1.8] fixed normalization of urls in RepoConfig

facade/src/main/java/org/jboss/pnc/facade/rsql/ComparatorRSQLNodeTraveller.java, facade/src/main/java/org/jboss/pnc/facade/rsql/EntityRSQLNodeTraveller.java, facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLException.java, facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java, facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLSelectorPath.java, facade/src/main/java/org/jboss/pnc/facade/rsql/SortRSQLNodeTraveller.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/AbstractRSQLMapper.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/UniversalRSQLMapper.java, facade/src/test/java/org/jboss/pnc/facade/rsql/RSQLPredicateProducerTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/RSQLTest.java, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/RSQLExceptionMapper.java
=> [NCL-5252][NCL-5213] Map RSQL arguments to propper types and improve error reporting

termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java
=> Allow empty output checksum.

dto/src/main/java/org/jboss/pnc/dto/notification/GroupBuildChangedNotification.java
=> Groups status update PENDING for status NEW.

common/src/main/java/org/jboss/pnc/common/util/ProcessStageUtils.java
=> [v1.8][NCL-5267] Minor code cleanup

integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildRecordAliasEndpointTest.java, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildRecordAliasEndpointImpl.java
=> [NCL-4712] add backward compatible build-record endpoint

dto/src/main/java/org/jboss/pnc/dto/Build.java, dto/src/main/java/org/jboss/pnc/dto/requests/GroupBuildRequest.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, integration-test/pom.xml, integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/setup/Deployments.java, integration-test/src/test/java/org/jboss/pnc/integration_new/setup/RestClientConfiguration.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java, pom.xml, rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/BuildParameters.java, rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/GroupBuildParameters.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java
=> [NCL-5216] BuildTest integration tests

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/DownloadTwoThenVerifyExtractedArtifactsContainThemTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ExcludeInternalRepoByNameTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ExcludeInternalRepoByRegexTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ImportDepVerifyPromotionToSharedImportsTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/IndyPromotionValidationTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadOneThenDownloadAndVerifyArtifactHasOriginUrlTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadTwoThenVerifyExtractedArtifactsContainThemTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildGroupRemovedAfterArtifactExtractionTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildRepoPromotionToUntestedBuildsGroupTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualDeletionOfBuildRepoTest.java, maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualPromotionOfBuildRepoTest.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositoryManagerMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositorySessionMock.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java, rest/src/test/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpointTest.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
=> [NCL-4802] Provide method to get repository manager result

integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigSetRecordsTest.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildRecordsTest.java, pom.xml, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigSetRecordRest.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildEnvironmentRest.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/ProjectRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigSetRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigSetRecordProvider.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java
=> [NCL-5106]: Add REST endpoints GET temporary-older-than-timestamp for BuildRecords and sets

processor/src/main/java/org/jboss/pnc/processor/ClientGenerator.java, rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java, rest-api/src/main/java/org/jboss/pnc/client/RemoteResourceException.java
=> [NCL-5230] Show ErrorResponse message in client exceptions

termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java, termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/DebugInContainerTest.java
=> NCL-5298 - build driver debug enabling fix.

processor/src/main/java/org/jboss/pnc/processor/ClientGenerator.java
=> [NCL-5221] ignore @PATCH endpoints in the rest-client

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/util/UserService.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildTest.java, rest-new/src/main/java/org/jboss/pnc/rest/RequestLoggingFilter.java
=> fix PR #2704

common/src/main/java/org/jboss/pnc/common/mdc/MDCUtils.java
=> Rename mdc field to processContext.

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionSession.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, common/src/main/java/org/jboss/pnc/common/util/ProcessStageUtils.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
=> Update duration logs.

dto/pom.xml, facade/pom.xml, facade/src/main/java/org/jboss/pnc/facade/executor/BuildExecutorTriggerer.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, mapper/pom.xml, notifications/pom.xml, rest-api/pom.xml, rest-new/pom.xml
=> [NCL-4511] Remove unused dependencies

dto/src/main/java/org/jboss/pnc/dto/response/Validation.java, dto/src/main/java/org/jboss/pnc/dto/response/Validations.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildEndpointTest.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/EnvironmentEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupBuildEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupConfigurationEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductVersionEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProjectEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/UserEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/PageParameters.java, rest-api/src/main/java/org/jboss/pnc/rest/configuration/Constants.java, rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConstants.java, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/provider/ConstraintViolationExceptionMapper.java
=> [NCL-5261] Add constraint for REST page size (max 200)

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
=> [NCL-5265] Throw 404 when there is no Build Push Result

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ArtifactEndpointTest.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
=> [NCL-5167] Add endpoints to get Builds related to an artifact

constants/src/main/java/org/jboss/pnc/constants/Patterns.java, constants/src/test/java/org/jboss/pnc/constants/PatternsTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
=> [NCL-4611] added special case for milestone version pattern matching

model/src/main/java/org/jboss/pnc/model/ProductMilestone.java, model/src/test/java/org/jboss/pnc/model/VersionPatternTest.java
=> [v1.8][NCL-4611] added special case for milestone version pattern matching

ui/app/common/directives/pnc-confirm-click/pncConfirmClick.js
=> [NCL-4525] Fix console error: Possibly unhandled rejection: undefined

rest-api/pom.xml
=> Generate openapi spec at build time

dto/pom.xml, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildEndpointTest.java, processor/src/main/java/org/jboss/pnc/processor/ClientGenerator.java, rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
=> Stream logs.

ui/app/common/select-modals/modalEditService.js
=> [NCL-5263] Fix console error: Cannot read property of undefined

ui/app/index.html
=> [NCL-4916] Fix issue: Duplicated path to artifacts page

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleanerAsyncInvoker.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigSetRecordEndpoint.java, rest/src/test/java/org/jboss/pnc/rest/endpoint/BuildConfigSetRecordEndpointTest.java
=> Callback set

ui/app/builds/builds.module.js, ui/app/builds/detail/details/pnc-build-detail-details-page.html, ui/app/builds/detail/details/pncBuildDetailDetailsPage.js, ui/app/builds/directives/pnc-log-streamer/pncLogStreamer.js
=> Fixes broken log-streamer after build record refactor

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, constants/src/main/java/org/jboss/pnc/enums/BuildType.java, indy-repository-manager/pom.xml, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/AbstractRepositoryManagerDriverTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/DownloadTwoThenVerifyExtractedArtifactsContainThemTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExcludeInternalRepoByNameTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExcludeInternalRepoByRegexTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ImportDepVerifyPromotionToSharedImportsTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/IndyPromotionValidationTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/UploadOneThenDownloadAndVerifyArtifactHasOriginUrlTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/UploadTwoThenVerifyExtractedArtifactsContainThemTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyBuildGroupRemovedAfterArtifactExtractionTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyBuildRepoPromotionToUntestedBuildsGroupTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyManualDeletionOfBuildRepoTest.java, indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyManualPromotionOfBuildRepoTest.java, openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositoryManagerMock.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositorySessionMock.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildMaintenanceEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildMaintananceEndpoint.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java, spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
=> [NCL-4802] Add endpoint to provide processed data from tracking report

ui/app/common/components/pnc-toolbar/pncToolbar.js, ui/app/common/pnc-client/pagination/filteringPaginator.js, ui/app/common/pnc-client/pagination/pfFilterAdaptor.js, ui/app/projects/list/pnc-projects-list-page.html, ui/app/projects/list/pncProjectsListPage.js, ui/app/projects/projects.module.js
=> [NCL-5340] Projects ordering

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildMaintenanceEndpointImpl.java
=> [NCL-4802] Instantiate the BuildMaintenanceEndpointImpl

rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildMaintenanceEndpointImpl.java
=> [NCL-4802] Activate the new endpoint

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java
=> [NCL-4802] Read build record along with BuildConfigurationAudited

process-managers/src/main/java/org/jboss/pnc/managers/BuildResultPushManager.java, process-managers/src/test/java/org/jboss/pnc/managers/BuildResultPushManagerTest.java
=> [NCL-5112] Fix build push wrongly claiming it's ing progress when it actually failed

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionSession.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java, common/src/main/java/org/jboss/pnc/common/util/ProcessStageUtils.java
=> NCL-5317 - fix build steps duration.

common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java, integration-test/src/test/java/org/jboss/pnc/integration_new/setup/RestClientConfiguration.java, rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java, rest-api/src/main/java/org/jboss/pnc/client/Configuration.java, rest-api/src/main/java/org/jboss/pnc/client/MdcToHeadersFilter.java, rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java
=> NCL-5353 - Add MDC context passing to headers.

rest-api/src/main/java/org/jboss/pnc/client/Configuration.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
=> Use lombok builder and customize it.

common/src/main/java/org/jboss/pnc/common/monitor/PullingMonitor.java
=> Run oncomplete befoce killing the task.

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildMaintenanceEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildMaintenanceEndpoint.java
=> Fix a typo

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java, bpm/src/test/java/org/jboss/pnc/bpm/test/BuildResultPushManagerTest.java, facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
=> [NCL-5112] Fix build push wrongly claiming it's ing progress when it actually failed [master]

rest/src/main/java/org/jboss/pnc/rest/endpoint/GenericSettingEndpoint.java
=> [v1.8][NCL-5297] Fix typo in endpoint

datastore/src/main/java/org/jboss/pnc/datastore/repositories/GenericSettingRepositoryImpl.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/GenericSettingSpringRepository.java, dto/src/main/java/org/jboss/pnc/dto/Banner.java, facade/src/main/java/org/jboss/pnc/facade/impl/BuildTriggererImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java, facade/src/main/java/org/jboss/pnc/facade/providers/HealthCheckProviderImpl.java, model/src/main/java/org/jboss/pnc/model/GenericSetting.java, model/src/main/resources/db-update/10002-from-1.7.x-to-1.8.0.sql, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/GenericSettingEndpointImpl.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/GenericSettingPredicates.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/GenericSettingRepository.java
=> [NCL-5297] Maintenance mode

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-5360] Fix confusing message when promotion timeout happens

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.8][NCL-5360] Fix confusing message when promotion timeout happens

rest-client/pom.xml
=> Add common as a client dependency.

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
=> NCL-5351 - Filter subquery for the same BuildConfigurationAudited.idRev

build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/AbstractDependentBuildTest.java, datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java, datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/BuildRecordSpringRepository.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordPushEndpoint.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java
Related to https://github.com/project-ncl/pnc/pull/2777
=> NCL-5276 - optimization of implicit rebuild generated queries 

dto/src/main/java/org/jboss/pnc/dto/notification/BuildChangedNotification.java, dto/src/main/java/org/jboss/pnc/dto/notification/BuildConfigurationCreation.java, dto/src/main/java/org/jboss/pnc/dto/notification/BuildPushResulNotification.java, dto/src/main/java/org/jboss/pnc/dto/notification/GroupBuildChangedNotification.java, dto/src/main/java/org/jboss/pnc/dto/notification/Notification.java, dto/src/main/java/org/jboss/pnc/dto/notification/RepositoryCreationFailure.java, dto/src/main/java/org/jboss/pnc/dto/notification/SCMRepositoryCreationSuccess.java, integration-test/src/test/java/org/jboss/pnc/integration/WebSocketsNotificationTest.java
=> [NCL-5349] Add oldStatus field to Notification DTOs

rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigSetRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/utils/EndpointAuthenticationProvider.java
=> Add validation to delete endpoints if user is not loaded, add logging

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
=> Move logging and add more checks on arrays size

ui/app/common/util/SortHelper.js, ui/app/projects/list/pncProjectsListPage.js, ui/app/projects/projects.module.js
=> Ncl 5347 Refactor and implement proper localStorage persisting methods 

ui/app/common/templates/footer.tmpl.html
=> [v1.8] It's 2020

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinatorTest.java, datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java, pnc-mock/src/main/java/org/jboss/pnc/mock/datastore/DatastoreMock.java, spi/src/main/java/org/jboss/pnc/spi/datastore/Datastore.java
=> Ncl-5276 optimization continued, backport from v1.8

causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/NpmBuild.java, causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/NpmBuiltArtifact.java, facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ArtifactRSQLMapper.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/GroupBuildRSQLMapper.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/TargetRepositoryRSQLMapper.java, integration-test/src/test/java/org/jboss/pnc/integration/ArtifactRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/client/ArtifactRestClient.java, integration-test/src/test/java/org/jboss/pnc/integration/client/ProductMilestoneRestClient.java, mapper/src/main/java/org/jboss/pnc/mapper/AbstractArtifactMapper.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildConfigurationRevisionMapper.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildPushResultMapper.java, mapper/src/main/java/org/jboss/pnc/mapper/api/GroupBuildMapper.java, mapper/src/main/java/org/jboss/pnc/mapper/api/ProductMapper.java, mapper/src/main/java/org/jboss/pnc/mapper/api/ProductMilestoneMapper.java, mapper/src/main/java/org/jboss/pnc/mapper/api/ProductReleaseMapper.java, mapper/src/main/java/org/jboss/pnc/mapper/api/TargetRepositoryMapper.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ArtifactEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/swagger/response/ArtifactSingleton.java
=> [jmichalo] fix email documentation

integration-test/src/test/java/org/jboss/pnc/integration/ArtifactRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/client/ArtifactRestClient.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/ArtifactEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/swagger/response/ArtifactSingleton.java
=> [jmichalo] fix email links

integration-test/pom.xml, integration-test/src/test/java/org/jboss/pnc/integration/BuildRecordPushTest.java, integration-test/src/test/java/org/jboss/pnc/integration/remote/RemoteBuildTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/NotificationCollector.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/ProcessProgressNotificationTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/UpdatesMessageHandler.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/WebSocketsNotificationTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/WsUpdatesClient.java, integration-test/src/test/java/org/jboss/pnc/integration_new/setup/Deployments.java, notifications/pom.xml, notifications/src/main/java/org/jboss/pnc/notification/Action.java, notifications/src/main/java/org/jboss/pnc/notification/MessageType.java, notifications/src/main/java/org/jboss/pnc/notification/ProgressUpdatesRequest.java, notifications/src/main/java/org/jboss/pnc/notification/RequestParser.java, notifications/src/main/java/org/jboss/pnc/notification/SessionBasedAttachedClient.java, notifications/src/main/java/org/jboss/pnc/notification/TypedMessage.java, notifications/src/test/java/org/jboss/pnc/notification/DefaultNotifierTest.java, notifications/src/test/java/org/jboss/pnc/notification/RequestParserTest.java, notifications/src/test/java/org/jboss/pnc/notification/SessionBasedAttachedClientTest.java, pom.xml, rest-new/pom.xml, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/notifications/NotificationsEndpoint.java, rest/pom.xml
=> [NCL-5109] Change WebSocket URL

ui/app/dashboard/widgets/pnc-grafana-widget/pnc-grafana-widget-body.html
=> [NCL-5375] Change pnc-grafana-widget-body height

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.8][NCL-5380] Ensure all repo urls contain trailing slash

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-5380] Ensure all repo urls contain trailing slash

common/src/main/java/org/jboss/pnc/common/util/StringUtils.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/Product.java, model/src/main/java/org/jboss/pnc/model/Project.java, model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql
=> [NCL-5346] Nullify some empty string before storing to DB

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/UIModuleConfig.java
=> Add kafka store url to UI config

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/UIModuleConfig.java
=> [v1.8] Add kafka store url to UI config

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/TermdBuildDriverModuleConfig.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/DefaultFileTranser.java
=> Environment liveness probe fix

datastore/src/main/java/org/jboss/pnc/datastore/repositories/CacheHandlerRepositoryImpl.java, datastore/src/main/resources/META-INF/persistence.xml, model/src/main/java/org/jboss/pnc/model/utils/HibernateMetric.java, model/src/main/java/org/jboss/pnc/model/utils/HibernateStatsUtils.java, model/src/test/resources/META-INF/persistence.xml, rest/src/main/java/org/jboss/pnc/rest/configuration/JaxRsActivator.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/CacheEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/CacheProvider.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/CacheHandlerRepository.java
=> NCL-5408 - Expose REST endpoints to provide Hibernate 1LC and 2LC statistics

model/src/main/java/org/jboss/pnc/model/ProductMilestone.java
=> [NCL-5012] Remove eager fetch in ProductMilestone

datastore/src/main/java/org/jboss/pnc/datastore/repositories/CacheHandlerRepositoryImpl.java, datastore/src/main/resources/META-INF/persistence.xml, model/src/main/java/org/jboss/pnc/model/utils/HibernateMetric.java, model/src/main/java/org/jboss/pnc/model/utils/HibernateStatsUtils.java, model/src/test/resources/META-INF/persistence.xml, rest/src/main/java/org/jboss/pnc/rest/configuration/JaxRsActivator.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/CacheEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/CacheProvider.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/CacheHandlerRepository.java
=> [1.8] NCL-5408 - Expose REST endpoints to provide Hibernate 1LC and 2LC statistics

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/BuildRecordProviderTest.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java
=> NCL-5396 - show parent in progress builds in the dependency tree.

bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationRest.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildTaskEndpoint.java
=> Add endpoints that accept single json rather than form parameters.

bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationRest.java, bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationWithCallbackRest.java, bpm/src/test/java/org/jboss/pnc/bpm/test/BuildExecutionConfigurationTest.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildTaskEndpoint.java, rest/src/test/java/org/jboss/pnc/rest/serialization/BuildExecutionConfigurationTest.java
=> Add REST model object with callback.

ui/app/artifacts/artifacts.module.js, ui/app/artifacts/list/pnc-artifacts-data-table.html, ui/app/artifacts/list/pncArtifactsDataTable.js, ui/app/builds/builds.module.js, ui/app/builds/list/pnc-builds-list-page.html, ui/app/builds/list/pncBuildsListPage.js, ui/app/common/util/SortHelper.js, ui/app/group-builds/group-builds.module.js, ui/app/group-builds/list/pnc-group-builds-list-page.html, ui/app/group-builds/list/pncGroupBuildsListPage.js, ui/app/group-configs/group-configs.module.js, ui/app/group-configs/list/pnc-group-configs-list-page.html, ui/app/group-configs/list/pncGroupConfigsListPage.js, ui/app/projects/list/pncProjectsListPage.js, ui/app/projects/projects.module.js, ui/app/scm-repositories/list/pnc-scm-repositories-list-page.html, ui/app/scm-repositories/list/pncScmRepositoriesListPage.js, ui/app/scm-repositories/scm-repositories.module.js
=> [NCL-5019] Add ordering functionality to the toolbar (except Products and Build Configs page)

dto/src/main/java/org/jboss/pnc/dto/requests/BuildConfigWithSCMRequest.java, dto/src/main/java/org/jboss/pnc/dto/response/BuildConfigCreationResponse.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, rest-api/src/test/java/org/jboss/pnc/rest/jackson/DeserializerTest.java
=> [NCL-5441] Fix DTO parameter name

datastore/src/main/resources/META-INF/persistence.xml, model/pom.xml, model/src/main/java/org/jboss/pnc/model/Artifact.java, model/src/main/java/org/jboss/pnc/model/BuildConfigSetRecord.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java, model/src/main/java/org/jboss/pnc/model/BuildEnvironment.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, model/src/main/java/org/jboss/pnc/model/BuildRecordPushResult.java, model/src/main/java/org/jboss/pnc/model/Product.java, model/src/main/java/org/jboss/pnc/model/ProductMilestone.java, model/src/main/java/org/jboss/pnc/model/ProductMilestoneRelease.java, model/src/main/java/org/jboss/pnc/model/ProductRelease.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, model/src/main/java/org/jboss/pnc/model/Project.java, model/src/main/java/org/jboss/pnc/model/RepositoryConfiguration.java, model/src/main/java/org/jboss/pnc/model/TargetRepository.java, model/src/main/java/org/jboss/pnc/model/User.java, model/src/test/java/org/jboss/pnc/model/CacheHandlerTest.java, model/src/test/resources/META-INF/persistence.xml, pom.xml
=> Ncl 5400 - Enable the second level cache

model/src/main/java/org/jboss/pnc/model/utils/HibernateStatsUtils.java
=> NCL-5400 - Handle exception when region name cannot be resolved

model/src/main/java/org/jboss/pnc/model/utils/HibernateStatsUtils.java
=> Handle exception when region name cannot be resolved

ui/app/builds/directives/pnc-build-tree/pncBuildTree.js
=> NCL-5335 Fix missing dependency ids for Build Tree

model/src/main/java/org/jboss/pnc/model/Artifact.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/ArtifactProvider.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java
Optimize queries to retrieve dependencies and builtArtifact from a BuildRecord, to improve the MavenRepository generation with PiG
=> [v1.8] NCL-5386 - Optimize queries used to generate the MavenRepository with PiG

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java
=> Fix REPO_SETTING_UP end event.

ui/app/artifacts/list/pncArtifactsDataTable.js
=> [NCL-5140] Removed unnecessary sorting columns

ui/app/builds/directives/pnc-builds-list/pnc-builds-list.html, ui/app/builds/directives/pnc-builds-list/pncBuildsList.js
=> [NCL-5439] Add "Submit Time" column on Builds page table

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java
=> Update build tasks timing capture points.

rest/src/main/java/org/jboss/pnc/rest/endpoint/GenericSettingEndpoint.java
=> [v1.8][NCL-5297] Add parameter description

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java
=> [NCL-5297] Add description to params for announcement banner

.gitignore, model/src/main/java/org/jboss/pnc/model/utils/HibernateMetric.java, model/src/main/java/org/jboss/pnc/model/utils/HibernateStatsUtils.java, model/src/test/java/org/jboss/pnc/model/CacheHandlerTest.java
=> NCL-5417 - Fix the calculation of hit ratios and do filter non supported stats

rest/src/main/java/org/jboss/pnc/rest/provider/ArtifactProvider.java
=> Fix calculation of offset

ui/app/dashboard/directives/pnc-my-build-sets-panel.html, ui/app/dashboard/directives/pnc-my-builds-panel.html, ui/app/dashboard/views/dashboard.html, ui/app/styles/app.css
=> [NCL-5463] Solve Dashboard page scrollable issue

rest-api/src/main/java/org/jboss/pnc/client/Configuration.java
=> Add default MdcMapping to the client to prevent NPE

rest-api/src/main/java/org/jboss/pnc/client/BasicAuthentication.java, rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java
=> Client compatibility RestEasy 3 & 4.

model/src/main/java/org/jboss/pnc/model/Artifact.java, model/src/test/java/org/jboss/pnc/model/ArtifactTest.java
=> [NCL-5456] Temporary builds cleaner cannot delete artifacts from DB

bpm-mock/src/main/java/org/jboss/pnc/bpm/mock/BpmMock.java, bpm/src/main/java/org/jboss/pnc/bpm/BpmManager.java, bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java, bpm/src/main/java/org/jboss/pnc/bpm/Connector.java, bpm/src/main/java/org/jboss/pnc/bpm/ConnectorSelector.java, bpm/src/main/java/org/jboss/pnc/bpm/HttpConfig.java, bpm/src/main/java/org/jboss/pnc/bpm/KieClientConnector.java, bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java, bpm/src/main/java/org/jboss/pnc/bpm/task/BpmBuildTask.java, bpm/src/test/java/org/jboss/pnc/bpm/test/BpmSchedulerSmokeTest.java, common/src/main/java/org/jboss/pnc/common/json/JsonOutputConverterMapper.java, moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/BpmModuleConfig.java, moduleconfig/src/main/resources/pnc-config.json, pnc-mock/src/main/resources/bpmModuleConfig.json, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java, rest/src/test/java/org/jboss/pnc/rest/provider/AbstractMilestoneReleaseTest.java, rest/src/test/java/org/jboss/pnc/rest/utils/mock/BpmPushMock.java
=> BPM blue-green routing based on BuildConfiguration parameters.

ui/app/common/components/pnc-service-notification/pnc-service-notification.html, ui/app/common/components/pnc-service-notification/pncServiceNotification.js, ui/app/index.html, ui/package-lock.json
=> NCL-4344 provides the UI mechanism to display a service notification

bpm-mock/src/main/java/org/jboss/pnc/bpm/mock/BpmMock.java, bpm/src/main/java/org/jboss/pnc/bpm/Connector.java, bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java, spi/src/main/java/org/jboss/pnc/spi/exception/ProcessManagerException.java
=> Thrown exception when unable to start new process.

ui/app/builds/directives/pnc-build-tree/pnc-build-tree.html
=> [NCL-5485] Remove error notice for NCL5335 on Build Tree page

processor/src/main/java/org/jboss/pnc/processor/ClientGenerator.java, rest-api/src/main/java/org/jboss/pnc/client/RemoteResourceException.java
=> Catch all communication errors in the rest-client

dto/src/main/java/org/jboss/pnc/dto/Build.java, dto/src/main/java/org/jboss/pnc/dto/BuildRef.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java, rest-api/src/main/java/org/jboss/pnc/client/DefaultRemoteCollection.java, rest-api/src/main/java/org/jboss/pnc/client/RemoteCollection.java
=> Build output checksum

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildRSQLMapper.java
=> Add BuildRecord_.buildOutputChecksum rsql mapping.

model/src/main/java/org/jboss/pnc/model/Artifact.java, model/src/test/java/org/jboss/pnc/model/ArtifactTest.java
=> [NCL-5456] Temporary builds cleaner cannot delete artifacts from DB - v1.8

ui/app/artifacts/list/pncArtifactsDataTable.js, ui/app/builds/list/pncBuildsListPage.js, ui/app/common/util/SortHelper.js, ui/app/group-builds/list/pncGroupBuildsListPage.js, ui/app/group-configs/list/pncGroupConfigsListPage.js, ui/app/projects/list/pncProjectsListPage.js, ui/app/scm-repositories/list/pncScmRepositoriesListPage.js
=> [NCL-5493] Disable current Local Storage features

bpm/src/test/java/org/jboss/pnc/bpm/test/BuildResultPushManagerTest.java
=> Fix compile error

ui/app/build-configs/build-configs.module.js, ui/app/build-configs/detail/dependencies-tab/pnc-build-config-dependencies-tab.html, ui/app/build-configs/detail/dependencies-tab/pncBuildConfigDependenciesTab.js, ui/app/build-configs/detail/details-tab/pnc-build-config-details-editor.html, ui/app/build-configs/detail/details-tab/pnc-build-config-properties.html, ui/app/build-configs/detail/details-tab/pncBuildConfigDetailsEditor.js, ui/app/common/pnc-client/resources/BuildConfigResource.js
=> NCL-4198-5

ui/app/build-configs/detail/revisions-tab/pnc-build-config-revision-link.html, ui/app/common/pnc-client/resources/BuildConfigResource.js
=> NCL-4198 Refactor BuildConfig->Revisions tab to work with PNC 2.0

auth/src/test/resources/logback.xml, bpm/src/test/resources/logback.xml, build-coordinator/src/test/resources/logback-test.xml, build-executor/src/test/resources/logback.xml, causeway-client/src/test/resources/logback.xml, common/src/test/resources/logback.xml, integration-test/src/test/resources/logback.xml, maven-repository-manager/src/test/resources/logback.xml, messaging/src/test/resources/logback.xml, model/src/test/resources/logback.xml, process-managers/src/test/resources/logback.xml, rest-model/src/test/resources/logback.xml, rest/src/test/resources/logback.xml, termd-build-driver/src/test/resources/logback.xml
=> [v1.8.x] NCL-5519 - Configure the log level of Hibernate statistics to TRACE

auth/src/test/resources/logback.xml, bpm/src/test/resources/logback.xml, build-coordinator/src/test/resources/logback-test.xml, build-executor/src/test/resources/logback.xml, causeway-client/src/test/resources/logback.xml, common/src/test/resources/logback.xml, datastore/pom.xml, datastore/src/test/resources/logback.xml, integration-test/pom.xml, integration-test/src/test/resources/logback.xml, maven-repository-manager/src/test/resources/logback.xml, messaging/pom.xml, messaging/src/test/resources/logback.xml, model/src/test/resources/logback.xml, rest-api/src/test/resources/logback.xml, rest-model/src/test/resources/logback.xml, rest/src/test/resources/logback.xml, termd-build-driver/src/test/resources/logback.xml
=> NCL-5519 - Configure the log level of Hibernate statistics to TRACE

processor/src/main/java/org/jboss/pnc/processor/ClientGenerator.java, rest-api/pom.xml, rest-api/src/main/java/org/jboss/pnc/client/BearerAuthentication.java, rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java, rest-api/src/main/java/org/jboss/pnc/client/Configuration.java, rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java
=> [NCL-5513]: Update REST client to support token refresh

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java
=> [NCL-5030] Possible to create invalid repository configurations

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
MDC works by setting a context map for each thread [1]. While this works quite
well, we have to be careful when using a threadpool, since threads get re-used.
This means that the context of a thread, set by a previous job, could be
erroneously used with a new job.
We are concerned with 3 main classes in this bug,
`DefaultBuildCoordinator`,`BpmBuildScheduler` and `DefaultBuildExecutor`.
This class handles the 'pod creation', Maven/Gradle building, and the
collection of results. It interacts with the other 2 classes indirectly via
Maitai. The MDC from Maitai -> BuildExecutor is set. `DefaultBuildExecutor`
uses a modified thread pool (`MDCThreadPoolExecutor`) that explicitly sets the
MDC for each thread processing a `Runnable`, `Callable` etc. As such, this
class properly deals with MDC in …
=> [v1.8][NCL-5520] Fix thread MDC context

ui/app/builds/detail/details/pnc-build-detail-details-page.html, ui/app/builds/directives/pnc-build-config-link/pnc-build-config-link.html, ui/app/builds/directives/pnc-build-config-link/pncBuildConfigLink.js
=> NCL-5331 Fix Navigate-back error after clicking the "build config" link in build records page

ui/app/builds/detail/details/pnc-build-detail-details-page.html, ui/app/builds/directives/pnc-build-config-history-revision/pnc-build-config-history-revision.html, ui/app/builds/directives/pnc-build-config-history-revision/pncBuildConfigHistoryRevision.js
=> NCL-5320 Add link back to specific build config revision on build details page

ui/app/builds/directives/pnc-build-tree/pnc-build-tree-link.html
=> NCL-5587 Fix bug: Link on Build Tree does not work properly

common/src/main/java/org/jboss/pnc/common/util/UrlUtils.java
=> Fix potential NPE in UrlUtils#buildUrl

rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java
=> [v1.8] NCL-3766 - Generate download link, not UI link

ui/app/group-builds/list/pnc-group-builds-list-page.html, ui/app/group-builds/list/pncGroupBuildsListPage.js
=> [NCL-5495] Unnecessary "Submit Time" column on "Group Build" page

rest-model/src/main/java/org/jboss/pnc/rest/restmodel/genericsetting/GenericSettingUpdate.java, rest/src/main/java/org/jboss/pnc/rest/genericsetting/notifications/GenericSettingNotificationSender.java, rest/src/main/java/org/jboss/pnc/rest/genericsetting/notifications/GenericSettingNotificationsEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/GenericSettingProvider.java
=> [v1.8][NCL-5528] websocket for generic settings

constants/src/main/java/org/jboss/pnc/enums/JobNotificationType.java, dto/src/main/java/org/jboss/pnc/dto/notification/BuildPushResultNotification.java, dto/src/main/java/org/jboss/pnc/dto/notification/GenericSettingNotification.java, facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildRecordPushTest.java, notifications/src/main/java/org/jboss/pnc/notification/DefaultNotifier.java
=> [NCL-5528] websocket for generic settings

build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/AbstractDependentBuildTest.java, facade/src/main/java/org/jboss/pnc/facade/BrewPusher.java, facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
If there is no completed brew push result, check the in progress list
if the given build id is there. If so return an empty result with
status ACCEPTED meaning that pusher accepted the push request.
=> [NCL-5585] Add in progress brew push into REST API result

rest/src/main/java/org/jboss/pnc/rest/provider/GenericSettingProvider.java
=> [v1.8][NCL-5528] Adapt to updated payload

dto/src/main/java/org/jboss/pnc/dto/notification/GenericSettingNotification.java
=> [NCL-5528] Adjust message payload

dto/src/main/java/org/jboss/pnc/dto/ProductRef.java
=> Fix incorrect validation of ProductRef.name

integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/ProcessProgressNotificationTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/WebSocketsNotificationTest.java, notifications/pom.xml, notifications/src/main/java/org/jboss/pnc/notification/DefaultNotifier.java, notifications/src/main/java/org/jboss/pnc/notification/RequestParser.java, notifications/src/main/java/org/jboss/pnc/notification/SessionBasedAttachedClient.java, rest-api/src/main/java/org/jboss/pnc/rest/jackson/JacksonProvider.java
=> [NCL-5413] Use REST object mapper in notifications

dto/src/main/java/org/jboss/pnc/dto/notification/BuildPushResultNotification.java, integration-test/src/test/java/org/jboss/pnc/integration_new/WebSocketClientTest.java, pom.xml, rest-client/pom.xml, rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildConfigurationClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedGroupConfigurationClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/ConnectionClosedException.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/Dispatcher.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/ListenerUnsubscriber.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/WebSocketClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/predicates/BuildChangedNotificationPredicates.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/predicates/BuildPushResultNotificationPredicates.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/predicates/GroupBuildChangedNotificationPredicates.java
=> [NCL-5483] Add websocket support to rest-client

pom.xml
=> Use build agent 0.6.1.

rest/src/main/java/org/jboss/pnc/rest/trigger/BuildTriggerer.java
=> [v1.8][NCLSUP-34] Put reason for maintenance mode in notification

facade/src/main/java/org/jboss/pnc/facade/impl/BuildTriggererImpl.java
=> [NCLSUP-34] Put reason for maintenance mode in notification

facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductVersionProviderTest.java
=> [NCL-5622] Throw nice error if PV already exists

ui/bower.json
=> NCL-5625 Improvement to patternfly declaration

datastore/pom.xml, datastore/src/test/java/org/jboss/pnc/datastore/DeploymentFactory.java, dto/pom.xml, ear-package/pom.xml, facade/pom.xml, integration-test/pom.xml, integration-test/src/test/java/org/jboss/pnc/integration/deployments/Deployments.java, integration-test/src/test/java/org/jboss/pnc/integration_new/setup/Deployments.java, messaging/pom.xml, pom.xml, rest-api/pom.xml, rest-model/pom.xml, rest-new/pom.xml, rest/pom.xml, test-common/pom.xml, test-common/src/main/java/org/jboss/pnc/test/arquillian/ShrinkwrapDeployerUtils.java, test-common/src/test/java/org/jboss/pnc/test/arquillian/ManifestTest.java, web/pom.xml
=> Ncl 5618 maven release plugin

rest-client/pom.xml, rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildConfigurationClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedGroupConfigurationClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/WebSocketClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/websocket/predicates/GroupBuildChangedNotificationPredicates.java
=> [NCL-5483] fixed bugs in WebSocketClient for rest-client

rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildConfigurationClient.java, rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedGroupConfigurationClient.java
=> [NCL-5406] fix vertx not clearing threads on external timeout

dto/src/main/java/org/jboss/pnc/dto/requests/validation/VersionValidationRequest.java, dto/src/main/java/org/jboss/pnc/dto/response/ValidationResponse.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
=> [NCL-4624] [RR] product milestone version validation endpoint

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-5625] Use by-path promotion for temporary builds

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
=> [v1.8] [NCL-5625] Use by-path promotion for temporary builds

datastore/src/main/resources/META-INF/persistence.xml, model/src/test/resources/META-INF/persistence.xml
=> [v1.8] NCL-5480 - Configure Hibernate to do batch inserts and updates

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java, indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java
=> [NCL-5626] Add deletion of artifacts from consolidated temporary builds

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java, maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
=> [v1.8] [NCL-5626] Add deletion of artifacts from consolidated temporary builds repo

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationRepositoryImpl.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationAudited.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationAuditedRest.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
=> [v1.8] NCL-5527 - Update lastModificationTime only if audited fields are updated

termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java, termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
=> Run stop liveness probe before closing the build agent client.

ui/app/build-records/directives/pnc-build-records-data-table/pncBuildRecordsDataTable.js
=> NCL-5632 Fix artifact null paginator [v1.8 only]

ui/app/common/components/pnc-admin-panel/pncAdminPanel.js
=> [NCL-5629] master - Switch for maintenance mode doesn't work properly

ui/app/common/components/pnc-admin-panel/pncAdminPanel.js
=> [NCL-5629] 1.8 Switch for maintenance mode doesn't work properly

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationRepositoryImpl.java, dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRevision.java, dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRevisionRef.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigRevisionHelper.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildConfigurationEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildTest.java, messaging-spi/src/test/java/org/jboss/pnc/messaging/spi/BuildStatusChangedTest.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationAudited.java, model/src/main/java/org/jboss/pnc/model/User.java, pnc-mock/src/main/java/org/jboss/pnc/mock/dto/BuildConfigurationRevisionMock.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationAuditedRest.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java, rest/src/test/java/org/jboss/pnc/rest/provider/BuildConfigurationProviderTest.java
=> NCL-5527 - Adding / Updating a description on build configuration causes a rebuild

ui/app/build-configs/detail/details-tab/pnc-build-config-properties.html, ui/app/build-configs/detail/details-tab/pncBuildConfigProperties.js, ui/app/build-configs/detail/revisions-tab/pnc-revisions-details.html, ui/app/build-configs/detail/revisions-tab/pncRevisionsDetails.js
=> NCL-5527 - Hide the description field from the revisions tab

datastore/src/main/resources/META-INF/persistence.xml, model/pom.xml, model/src/main/java/org/jboss/pnc/model/Artifact.java, model/src/main/java/org/jboss/pnc/model/BuildConfigSetRecord.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java, model/src/main/java/org/jboss/pnc/model/BuildEnvironment.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, model/src/main/java/org/jboss/pnc/model/BuildRecordPushResult.java, model/src/main/java/org/jboss/pnc/model/GenericSetting.java, model/src/main/java/org/jboss/pnc/model/License.java, model/src/main/java/org/jboss/pnc/model/Product.java, model/src/main/java/org/jboss/pnc/model/ProductMilestone.java, model/src/main/java/org/jboss/pnc/model/ProductMilestoneRelease.java, model/src/main/java/org/jboss/pnc/model/ProductRelease.java, model/src/main/java/org/jboss/pnc/model/ProductVersion.java, model/src/main/java/org/jboss/pnc/model/Project.java, model/src/main/java/org/jboss/pnc/model/RepositoryConfiguration.java, model/src/main/java/org/jboss/pnc/model/TargetRepository.java, model/src/main/java/org/jboss/pnc/model/User.java, model/src/main/java/org/jboss/pnc/model/utils/HibernateStatsUtils.java, model/src/test/java/org/jboss/pnc/model/CacheHandlerTest.java, model/src/test/resources/META-INF/persistence.xml, pom.xml, rest/src/main/java/org/jboss/pnc/rest/provider/CacheProvider.java
=> [v1.8] NCL-5480 Enable and tune the Infinispan 2LC in Orchestrator

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationAuditedRepositoryImpl.java, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildConfigurationAuditedRepositoryMock.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildConfigurationAuditedRepository.java
=> [v1.8] NCL-5400 - Refactoring: move usage of AuditReaderFactory in BuildConfigurationAuditedRepository

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationAuditedRepositoryImpl.java, datastore/src/main/resources/META-INF/persistence.xml, facade/src/main/java/org/jboss/pnc/facade/providers/CacheProviderImpl.java, model/src/test/resources/META-INF/persistence.xml, pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildConfigurationAuditedRepositoryMock.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java, spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildConfigurationAuditedRepository.java
=> Move usage of AuditReaderFactory to BuildConfigurationAuditedRepository

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationRepositoryImpl.java, datastore/src/test/java/org/jboss/pnc/datastore/DatastoreTest.java, dto/src/main/java/org/jboss/pnc/dto/BuildConfiguration.java, dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRevision.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/BuildConfigProviderTest.java, integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/UserRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildConfigurationEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/SCMRepositoryEndpointTest.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildConfigurationMapper.java, mapper/src/main/java/org/jboss/pnc/mapper/api/BuildConfigurationRevisionMapper.java, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/main/java/org/jboss/pnc/model/BuildConfigurationAudited.java, model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationAuditedRest.java, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationRest.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java, ui/app/build-configs/detail/details-tab/pnc-build-config-properties.html
@janinko @alexcreasy Hi guys, would you mind taking a look? Thanks!
=> NCL-5497 - Store User in BuildConfiguration and BuildConfigurationAudited

ui/app/build-configs/detail/details-tab/pnc-build-config-properties.html
=> NCL-5497 - UI fix : use the correct syntax

bpm/src/main/java/org/jboss/pnc/bpm/causeway/ProductMilestoneReleaseManager.java, datastore/src/test/java/org/jboss/pnc/datastore/repositories/ProductMilestoneReleaseRepositoryImplTest.java, demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java, dto/src/main/java/org/jboss/pnc/dto/ProductMilestoneRelease.java, dto/src/main/java/org/jboss/pnc/dto/ProductMilestoneReleaseRef.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneReleaseProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneReleaseProvider.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductMilestoneReleaseRSQLMapper.java, facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneFactory.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ProductMilestoneEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ProductVersionEndpointTest.java, mapper/src/main/java/org/jboss/pnc/mapper/api/ProductMilestoneReleaseMapper.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java, rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/ProductMilestoneReleaseParameters.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ProductMilestoneReleasePredicates.java
=> Milestone release endpoint.

ui/app/build-configs/detail/details-tab/pncBuildConfigDetailsEditor.js, ui/app/build-configs/directives/pnc-select-build-parameters/pncSelectBuildParameters.js, ui/app/common/pnc-client/resources/BuildConfigResource.js, ui/app/common/pnc-client/resources/helpers/patchHelper.js
=> [NCL-5602] Fix editing build configuration

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java, dto/src/main/java/org/jboss/pnc/dto/Product.java, dto/src/main/java/org/jboss/pnc/dto/ProductRef.java, facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductRSQLMapper.java, facade/src/test/java/org/jboss/pnc/facade/providers/ProductProviderTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ProductEndpointTest.java, model/src/main/java/org/jboss/pnc/model/Product.java, model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql, rest-model/src/main/java/org/jboss/pnc/rest/restmodel/ProductRest.java
=> [NCL-5638]: Remove Product.productCode and Product.pgmSystemName

ui/app/products/components/pnc-products-data-table/pnc-products-list.html, ui/app/products/components/pnc-products-data-table/pncProductsList.js, ui/app/products/create/pnc-create-product-form.html, ui/app/products/detail/pnc-product-detail-page.html
=> [NCL-5639] Update UI to reflect dropped product fields

rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java
=> fix WS rest-client reconnection

datastore/src/main/resources/META-INF/persistence.xml, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
=> [v1.8] NCL-5686 - Remove Hibernate batch size configuration

datastore/src/main/resources/META-INF/persistence.xml
=> Disable cache for deeper debugging

datastore/src/main/resources/META-INF/persistence.xml
=> Re-enable Hibernate batch size configuration

ui/app/build-configs/directives/pnc-select-build-parameters/pncSelectBuildParameters.js, ui/app/common/components/pnc-environment-combobox/pncEnvironmentCombobox.js, ui/app/common/components/pnc-product-version-combobox/pncProductVersionCombobox.js, ui/app/common/pnc-client/resources/BuildConfigResource.js, ui/app/common/pnc-client/resources/EnvironmentResource.js
=> [NCL-5628]Update Rest for supported parameters in build configuration

indy-repository-manager/pom.xml, pom.xml, ui/pom.xml
- hibernate-search
- undertow
- swagger2
- maven-enforcer-plugin
- gmavenplus-plugin
=> Bump dependency versions to latest

dto/pom.xml, pom.xml, rest-api/pom.xml, ui/pom.xml
- arquillian-bom
- arquillian-jacoco
- buildagent
- byte-buddy
- commons-codec
- commons-io
- dbunit
- directroy-maven-plugin
- docker-maven-plugin
- enforce-managed-deps-rule
- fluent-hc
- frontend-maven-plugin
- git-commit-id-plugin
- groovy-all
- Guava
- jackson-core
- jakarata.xml.bind-api
- javapoet
- javax.el
- json
- junit
- lombok
- mapstruct
- maven-jar-plugin
- mockito
- nexus-staging-maven-plugin
- properties-maven-plugin
- rest-assured
- resteasy (to align with EAP 7.2.3)
- shrinkwrap-descriptors
- slf4j-api
- slf4j-log4j12
- sonar-maven-plugin
- swagger-maven-plugin
- weld-core-impl
- weld-se
- wildfly-arquillian-container-managed
- wiremock-jre8
Removed:
- jclouds
=> Update dependencies in pom.xml

auth/src/main/java/org/jboss/pnc/auth/JAASLoggedInUser.java, facade/src/main/java/org/jboss/pnc/facade/providers/UserProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/UserProvider.java, facade/src/main/java/org/jboss/pnc/facade/util/UserService.java, facade/src/test/java/org/jboss/pnc/facade/providers/UserProviderImplTest.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/UserEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java
If the logged-in user doesn't exist yet in DB, create it in the
UserService.
Use UserService in facade/REST insted of AuthenticationProvider.
=> Create user in UserService

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, model/src/main/java/org/jboss/pnc/model/BuildRecord.java, model/src/main/java/org/jboss/pnc/model/BuildRecordAttribute.java, spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
Guide: https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/
=> [NCLSUP-48] Set a bidirectional for BuildRecord and BuildRecordAttribute to fix jpa relationships

model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql
=> SQL migration script.

bpm/src/main/java/org/jboss/pnc/bpm/BpmManager.java, bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java
=> Rhpam support

datastore/src/main/resources/META-INF/persistence.xml, integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration/SecondLevelCacheStoreTest.java, integration-test/src/test/resources/buildConfiguration_with_dependencies_create_template.json, integration-test/src/test/resources/test-cache-ds.xml, integration-test/src/test/resources/test-ds.xml, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, model/src/test/java/org/jboss/pnc/model/SecondLevelCacheDebugTest.java, model/src/test/resources/cache-model-test-data.xml, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
=> [v1.8] NCL-5686 - Fix for the lazy initialization which causes the duplicated entry insertion

integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationSetRestTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/GroupConfigurationEndpointTest.java
=> [NCL-5692] Port GroupConfiguration integration tests

bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildQueue.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/MDCAwareElement.java, build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionSession.java, common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildEndpoint.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildTaskEndpoint.java, spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildCoordinator.java
=> Improve MDC handling in Build Orchestrator.

rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
=> Register request logging filter in new REST API.

ui/app/products/create/pncCreateProductForm.js
=> [NCL-5675]Fix redirect to Product detail page after create a new product

dto/src/main/java/org/jboss/pnc/dto/notification/BuildChangedNotification.java
=> [NCL-5507] fix ENQUEUED status being IN_PROGRESS instead of PENDING

moduleconfig/src/main/resources/pnc-config.json, ui/app/build-configs/detail/details-tab/pnc-build-config-details-editor.html, ui/app/build-configs/detail/details-tab/pncBuildConfigDetailsEditor.js, ui/app/build-configs/directives/pnc-create-build-config-general-form/pnc-create-build-config-general-form.html, ui/app/build-configs/directives/pnc-create-build-config-general-form/pncCreateBuildConfigGeneralForm.js, ui/app/build-configs/directives/pnc-create-build-config-wizard/pnc-create-build-config-wizard.html, ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js, ui/app/build-configs/directives/pnc-select-build-parameters/pnc-display-build-parameters.html, ui/app/build-configs/directives/pnc-select-build-parameters/pnc-select-build-parameters.html, ui/app/build-configs/directives/pnc-select-build-parameters/pncDisplayBuildParameters.js, ui/app/build-configs/directives/pnc-select-build-parameters/pncSelectBuildParameters.js, ui/app/styles/generics.css
=> [NCL-5634] Propose new ALIGNMENT_PARAMETERS after build type edit

ui/pom.xml
=> Bump frontend-maven-plugin from 1.9.1 to 1.10.0

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildConfigurationEndpointTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/SecondLevelCacheStoreTest.java, integration-test/src/test/resources/test-cache-ds.xml, model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java, rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
=> [NCL-5686] - Port fixes for lazy initialization in BuildConfiguration; add tests; fix on BuildConfiguration builder

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
=> Fix initialization of same collections in BuildConfiguration

pom.xml
=> [NCL-5725] [v1.8.1] Add staging nexus repository

ui/app/common/pnc-client/message-bus/message-bus.module.js, ui/app/common/pnc-client/message-bus/messageBus.js, ui/app/pnc.module.js
=> [NCL-5655]Fix Live logs not working on stable-next

ui/app/common/pnc-client/message-bus/message-bus.module.js, ui/app/common/pnc-client/message-bus/messageBus.js, ui/app/pnc.module.js
=> [NCL-5655]Fix Live logs ver2

pom.xml
=> Bump assertj-core from 3.15.0 to 3.16.0

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
=> Check for null when getting milestone builds

pom.xml
=> Use latest Build Agent.

ear-package/pom.xml
=> Add io.undertow.websocket EAP module dependency.

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BpmEndpointImpl.java, rest/src/main/java/org/jboss/pnc/rest/endpoint/BpmEndpoint.java
=> Handle deprecated PROCESS_PROGRESS_UPDATE notifications from BPM

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java
=> Make BuildTaskEndpoint CDI bean.

dto/src/main/java/org/jboss/pnc/dto/Product.java, dto/src/main/java/org/jboss/pnc/dto/ProductRef.java, dto/src/main/java/org/jboss/pnc/dto/ProductRelease.java, dto/src/main/java/org/jboss/pnc/dto/ProductReleaseRef.java, dto/src/main/java/org/jboss/pnc/dto/Project.java, dto/src/main/java/org/jboss/pnc/dto/ProjectRef.java, model/src/main/java/org/jboss/pnc/model/Product.java, model/src/main/java/org/jboss/pnc/model/ProductRelease.java, model/src/main/java/org/jboss/pnc/model/Project.java, model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql
=> [NCL-5677] Model changes to improve Products and Projects metadata

ui/app/product-releases/create-update/pnc-product-release-create-update-page.html, ui/app/products/create/pnc-create-product-form.html, ui/app/products/detail/pnc-product-detail-page.html, ui/app/projects/create/pnc-project-create-page.html, ui/app/projects/detail/pnc-project-detail-page.html
=> [NCL-5679] - Show the additional metadata of Products and Projects in the UI

pom.xml
=> Bump assertj-core from 3.16.0 to 3.16.1

spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/TargetRepositoryPredicates.java
=> Java 1.8 compliance

auth/src/main/java/org/jboss/pnc/auth/KeycloakLoggedInUser.java
=> Make Authentication exception message more readable

constants/src/main/java/org/jboss/pnc/enums/ValidationErrorType.java, dto/src/main/java/org/jboss/pnc/dto/response/ValidationResponse.java, facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java, facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ProductMilestoneEndpointTest.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java, rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
=> [NCL-5754] add duplication validation to productMilestone validation endpoint

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
=> [NCL-5625] Use hosted repo as promotion target for all builds

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java, build-coordinator/src/test/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinatorTest.java, integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/BuildTest.java, spi/src/main/java/org/jboss/pnc/spi/BuildSetStatus.java
=> [NCL-5041] Reject Group build with NO_REBUILD_REQUIRED when appropriate

ui/app/group-builds/detail/pncGroupBuildDetailPage.js
=> [NCL-5727] Fix Detail page of Group Build record doesn't work properly

bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationRest.java, bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationWithCallbackRest.java, bpm/src/test/java/org/jboss/pnc/bpm/test/DeserializeTest.java
=> Single json Build execution configuration serailization fix.

pom.xml
=> Bump json from 20190722 to 20200518

model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql
=> [NCL-5511] Make user email nullable

pom.xml
=> [NCL-5663] set keycloak version for EAP 7.3

ui/app/builds/detail/details/pnc-build-detail-details-page.html
=> [NCL-5770] - BR detail shows "todo NCL-5271" instead of Parameters

ui/app/builds/builds.module.js, ui/app/builds/detail/details/pnc-build-detail-details-page.html, ui/app/common/pnc-client/resources/BuildResource.js
=> [NCL-5770-1] - Fetch the revision of a build for the display inside build details

pom.xml
=> Add tagSuffix to enable automatic RC releases

pom.xml
=> [v1.8] Add tagSuffix to enable automatic RC releases

ui/app/builds/builds.module.js, ui/app/builds/detail/details/pnc-build-detail-details-page.html, ui/app/builds/detail/details/pncBuildDetailDetailsPage.js, ui/app/builds/detail/pncBuildDetailPage.js
=> [NCL-5770-2] Add binding and renaming

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java, rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
=> [NCL-5779] Restrict deletion of temporary builds to system-users

facade/src/main/java/org/jboss/pnc/facade/rsql/EntityRSQLNodeTraveller.java, facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java, facade/src/main/java/org/jboss/pnc/facade/rsql/StreamRSQLNodeTraveller.java, integration-test/src/test/java/org/jboss/pnc/integration_new/RSQLTest.java
=> [NCL-5711] Create NOT LIKE oprateor in RSQL parser
