- .gitignore
- integration-test/pom.xml
- maven-repository-manager/pom.xml
- pom.xml
- Relying on the transitive version of httpclient and httpcore
can cause unpredictable build behaviour.
- Minor additions to .gitignore
- Manage version of JUnit
> Manage version of httpcomponents

- demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
- integration-test/src/test/java/org/jboss/pnc/integration/RestTest.java
- jenkins-build-driver/src/main/java/org/jboss/pnc/jenkinsbuilddriver/BuildJob.java
- jenkins-build-driver/src/test/java/org/jboss/pnc/jenkinsbuilddriver/test/JenkinsDriverRemoteTest.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildCoordinator.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/DatastoreAdapter.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/buildCoordinator/ProjectBuilder.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/configurationBuilders/TestProjectConfigurationBuilder.java
- pnc-model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
- pnc-model/src/main/java/org/jboss/pnc/model/builder/BuildConfigurationBuilder.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationRest.java
Change the build config field "identifier" to "name" to avoid confusion with the "id" field.
Add description field for better usability.
> [NCL-404] Update build configuration name and description fields

- docker-environment-driver/pom.xml
- jenkins-build-driver/pom.xml
- pnc-core/pom.xml
- pom.xml
Update Guava library to version 17.0, because it is needed by JClouds. But for the tests there is still Guava version 13.0.1, because of Weld dependency. Weld cannot run with higher version of Guava than 14.
> Integrate JClouds library

- pnc-model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
For example, when deleting a build configuration, the associated product version
should not also be deleted.
> [NCL-550] Don't delete product version when deleting a build config

- pnc-model/src/main/java/org/jboss/pnc/model/Artifact.java
- pnc-model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
- pnc-model/src/main/java/org/jboss/pnc/model/BuildRecord.java
- pnc-model/src/main/java/org/jboss/pnc/model/BuildRecordSet.java
- pnc-model/src/main/java/org/jboss/pnc/model/Environment.java
- pnc-model/src/main/java/org/jboss/pnc/model/License.java
- pnc-model/src/main/java/org/jboss/pnc/model/Product.java
- pnc-model/src/main/java/org/jboss/pnc/model/ProductVersionProject.java
- pnc-model/src/main/java/org/jboss/pnc/model/Project.java
- pnc-model/src/main/java/org/jboss/pnc/model/SystemImage.java
- pnc-model/src/main/java/org/jboss/pnc/model/User.java
Each entity should have it's own sequence generator for the PK ID field
> [NCL-543] Use a unique sequence generator for each entity

- pnc-model/src/main/java/org/jboss/pnc/model/ProductVersion.java
This was missed in the previous commit for NCL-543
> [NCL-543] Use separate sequence gen for product version

- docker-environment-driver/src/test/java/org/jboss/pnc/environment/docker/DockerEnvironmentDriverRemoteTest.java
- jenkins-build-driver/src/test/java/org/jboss/pnc/jenkinsbuilddriver/test/JenkinsDriverRemoteTest.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenContentIdentifierManager.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRunningPromotion.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractRepositoryManagerDriverTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver01Test.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver02Test.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver03Test.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver04Test.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildCoordinator.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildTask.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildTasksTree.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/buildCoordinator/ReadDependenciesTest.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/mock/MockContentIdentifierManager.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/mock/RepositoryManagerMock.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/mock/RepositorySessionMock.java
- pnc-model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
- pnc-model/src/main/java/org/jboss/pnc/model/BuildRecord.java
- pnc-model/src/main/java/org/jboss/pnc/model/BuildRecordSet.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/BuildExecution.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/content/ContentIdentifierManager.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
(eg. repo manager)
Also implemented centrally-managed content IDs for product and build-config-set levels, and promotion of build record sets to arbitrary (pre-existing) groups.
> Implementing centrally-managed content IDs for use in external services

- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver05Test.java
shared-releases, shared-imports, and the public group are all injected directly into the resolution group used for the particular build (in the repository setup), rather than relying on the product group to have the right configuration. 
Adding a test to verify the structure is correct.
> Make build group the insertion point for shared/public artifacts

- integration-test/src/test/java/org/jboss/pnc/integration/BuildConfigurationRestTest.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java
If the client sends the id in the POST request for a new config we
should return an HTTP 400 (bad request), because we require that
the server generates the correct next id in the sequence.
> [NCL-477] Return HTTP 400 when an id is sent for a new build config

- docker-environment-driver/src/test/java/org/jboss/pnc/environment/docker/DockerEnvironmentDriverRemoteTest.java
- jenkins-build-driver/src/test/java/org/jboss/pnc/jenkinsbuilddriver/test/JenkinsDriverRemoteTest.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver04Test.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver05Test.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver06Test.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildCoordinator.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildTask.java
- pnc-core/src/main/java/org/jboss/pnc/core/events/DefaultBuildStatusChangedEvent.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/mock/RepositoryManagerMock.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/mock/RepositorySessionMock.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/events/BuildStatusChangedEvent.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
Implementing promotion of build repository to the build-set group (if it exists) after each build in a chain completes. If the build isn't in a chain, build-set ID won't be set, and no promotion will take place.
> Implementing promotion of builds within a chain to chain-level group

- demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
- pnc-ui/app/app.js
- pnc-ui/app/common/remote/rest-client.js
- pnc-ui/app/common/templates/uiBreadcrumbs.tpl.html
- pnc-ui/app/configuration-set/_configuration-set.js
- pnc-ui/app/configuration-set/configuration-set-controller.js
- pnc-ui/app/configuration-set/views/configuration-set.detail.html
- pnc-ui/app/configuration-set/views/configuration-set.list.html
- pnc-ui/app/configuration/_configuration.js
- pnc-ui/app/configuration/views/configuration.detail-main.html
- pnc-ui/app/configuration/views/configuration.list.html
- pnc-ui/app/dashboard/_dashboard.js
- pnc-ui/app/index.html
- pnc-ui/app/product/_product.js
- pnc-ui/app/product/product-controllers.js
- pnc-ui/app/product/views/product.detail.html
- pnc-ui/app/product/views/product.list.html
- pnc-ui/app/product/views/product.version.html
- pnc-ui/app/project/_project.js
- pnc-ui/app/project/project-controllers.js
- pnc-ui/app/project/views/project.detail.html
- pnc-ui/app/project/views/project.list.html
- pnc-ui/app/styles/app.css
- pnc-ui/bower.json
(Based on @alexcreasy branch NCL-561), with additional:
* Added abbreviation for Product PNC
* Initial implementation of Breadbrumbs (to be completed, maybe different angular solution needed)
* Added filtering on tables
* Added navigation to BuildConfigurations from Project list
* Added navigation to BuildConfigurationSet via Product->Product Version and via BuildConfigurationSet List
> Initial implementation of NCL-561

- docker-environment-driver/src/test/java/org/jboss/pnc/environment/docker/DockerEnvironmentDriverRemoteTest.java
- jenkins-build-driver/src/test/java/org/jboss/pnc/jenkinsbuilddriver/test/JenkinsDriverRemoteTest.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractRepositoryManagerDriverTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver05Test.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver06Test.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/fixture/TestBuildExecution.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildCoordinator.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildSetTask.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildTask.java
- pnc-core/src/main/java/org/jboss/pnc/core/builder/BuildTasksTree.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/buildCoordinator/ReadDependenciesTest.java
- pnc-core/src/test/java/org/jboss/pnc/core/test/mock/RepositorySessionMock.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/BuildExecution.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/BuildExecutionType.java
- pnc-spi/src/main/java/org/jboss/pnc/spi/repositorymanager/model/RepositorySession.java
...not based on  presence or absence of buildSetId.
Also, moved BuildTaskType enum in pnc-core to BuildExecutionType in pnc-spi, to break the dep cycle between pnc-core and maven-repository-manager modules.
> Promote to group for build-set based on BuildExecutionType enum

- pnc-rest/src/main/java/org/jboss/pnc/rest/endpoint/UserEndpoint.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationSetProvider.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordSetProvider.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/EnvironmentProvider.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/LicenseProvider.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/ProductProvider.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/ProductVersionProvider.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/ProjectProvider.java
- pnc-rest/src/main/java/org/jboss/pnc/rest/provider/UserProvider.java
The id in the entity can be non-null as long as it matches the id provided
in the URL.
Also add update operation for User entity.
> [NCL-666] Allow non-null ID for updates

- pom.xml
This makes the CLI output easier to read, and organizes test output by test.
> Redirect surefire and failsafe test output to a file by default.

- build-coordinator/pom.xml
- datastore/pom.xml
- demo-data/pom.xml
- docker-environment-driver/pom.xml
- ear-package/pom.xml
- integration-test/pom.xml
- jenkins-build-driver/pom.xml
- maven-repository-manager/pom.xml
- pom.xml
- rest/pom.xml
- spi/pom.xml
- web/pom.xml
As a result of the refactor, the artifactIds in various modules needed further modification.
Basic review of changes:
pnc-something references changed to something in artifactId elements
pnc-core changed to build-coordinator
This allows a clean build with a clean maven repo :)
> modify artifactIds to reflect new module refactor

- README.md
- datastore/pom.xml
- datastore/src/main/resources/META-INF/persistence.xml
- ear-package/pom.xml
- integration-test/src/test/resources/test-ds.xml
A few more changes related to the maven module refactor. The important one is the change in the persistence.xml, which was failing to find the @Entity annotated classes due to an outdated model.jar reference.
> Persistence updates

- rest/src/main/java/org/jboss/pnc/rest/endpoint/EnvironmentEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationRest.java
- rest/src/main/java/org/jboss/pnc/rest/restmodel/EnvironmentRest.java
This change allows correct resolution of the BuildStatus type:
before change: 
http://pastebin.com/ywPzeFp6
after change:
http://pastebin.com/eBTyMfWE
Note that "$ref": BuildStatus becomes "type": "string" 
pnc-rest/rest/api-docs/build-configurations/
which I believe is desired here.
> Add @ApiModelProperty to the BuildStatus property in BuildConfigurationRest

- rest/src/main/java/org/jboss/pnc/rest/endpoint/EnvironmentEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/restmodel/EnvironmentRest.java
These changes correct errors and inconsistencies within api-docs/environments
1) Correctly define the values within buildType and operationalSystem
2) Define the model used as Environment instead of EnvironmentRest, consistent with the other Endpoints
3) Correct small misnomers in the delete method
> Modifications to the EnvironmentEndpoint and EnvironmentRest classes

- ui/app/configuration-set/configuration-set-controllers.js
- ui/app/configuration-set/views/configuration-set.add.configuration.html
Filter Build Configurations based on product version when trying to add a Build Configuration to a Set.
Provide a checkbox to disable filter.
> NCL-870 Filter build configurations based on product version

- ui/app/common/directives/header.js
- ui/app/common/directives/views/build-status-icon-d.html
- ui/app/record/views/record.list.html
- Fixed bug in header.js where directives module was redefined rather than retrieved, causing other directive definitions to be lost
- Updated tooltips for status icons
- Updated record page to use build-status-icon directive
> Various minor fixes and updates to build status display

- model/src/main/java/org/jboss/pnc/model/BuildRecord.java
- rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordRest.java
This can store an id which maps to an associated record in an external system
such as Koji/Brew
> [NCL-908] Add externalArchiveId to build record

- build-coordinator/src/main/java/org/jboss/pnc/core/builder/BuildCoordinator.java
This will be helpful when running local builds, as the fact that there is no way to shutdown the executor causes the Java process to hang.
> Add method to shutdown ExecutorService.

- rest/src/main/java/org/jboss/pnc/rest/trigger/BuildTriggerer.java
I find /build-configurations/{id}/build callbackUrl does not work. After debugging into it, I find the culprit is in triggerBuilds which returns the configuration Id instead of taskId.
> Fix triggerBuilds to return correct taskId

- build-coordinator/src/main/java/org/jboss/pnc/core/builder/BuildCoordinator.java
Improvement from ahmedlawi92, just rebasing for merge since it's been in the queue for a while.
> BuildCoordinator.shutdown() should also shutdown the dbexecutor

- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigSetRecordEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationSetEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordSetEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/EnvironmentEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/LicenseEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductMilestoneEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductReleaseEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductVersionEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/ProjectEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/RunningBuildRecordEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/UserEndpoint.java
When viewing the Swagger documentation, it can be useful to view the expected response JSON that we will receive from PNC REST endpoints.
This PR attempts to achieve this by defining the response class in the Swagger annotations.
> Add response class to Swagger documentation

- ui/app/configuration/views/configuration.list.html
When a user adds several build configurations with the same project, the
project name gets duplicated several times when viewing the list of
build configurations.
http://localhost:8080/pnc-web/#/configuration
This happens because the frontend will loop through the build
configurations, grab the project information for the project id
associated with each build configuration, and add the project
information to a list.
If two build configurations have the same project id, there will be
duplicates of the project info in that list. The duplicates will show up
in the UI.
This commit attempts to fix the duplication by simply adding a 'limitTo'
to the `ng-repeat` command so that the duplicates do not show up.
However, a better fix would be to use a set to store those project info
so that we are …
> The Build Configurations list show duplicate project

- ui/app/configuration/views/configuration.create.html
- ui/app/milestone/views/milestone.create-update.html
- ui/app/product/views/product.version.create.html
- ui/app/release/views/release.create-update.html
1. For the Configuration creation view:
`ui/app/configuration/views/configuration.create.html`
In `model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java`,
the fields marked with `@NotNull` are marked as required in the
web-ui (name, environment, and project)
2. For the Milestone creation view:
`ui/app/milestone/views/milestone.create-update.html`
In `model/src/main/java/org/jboss/pnc/model/ProductMilestone.java`,
the regex validation for the version is reflected in the web-ui too.
As such, the error message has been updated.
`ng-pattern` is also changed to `pattern` since this seems to
activate the regex UI validation.
3. For the Release creation view:
`ui/app/release/views/release.create-update.html`
Same explanation as 2. Model found in: …
> Add UI Validation based on the models

- ui/app/project/views/project.detail.html
Right now we are showing the project id in the projects view in the list of build configurations.
Since we're already in the projects view, I believe it's redundant to have a column in the build configurations section of the projects page.
Also note: I think I'm going to start a lot of mini PRs for the minor UI changes I'd like to see, instead of a big one. Reason is I'm not sure if the UI change I want to make will get accepted or not.
> No need to show projects column on the projects view

- ui/app/configuration-set/configuration-set-controllers.js
- ui/app/configuration/views/configuration.detail-main.html
- ui/app/milestone/_milestone.js
- ui/app/milestone/milestone-controllers.js
- ui/app/product/_product.js
- ui/app/product/product-controllers.js
- ui/app/product/views/product.detail.html
- ui/app/product/views/product.version.html
- ui/app/record/_record.js
- ui/app/release/_release.js
- ui/app/release/release-controllers.js
The breadcrumb navigation for the product page is broken and doesn't
properly show the nested view hierarchy of the views.
This commit attempts to fix this issue for both the products and the
records page.
From:
To:
From:
To:
From:
To:
From:
To:
The changes require a renaming of some of the states so that the angular-ui-router can figure out the parent of each state.
I also moved some `templateUrl`, router definitions inside `views: { 'content@`: {}}` so that Angular could properly substitute the views, now that it knows about the parent of each state. (I think that's what's happening?)
> Fix breadcrumbs navigation for product and record

- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- rest/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordRest.java
* Don't delete the tracking record for a build in AProx, so it can be used later in the workflow by other services.
* Propagate buildContentId from BuildRecord/BuildTask over REST via BuildRecordRest so workflow services can lookup the build id to access content on AProx / other repo managers.
> don't delete tracking on aprox, and propagate buildContentId via REST

- ui/app/common/restclient/services/BuildConfigurationSetDAO.js
- ui/app/configuration-set/configuration-set-controllers.js
- ui/app/configuration-set/views/configuration-set.detail.html
- ui/app/product/directives/pncProductVersionBCSets/pnc-product-version-bcsets.html
- ui/app/product/directives/pncProductVersionBCSets/pncProductVersionBCSets.js
- ui/app/styles/app.css
This functionality add the possibility of selecting a standard BuildConfigurationSet build (that would reuse its existing BuildConfigurations builds, if any), or forcing the rebuild of all its BuildConfigurations, regardless of eventual existing builds.
** NOTE ** the previous default behavior of the "Build" button was to FORCE the rebuilds. Now it has changed to NOT FORCE the rebuilds. To force the rebuilds, a new Button is provided.
> NCL-1187 - Option to skip or force rebuild of existing builds in web UI

- ui/app/configuration-set-record/directives/pncRecentCsBuilds/pnc-recent-cs-builds.html
- ui/app/configuration-set-record/directives/pncRunningCsBuilds/pnc-running-cs-builds.html
- ui/app/configuration-set/directives/pncBCTab/pnc-bc-tab.html
- ui/app/record/directives/pncRecentBuilds/pnc-recent-builds.html
- ui/app/record/directives/pncRunningBuilds/pnc-running-builds.html
- ui/app/styles/app.css
Added the visualization of the user who triggered the build in the "Build Progress" and "Configuration Set Build Progress" pages. Modified also the BuildConfigurationSet Details page, where a fake user (John Doe) was showed, intending to show who created the BuildConfiguration. But we don't have that data in the DB. So removed the column, and added the information of the user who triggered the last build. All the usernames are in bold, since it is a quite important data to show.
> NCL-1014 - User who invoked the build is not displayed in UI

- ui/app/common/restclient/services/ProductImportDAO.js
If the '/' in the path is omitted, PNC will try to access:
'localhost:8080/pnc-web/da-bcg ...'
instead of:
'localhost:8080/da-bcg ...'
This commit fixes it.
> Fix for relative path for import

- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildGroupRemovedAfterArtifactExtractionTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildRepoPromotionToUntestedBuildsGroupTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/fixture/TestBuildExecution.java
- spi/src/main/java/org/jboss/pnc/spi/BuildExecution.java
- Tests adjusted to untested-builds group and for build-group cleanup after extraction of artifacts
- Adding desription including build ID and project name to hosted repo / build group
- Removing the build group when artifact extraction completes, since it's only useful during the build.
> Describe repo/group for build, clean up build group afterward, improve tests.

- ui/app/common/pagination/PageFactory.js
This is causing only a single page to be loaded instead of all.
> Fix decorateNonPaged bug when DAO method called without arguments.

- ui/app/configuration-set/configuration-set-controllers.js
- ui/app/configuration-set/views/configuration-set.create.html
- ui/app/configuration-set/views/configuration-set.detail.html
- ui/app/configuration/configuration-controllers.js
- ui/app/configuration/views/configuration.create.html
- ui/app/configuration/views/configuration.detail-main.html
- ui/app/configuration/views/configuration.list.html
- ui/app/import/product/ProductImportCtrl.js
- ui/app/import/product/directive/ProductImportBCForm/product-import-bc-form.html
- ui/app/import/product/directive/ProductImportStartForm/product-import-start-form.html
- ui/app/import/product/directive/ProductImportTree/product-import-tree.html
- ui/app/product/product-controllers.js
- ui/app/product/views/product.create.html
- ui/app/product/views/product.detail.html
- ui/app/product/views/product.version.create.html
- ui/app/product/views/product.version.html
- ui/app/project/project-controllers.js
- ui/app/project/views/project.create.html
- ui/app/project/views/project.detail.html
@alexcreasy 
This adds some consistency when creating and updating Products, Projects, BuildConfigurations, BuildConfigurationSets, ProductVersions, implementing full "clear" and "cancel" functionality (which reset also the form validation state for consistency). Moreover, it adds validation (and feedback) when editing entities inline. After the update, also the pages get reloaded to update all the Breadcrumbs (in some cases they were left not updated).
> NCL-1451, NCL-1448, NCL-1413, NCL-1446 - Ui form reset and validation

- datastore/src/main/java/org/jboss/pnc/datastore/predicates/rsql/RSQLNodeTravellerPredicate.java
- integration-test/src/test/java/org/jboss/pnc/integration/RSQLTest.java
Reverts project-ncl/pnc#683, as it leads to "Could not parse query..." errors on UI
> Revert "NCL-1342 Spaces are allowed in RSQL"

- rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
validateCondition needs the boolean parameter to be true, otherwise validation will fail. Without this change, the validateCondition will only pass when configId == dependencyId, which cannot be the intent. With this fix, NCL-1264 becomes possible.
> Fix inverted logic for adding a dependency. 

- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java
Modify the 'build' method in BuildConfigurationEndpoint to correctly indicate that a 200 response has a BuildRecordSingleton, instead of nothing. This corrects the swagger documentation on this method.
Wrap the response in the 'clone' method of  BuildConfigurationEndpoint instead of returning the raw BuildConfigurationRest
> Build configuration endpoint changes

- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildExecutionConfigurationRest.java
- spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionConfiguration.java
The build execution config should only contain a single scm repo url and revision
to be built, and should not need to differentiate between upstream and mirror repo
> [NCL-1291] Deprecate use of mirror repo in build execution config

- model/src/main/java/org/jboss/pnc/model/BuildRecord.java
This can cause problems if the build config was not loaded during the current transaction.
> [NCL-1618] Don't try to update build config when building build record

- ui/app/import/product/directive/ProductImportStartForm/ProductImportStartForm.js
- ui/app/import/product/directive/ProductImportStartForm/product-import-start-form.html
This optional field is added to the Product import process.
This allows products that need custom repositories (not defined in the
pom.xml) to be analyzed by allowing the user to specify the custom
repositories.
On submit, the additional field 'repositories' will be sent to the
configured Dependency Analysis server. That field will contain a list of
repositories to add.
I had to override the Clear button so that it also clears the list of repositories.
Thank you to @alexcreasy for the mockup review :smile:
> [NCL-1483] Add optional field with repositories

- maven-repository-manager/pom.xml
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRunningDeletion.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRunningPromotion.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractImportTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractRepositoryManagerDriverTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesConfSetGroupTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesProductVersionGroupTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/DownloadTwoThenVerifyExtractedArtifactsContainThemTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ImportDepVerifyPromotionToSharedImportsTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadOneThenDownloadAndVerifyArtifactHasOriginUrlTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildGroupRemovedAfterArtifactExtractionTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildRepoPromotionToUntestedBuildsGroupTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualDeletionOfBuildRepoTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualPromotionOfBuildRepoTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/fixture/Producer.java
- maven-repository-manager/src/test/resources/META-INF/beans.xml
- pom.xml
Also, update client library from AProx to Indy, and use the approaching-final 0.99.0 version. Minor changes to httpclient and log4j deps to clean up depgraph and make things work again.
> NCL-1646 Use local URL from tracking record for origin URL with hosted artifact refs

- rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductReleaseEndpoint.java
This changes the return declaration of the swagger annotations to match what is actually being returned by the provider.
> fix for NCL-1728

- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationSetEndpoint.java
Slightly modify the @Consumes annotation for swagger.json. Without this slight tweak, clients generated from swagger-codegen will be incorrect.
> update consumes API documentation for swagger

- ui/app/_pnc.js
- ui/app/index.html
- ui/app/styles/app.css
- ui/bower.json
When using frontend web frameworks like Angular JS, sometimes it's
really hard to know when a page is loading after we click on a button.
For e.g if clicking the button redirects us to another page that takes a
long time to load, we don't have any visual feedback that the other page
is being loaded, prompting the user to re-press the button again.
In traditional web frameworks, our browser would show a spinner that
gives us visual feedback that it is still loading.
Using angular-loading-bar adds the visual feedback currently lacking in
our Web UI.
I've chosen to use the color orange for the bar since we don't use that color anywhere on PNC Web-UI, and is therefore easily seen, not yet too distracting.
> Use angular-loading-bar to show progress

- ui/npm-shrinkwrap.json
(cherry picked from commit aee3a5157b4f85d4d18b3b38d8018540c5c67afe)
> NCL-1771 - Bump version of i in npm-shrinkwrap to 0.3.3

- ui/app/services.js
Remove hard-coding of the 409 response code error message. This allows the correct error message from the REST API to be displayed.
> Fix for NCL-1878

- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
This is easier to verify than the sha256 checksum
> [NCL-1820] Store md5 checksum in artifact database

- integration-test/pom.xml
- openshift-environment-driver/pom.xml
- pom.xml
first part includes:
- possible to run single tests (still terribly slow)
- download and configure EAP always when needed
- `container-tests` and `remote-tests` are trigered according to property usage (README changed)
> NCL-1243 first part of update of container tests configuration.

- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java
- moduleconfig/src/main/resources/pnc-config.json
- termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriverTest.java
This commit does 2 changes:
- Fix issue where the wrong field is set:
* executorThreadPoolSize is set instead of builderThreadPoolSize
- Add fields 'coordinatorThreadPoolSize' and
'coordinatorMaxConcurrentBuilds' to the pnc-config.json
> [NCL-1957] Define coordinatorThreadPoolSize in config

- rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
Fail the validation when the configuration name already exists even if the new
configuration is part of a different project.
> [NCL-1719] Fix build configuration name validation

- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
It was "[NCL-1827] Delete group (merged) metadata associated with the artifacts we're promoting, either to shared-imports or as build output.".
> NCL-2094 - apply workaround from NCL-1827 also on v0.9 branch

- pom.xml
We want to update to the latest openshift rest client because of issues
experienced with the 3.0.1.Final version with Openshift 3.2.
The request type was not set in that version.
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the
body of the request was in an unknown format - accepted media types
include: application/json,
application/yaml","reason":"UnsupportedMediaType","code":415}
```
We hope that by upgrading to the latest version, this error will
disappear.
> Update to latest openshift rest client

- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/OpenshiftEnvironmentDriverModuleConfig.java
- moduleconfig/src/main/resources/pnc-config.json
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
- openshift-environment-driver/src/main/resources/openshift.configurations/v1_pnc-builder-route.json
Changes made:
- Add 'buildAgentHost' variable into openshift driver configuration
- Use that new variable to setup routes
- Use that new variable to setup the service name
> [NCL-2168] Make build agent route configurable

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
We shouldn't do that since Openshift will complain that the new route
name does not conform to the DNS convention. We are going to revert that
change
> [NCL-2168] Don't specify host in route-name

- model/src/main/java/org/jboss/pnc/model/BuildConfigurationAudited.java
This seems to be causing postgresql to create a "long" type column for some reason
> [NCL-2198] Remove the text type definition from the buildscript column

- openshift-environment-driver/src/main/resources/openshift.configurations/v1_pnc-builder-pod.json
The current DNS policy for the build agent pod created by PNC on
Openshift is Default.
This causes us issues since the 'Default' policy doesn't add the
internal DNS nameserver of Openshift inside the build agent pod. We
would really like to have the internal DNS nameserver to solve NCL-2201.
Using the dns policy of 'ClusterFirst' should add to `/etc/resolv.conf`
the internal DNS nameserver of Openshift
> [NCL-2204] Change DNS policy of build agent pod

- openshift-environment-driver/src/main/resources/openshift.configurations/v1_pnc-builder-pod.json
The current DNS policy for the build agent pod created by PNC on
Openshift is Default.
This causes us issues since the 'Default' policy doesn't add the
internal DNS nameserver of Openshift inside the build agent pod. We
would really like to have the internal DNS nameserver to solve NCL-2201.
Using the dns policy of 'ClusterFirst' should add to `/etc/resolv.conf`
the internal DNS nameserver of Openshift
> [NCL-2204][v0.9] Change DNS policy of build agent pod

- ui/app/_pnc.js
- ui/app/common/pnc-client/_pnc-client.js
- ui/app/common/pnc-client/pagination/Page.js
- ui/app/common/pnc-client/pagination/Paginator.js
- ui/app/common/pnc-client/pagination/_pagination.js
- ui/app/common/pnc-client/pagination/filteringPaginator.js
- ui/app/common/pnc-client/resources/BuildRecord.js
- ui/app/common/pnc-client/resources/_resources.js
- ui/app/common/pnc-client/rsql/_rsql.js
- ui/app/common/pnc-client/rsql/comparator.js
- ui/app/common/pnc-client/rsql/context.js
- ui/app/common/pnc-client/rsql/operator.js
- ui/app/common/pnc-client/rsql/rsqlQuery.js
- ui/app/common/pnc-client/rsql/selector.js
This addresses a number of issues with the current API:
- Automatically applies paging functionality where necessary, there's no need to add decorating functions calls to ng-resource services.
- Adds ability to filter queries by a field, order by a field and change page size.
- Returns promises so as doesn't mess up ui router resolves
- decouples paging and pagination API.
- decouples searching and pagination. 
- Adds new features such as ability to change page size, or add query parameters to the search.
- Doesn't always cause a wildcard RSQL query to be performed even when there is no search term.
> NCL-2215 New paging API

- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/swagger/response/AttributeSingleton.java
Adds a new class of response, 'AttributeSingleton'. This allows clients generated using swagger-codegen to be correct, such as the PNC-CLI
> NCL-2305 Swagger Annotations BuildRecordEndpoint

- .gitignore
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractRepositoryManagerDriverTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadOneThenDownloadAndVerifyArtifactHasOriginUrlTest.java
- pom.xml
* @Ignore UploadOneThenDownloadAndVerifyArtifactHasOriginalUrlTest, since it requires registration of file as both upload and download, which doesn't make sense.
* Rename buildRepoId in MavenRepositorySession to be more consistent with the rest of PNC (buildContentId)
* Disable multi-threaded event processing in Indy for integration tests (new for Indy 1.0.0)
* Upgrade Indy to 1.0.0
> Add some test dirs to .gitignore, adjust buildRepoId, use Indy 1.0.0

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
- build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/DatastoreAdapterTest.java
- build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/event/StatusUpdatesTest.java
- build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionSession.java
- model/src/main/java/org/jboss/pnc/model/BuildRecord.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/executor/BuildExecutionSessionMock.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/spi/BuildResultMock.java
- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildRecordRest.java
- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/bpm/BuildResultRest.java
- spi/src/main/java/org/jboss/pnc/spi/BuildResult.java
- This is (in case of Maven) GAV of the POM being built. This information comes
from Repour/PME and has to be stored in the build record to be used in ~~brew bridge push~~ release process.
- NCL-2345
> Store execution root name and version in build record.

- process-managers/src/main/java/org/jboss/pnc/managers/ProductMilestoneReleaseManager.java
Exception message is now skipped from the push log.
It contained details that are irrelevant for the user.
> Simplified log message for milestone release failure

- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/OpenshiftBuildAgentConfig.java
Linked to NCL-2166
In NCL-2166, we add the ability to externalize pnc-build-agent pod
definitions in pnc-config.json, and the ability to only specify one
definition, not all of them.
Unfortunately, the second ability doesn't work. If one pod definition is
defined, but the others are not, the final definition used will be 'null'
This commit fixes this issue.
> [NCL-2410] External pnc-build-agent defs are null

- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/OpenshiftBuildAgentConfig.java
Linked to NCL-2166
In NCL-2166, we add the ability to externalize pnc-build-agent pod
definitions in pnc-config.json, and the ability to only specify one
definition, not all of them.
Unfortunately, the second ability doesn't work. If one pod definition is
defined, but the others are not, the final definition used will be 'null'
This commit fixes this issue.
> [NCL-2410][v0.10] External pnc-build-agent defs are null

- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationAuditedRest.java
- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildConfigurationRest.java
- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildExecutionConfigurationRest.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationEndpoint.java
This change is not backwards compatible and clients should update their rest request models.
> Removed deprecated scmMirror* fields.

- build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java
- maven-repository-manager/pom.xml
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/RepositoryManagerDriver.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractImportTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractRepositoryManagerDriverTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AllSessionUrlsForBuildAreAlikeTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesConfSetGroupTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/BuildGroupIncludesProductVersionGroupTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/DependencyUrlIncludesTrackingIdAndGeneratedBuildGroupNameTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/DownloadTwoThenVerifyExtractedArtifactsContainThemTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ExcludeInternalRepoByNameTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ExcludeInternalRepoByRegexTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/ImportDepVerifyPromotionToSharedImportsTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/IndyPromotionValidationTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadOneThenDownloadAndVerifyArtifactHasOriginUrlTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/UploadTwoThenVerifyExtractedArtifactsContainThemTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildGroupRemovedAfterArtifactExtractionTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyBuildRepoPromotionToUntestedBuildsGroupTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualDeletionOfBuildRepoTest.java
- maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/VerifyManualPromotionOfBuildRepoTest.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositoryManagerMock.java
- pom.xml
- spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java
For all operations it uses now the token of currently logged in user.
Therefore we had to drop the global repos setup at PNC startup, because
there is no user signed in. But it was not used anyway, because the
setup did not contain all the needed repos.
To be able to add the support we needed to use separate Indy client
for each build. That is achieved by calling init() at the beginning of
each RepositoryManager's methods and the in completeExecution there is
the connection close() called. Another option was to close the
connection after the client is not used for a period of time, but this
approach was easier to implement. We'll see if that works well.
Regarding the tests I used null token for now. I think there is the mock
used, so it should be ok. Not sure if there are any integration …
> NCL-2496: Enable authentication in Indy

- README.md
- common/src/main/java/org/jboss/pnc/common/monitor/PullingMonitor.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/OpenshiftEnvironmentDriverModuleConfig.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriver.java
ThreadPool now configurable in class:
- OpenshiftEnvironmentDriver
- PullingMonitor
ThreadPool not made configurable in class:
- JenkinsBuildMonitor (module not built)
- BuildExecutorMock (Used for testing only)
The `OpenshiftEnvironmentDriver` is configured via the
`openshift-environment-driver` config section, with key
`executorThreadPoolSize`.
The `PullingMonitor` is configured via system properties, with key
`pulling-monitor-threadpool`. For example, you can pass:
```
-Dpulling-monitor-threadpool=15
```
parameter.
> [NCL-2373] Make all threadpool configurable

- build-executor/src/test/java/org/jboss/pnc/executor/BuildExecutionBase.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/Configurations.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriver.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
We instead use the Application Scope PNC to inject the already loaded
configuration.
This is an updated PR to #1297 . I have removed the `@Inject` in the
enum, and instead provide the configuration to the method requiring
`configuration` via the method parameter.
This is also an updated PR to #1309, resolving merge conflicts
> [NCL-2539] Configuration loaded multiple times

- rest/src/main/java/org/jboss/pnc/rest/provider/BuildConfigurationProvider.java
When someone enters internal repo URL, and then erases it, the UI sends an empty string to the backend.
This commit fixes validation so that the empty URL is not checked against the required SCM prefix.
> fixed validation for empty internal repo

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
- pom.xml
This is done by bumping the openshift-restclient-java library to
v5.5.0.Final. The older one (v4.0.5.Final) is not compatible with OSE
3.4 it seems in regards to obtaining the cluster IP of a service.
The way to create a new `IClient` object had to be modified since the
old one is now removed in v5.5.0.Final. The `getUser()` method is no
more, so I decided to use an alternate one.
> [NCL-2913] Make PNC work with OSE 3.4

- build-coordinator/src/test/resources/pnc-config-one-parallel-only.json
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/EnvironmentDriverModuleConfigBase.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/OpenshiftEnvironmentDriverModuleConfig.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/helper/HttpDestinationConfig.java
- moduleconfig/src/main/resources/pnc-config.json
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
- openshift-environment-driver/src/main/resources/openshift.configurations/pnc-builder-pod.json
- openshift-environment-driver/src/test/resources/pnc-config.json
Add option to only allow some HTTP methods for a url. You can also
specify the port of the url.
The option is specified in pnc-config.json as such:
```
...
"firewallAllowedDestinations": "...",
"allowedHttpOutgoingDestinations": [
{"url": "<url>", allowedMethods: "PUT,POST"},
...
]
```
If the same URL is specified in both `firewallAllowedDestinations` and
`allowedHttpOutgoingDestinations`, the one in the latter has higher
priority than the former. This is enforced in the startup script running
in the builder pods.
> [NCL-2954] Add opt to only allow some http methods

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
So we were putting a JSON string inside another JSON structure. However,
we forgot to properly escape the JSON string.
The situation we were getting into is:
```
{
"name": "allowedHttpOutgoingDestinations",
"value": "[{"url":"http://haha.com","allowedMethods":"PUT"}]"
},
```
This is obviously wrong JSON. The value of the key 'value' should have
its string escaped to produce valid JSON.
```
{
"name": "allowedHttpOutgoingDestinations",
"value": "[{\"url\":\"http://haha.com\",\"allowedMethods\":\"PUT\"}]"
},
```
This commit fixes that bug.
> Fix nested JSON statement for allowedHttpOutgoingDestinations

- ui/app/milestone/milestone-controllers.js
The issue was caused because `that.data.endDate` is null but
`that.data.plannedEndDate` is generally not.
The fix is to check if `that.data.endDate` is null; if it is then use
the `that.data.plannedEndDate` as value, else use `that.data.endDate`.
Before:
The JS object:
With the fix:
> [NCL-2775] Weird date when closing a milestone

- openshift-environment-driver/src/main/resources/openshift.configurations/pnc-builder-pod.json
We don't need that secret mount anymore. That mount contains TLS certs;
however these certs are already mounted into the builder image pods, so
it's not necessary to have the secret mounted.
> Remove secret mount from build agent pod def

- bpm/src/main/java/org/jboss/pnc/bpm/task/BpmBuildTask.java
- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/local/LocalBuildScheduler.java
- build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionConfiguration.java
- build-executor/src/test/java/org/jboss/pnc/executor/BuildEnvironmentTest.java
- build-executor/src/test/java/org/jboss/pnc/executor/BuildExecutionBase.java
- integration-test/src/test/java/org/jboss/pnc/integration/BuildTasksRestTest.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/executor/BuildExecutionConfigurationMock.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/spi/BuildExecutionConfigurationMock.java
- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildExecutionConfigurationRest.java
- rest-model/src/test/java/org/jboss/pnc/restmodel/serialization/BuildExecutionConfigurationTest.java
- rest/src/test/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpointTest.java
- rest/src/test/java/org/jboss/pnc/rest/serialization/BuildExecutionConfigurationTest.java
- spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionConfiguration.java
Provide origin repository URL to the BuildExecutionConfiguration so that
the Maitai process then passes the URL to repour for auto-sync feature
> [NCL-3028] Provide origin repository to BEC

- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildExecutionConfigurationRest.java
This was done to help with the Maitai process. While we have different
Maitai processes, they all share the same backend code.
The backend code was updated to suit both the newer process (1.3.4) [Used in PNC 1.2.x]
which is used for the new repository configuration, and the older
process (1.3.2) [Used in PNC 1.1.x] with the older Build Configuration creation process.
Therefore, the backend code will send extra fields (with value null) for
process 1.3.2, which causes Jackson to throw an error that it doesn't
know about those extra fields.
This commit tells Jackson to ignore those extra fields.
> Ignore unknown fields on BuildExecutionConfigurationRest

- process-managers/src/main/java/org/jboss/pnc/managers/ProductMilestoneReleaseManager.java
When the milestone release process is started, its status is not set to
IN_PROGRESS. As such, the status is set to null while the release
process is being performed.
This commit puts the status to IN_PROGRESS just before the BPM process
is triggered to rectify this.
> [NCL-3326] Set release status to in-progress

- ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js
(cherry picked from commit 19b173ed84158d05c46d650aa4826cd2be409944)
> NCL-3377 Fixes: Pre-build sync enabled flag is not stored

- process-managers/src/main/java/org/jboss/pnc/managers/ProductMilestoneReleaseManager.java
- process-managers/src/test/java/org/jboss/pnc/managers/ProductMilestoneReleaseManagerTest.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/ProductMilestoneEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/provider/ProductMilestoneProvider.java
- rest/src/test/java/org/jboss/pnc/rest/provider/AbstractMilestoneReleaseTest.java
- rest/src/test/java/org/jboss/pnc/rest/provider/MilestoneReleaseTest.java
- ui/app/common/restclient/services/ProductMilestoneDAO.js
- ui/app/milestone/milestone-controllers.js
- ui/app/milestone/views/milestone.close.html
- ui/app/product/directives/pncProductVersionMilestones/pnc-product-version-milestones.html
- ui/app/product/directives/pncProductVersionMilestones/pncProductVersionMilestones.js
This commit applies changes to the close milestone process related to
NCL-3112 and NCL-2999.
A milestone is considered closed when the release process is successful
and the end date for this milestone is set.
We can initiate the close milestone process by hitting the
`/close-milestone` endpoint. Optionally, we can specify the
`downloadUrl` in that endpoint.
When the `/close-milestone` endpoint is hit, it will start the release
process. If the release process for the milestone is successful, the
following happens:
- the `endDate` of the milestone is set to the date the process release
succeeded
- if the milestone is set as 'current' in the product version, it is
then unset as 'current'
On the Web UI, if the end date of a milestone is set, then the options
to:
- set as current
- edit …
> [NCL-3112][NCL-2999] Close milestone process

- ui/.bowerrc
It looks like since Oct 11, the old bower registry got deprecated.
https://twitter.com/bower/status/918073147789889536
This causes the PNC build to fails because the ui/bower component cannot
talk to the mothership.
This PR updates our .bowerrc to specify the new registry to use.
> (v1.2 branch) Fix bower

- model/src/main/resources/db-update/00001-from-1.2.0-to-1.3.0.sql
Otherwise when we insert a new row into the target repository table,
we will try to add a new row with id 1 instead of id = 6
Note that we are not setting last_value to 5 because the target
repository sequence has column 'is_called' set to false.
https://www.postgresql.org/docs/8.1/static/functions-sequence.html
According to the document above, if 'is_called' is false, it will use
the value of 'last_value' as the next id. If 'is_called' is true, it
will use the value of 'last_value' + 1 as the next id.
Since we've only inserted 5 items, and 'is_called' is false, the
'last_value' column should be set to 6.
> Start targetrepo seq with last value = 6 for migration

- common/src/main/java/org/jboss/pnc/common/util/TimeUtils.java
- common/src/test/java/org/jboss/pnc/common/test/util/TimeUtilsTest.java
Currently, if the month, day, or time is a single digit, the timestamp
generated will be:
```
t<yyyy>-<m>-<d>-<h>-<M>-<s>-<f>
```
This commit changes this so that we add extra '0' where necessary. The
timestamp then looks like this:
```
t<yyyy>-0<m>-0<d>-0<h>-0<M>-0<s>-00<f>
```
E.g 't20170803-010305-009'
> Make timestamp generation prettier

- model/src/main/resources/db-update/00001-from-1.2.0-to-1.3.0.sql
The schema changes were obtained by first running
pnc-schema-generator[1] on PNC 1.2.0 and PNC 1.3.0-SNAPSHOT.
[1] is still a little bit confused on the names of the foreign keys and
seems to use random foreign key names instead of the ones we used in the
code.
We then use apgdiff[2] to get a sort of migration SQL commands to run
when migration from the schema from 1.2.0 to 1.3.0-SNAPSHOT. The
migration SQL commands is not perfect though. For one, it might generate some
weird output (rare), and it might generate unecessary foreign key migrations
due to the problem with [1] mentioned ealier.
However, it is still really useful, and this was used to create the new
updates in that script.
This commit also contain changes for NCL-3533, which is to migrate data
from build_record_attributes to …
> [NCL-3533] Update migration script from 1.2.0 to 1.3.0

- README.md
- common/src/main/java/org/jboss/pnc/common/monitor/PullingMonitor.java
PR-1275 (https://github.com/project-ncl/pnc/pull/1275) introduced the
ability to configure the timeout and check interval required to wait for
the builder pod to start. Unfortunately due to commits that PR is in an
umergeable state.
This commit attempts to add the same configuration in a different
approach, using system, or environment properties. This approach was
used because we are already using the same concept to configure the default
thread pool size we use for building (See NCL-2373)
> [PR-1275]Add ability to configure pod strt timeout

- model/src/main/java/org/jboss/pnc/model/BuildEnvironment.java
- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildEnvironmentRest.java
This commit adds the field 'deprecated' to the 'BuildEnvironment' model
to indicate which build environments are deprecated and shouldn't be
used in current/future build environments.
Note that this commit doesn't add a restriction on the backend on
assigning a deprecated build environment to a build configuration. This
is done so that you can still modify an existing build configuration
using deprecated build environment.
> [NCL-3514] Don't show deprecated environments

- model/src/main/resources/db-update/00001-from-1.2.0-to-1.3.0.sql
The migration script sets the temporarybuild to 'true' for existing
data. I believe that this is wrong and it should be set to 'false' for
*existing* data.
> Set temporarybuild = false for existing data

- datastore/src/test/java/org/jboss/pnc/datastore/DatastoreTest.java
- demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
- model/src/main/java/org/jboss/pnc/model/TargetRepository.java
- model/src/main/resources/db-update/00001-from-1.2.0-to-1.3.0.sql
- model/src/test/java/org/jboss/pnc/model/ArtifactTest.java
- model/src/test/java/org/jboss/pnc/model/BasicModelTest.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/model/builders/ArtifactBuilder.java
- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/TargetRepositoryRest.java
- rest/src/main/java/org/jboss/pnc/rest/provider/ArtifactProvider.java
- ui/app/build-records/views/build-records.detail.artifacts.html
The flag was merged into repository type, which does not make much sense
and made the code more complicated, since 2 values had to be checked for
a single repository type.
> Extract temporary as a separate flag in TargetRepository

- rest/src/main/java/org/jboss/pnc/rest/utils/BpmNotifier.java
> [NCL-3695]: Don't use toString method to pass parameters to Maitai - 1.3

- common/src/main/java/org/jboss/pnc/common/monitor/PullingMonitor.java
Monitor bug
-----------
The 'monitor' bug inside `PullingMonitor` class happens in situations
where the `monitor` runnable is run before `runningTaskReference` is set
with the running task since the runnable is scheduled to run before
`runningTaskReference` is set.
In those cases, we just skip this runnable run and re-run it on the next
scheduled interval with the assumption that `runningTaskReference` will
be set before the next re-run.
Without the fix, if the condition is true, we'll try to remove from the
'runningTasks' ConcurrentSet object a null object
('runningTaskReference' contains a null object, that null object is
assigned to variable 'runningTask' inside the runnable). This causes the
'remove' method to throw a NullPointerException.
Ironically, the NullPointerException is …
> Fix monitor bug and builder image not starting

- common/src/main/java/org/jboss/pnc/common/monitor/PullingMonitor.java
Monitor bug
-----------
The 'monitor' bug inside `PullingMonitor` class happens in situations
where the `monitor` runnable is run before `runningTaskReference` is set
with the running task since the runnable is scheduled to run before
`runningTaskReference` is set.
In those cases, we just skip this runnable run and re-run it on the next
scheduled interval with the assumption that `runningTaskReference` will
be set before the next re-run.
Without the fix, if the condition is true, we'll try to remove from the
'runningTasks' ConcurrentSet object a null object
('runningTaskReference' contains a null object, that null object is
assigned to variable 'runningTask' inside the runnable). This causes the
'remove' method to throw a NullPointerException.
Ironically, the NullPointerException is …
> [v1.3] Fix monitor bug and builder image not starting

- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationSetEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
The predicate fix is for getting a list of BuildRecord from a build
config set id.
> [NCL-3816] Fix predicates for buildconfigset

- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigurationSetEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
The predicate fix is for getting a list of BuildRecord from a build
config set id.
> [v1.3][NCL-3816] Fix predicates for buildconfigset

- maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java
It sets readonly flag as part of the promotion, which we don't want to
do for temporary builds. So we have to reset it after the promotion.
This is worth probably only for PNC 1.3, because 1.4 and on will use
Indy 1.3.x for sure.
> [1.3] NCL-3509 Support usage of Indy 1.2.x and earlier

- README.md
- integration-test/src/test/resources/application.xml
- metrics/src/main/java/org/jboss/pnc/metrics/MetricsConfiguration.java
- rest/pom.xml
- rest/src/main/java/org/jboss/pnc/rest/configuration/JaxRsActivator.java
- rest/src/main/java/org/jboss/pnc/rest/configuration/metrics/GeneralRestMetricsFilter.java
- rest/src/main/java/org/jboss/pnc/rest/configuration/metrics/TimedMetric.java
- rest/src/main/java/org/jboss/pnc/rest/configuration/metrics/TimedMetricFilter.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildConfigSetRecordEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordEndpoint.java
This PR includes:
- Add ability to specify rate of reporting data to Graphite
- Track all REST request metrics
- Track specific REST request metrics
> Track REST endpoint metrics

- auth/src/main/java/org/jboss/pnc/auth/KeycloakClient.java
- auth/src/main/java/org/jboss/pnc/auth/KeycloakServiceClient.java
- auth/src/main/java/org/jboss/pnc/auth/keycloakutil/util/HttpUtil.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/KeycloakClientConfig.java
Respect the ssl-required setting in pnc-config to allow talking to
keycloak without SSL client verification. Also changing the expected
value type from string to boolean, because the string value "none" used
before is EAP specific and has no meaning in our context.
The setting of the sslRequired value is done in KeycloakClient before
performing the request. It is not thread-safe but when we use single
value coming from config which cannot be changed during runtime, it
should be ok.
> [v1.3][NCL-3855] Failed to delete temporary build

- auth/src/main/java/org/jboss/pnc/auth/KeycloakClient.java
- auth/src/main/java/org/jboss/pnc/auth/KeycloakServiceClient.java
- auth/src/main/java/org/jboss/pnc/auth/keycloakutil/util/HttpUtil.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/KeycloakClientConfig.java
Respect the ssl-required setting in pnc-config to allow talking to
keycloak without SSL client verification. Also changing the expected
value type from string to boolean, because the string value "none" used
before is EAP specific and has no meaning in our context.
The setting of the sslRequired value is done in KeycloakClient before
performing the request. It is not thread-safe but when we use single
value coming from config which cannot be changed during runtime, it
should be ok.
> [NCL-3855] Failed to delete temporary build

- pom.xml
Using Indy client 1.3.0.2 is causing tests to fail. To progress now we will temporarily stick to 1.2.0.
> Use Indy 1.2.0 for now

- pom.xml
The first occurence starts on line 615.
> [v1.4] Remove duplicate of logback-classic from dependencyManagement

- rest/src/main/resources/buildConfigurationSupportedGenericParameters.properties
Specify the execution root name of the build configuration. This is used
to override the default value, and can be useful for builds that disable
PME. Format is '<groupid>:<artifactid>'
> [v1.4][NCL-4089] Add EXECUTION_ROOT_NAME generic param

- model/src/main/java/org/jboss/pnc/model/BuildRecord.java
- model/src/main/resources/db-update/00002-from-1.3.0-to-1.4.0.sql
The SQL schema update file has also been updated to add the extra
columns in buildrecord into the database.
> [v1.4] dependen*recordids in buildrecord set to 'text' type

- model/src/main/java/org/jboss/pnc/model/BuildRecord.java
- model/src/main/resources/db-update/00002-from-1.3.0-to-1.4.0.sql
The SQL schema update file has also been updated to add the extra
columns in buildrecord into the database.
> dependen*recordids in buildrecord set to 'text' type

- model/src/main/java/org/jboss/pnc/model/Artifact.java
- model/src/main/resources/db-update/00002-from-1.3.0-to-1.4.0.sql
to allow per-build target repositories for generic http downloads.
Also remove inserts meant for 2.0 that were already removed in master.
> [1.4] Remove unique constraint on artifact.originurl

- model/src/main/java/org/jboss/pnc/model/Artifact.java
- model/src/main/resources/db-update/00002-from-1.3.0-to-1.4.0.sql
to allow per-build target repositories for generic http downloads.
> Remove unique constraint on artifact.originurl

- CHANGELOG.md
- termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
When debug mode is on (or keep pod alive is on), we now execute a script
(startDebugTools.sh) before the build script runs, and another script
(stopDebugTools.sh) if the build script fails.
In the case the build script passes, the pod will die and will
automatically kill any debug tools still running. (the build script
typically runs the Maven command)
The usecase for the scripts right now is to start running `tcpdump` in
the background to capture packet going in/out of the pod (inside
`startDebugTools.sh`). If the build script fails, we can then stop the
`tcpdump` capture by running `stopDebugTools.sh`. The tcpdump capture is
then accessible to the user to analyze since the pod stays alive if the
build script fails.
The idea behind running scripts instead of running the 'tcpdump' …
> [NCL-4189] Execute debug scripts if debug mode on

- dto/src/main/java/org/jboss/pnc/dto/internal/BuildExecutionConfiguration.java
- dto/src/main/java/org/jboss/pnc/dto/model/Build.java
- dto/src/main/java/org/jboss/pnc/dto/model/BuildConfigurationRevision.java
- dto/src/main/java/org/jboss/pnc/dto/model/Product.java
- dto/src/main/java/org/jboss/pnc/dto/model/ProductMilestone.java
- dto/src/main/java/org/jboss/pnc/dto/model/ProductMilestoneRelease.java
- dto/src/main/java/org/jboss/pnc/dto/model/ProductRelease.java
- dto/src/main/java/org/jboss/pnc/dto/model/ProductVersion.java
- dto/src/main/java/org/jboss/pnc/dto/model/Project.java
- dto/src/main/java/org/jboss/pnc/dto/model/ProjectRef.java
- dto/src/main/java/org/jboss/pnc/dto/model/RepositoryConfiguration.java
- dto/src/main/java/org/jboss/pnc/dto/model/TargetRepository.java
- dto/src/main/java/org/jboss/pnc/dto/model/User.java
- dto/src/main/java/org/jboss/pnc/dto/response/ErrorResponse.java
ProductMilestoneReleaseRef, RepositoryConfigurationRef and UserRef were renamed (removing the Ref from name) as there were not additional fields left for the "full" class.
>  Add last part of DTO model.

- indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/IndyRepoDriverModuleConfig.java
I'm adding handling logic for generic-http to deal with IllegalArgumentException when trying to sort out whether tracking record entries are from an external origin. I've also added better support for generic-http in the ignored path suffixes, to be consistent.
I couldn't find a place to add unit tests for these. Please advise if you need more WRT that.
> Add generic internal-repo pattern list, support for generic-http in isExternalOrigin()

- CHANGELOG.md
- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/RunningBuildsCountRest.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/RunningBuildRecordEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/provider/BuildRecordProvider.java
This is done via endpoint: `/running-build-records/count`
REST response is:
```
{
running: <int>,
enqueued: <int>,
waitingForDependencies: <int>
}
```
> [v1.4][NCL-4392] Expose info about num of building and enqued builds

- CHANGELOG.md
- README.md
- build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java
- common/src/main/java/org/jboss/pnc/common/monitor/PullingMonitor.java
- common/src/main/java/org/jboss/pnc/common/monitor/RunningTask.java
- common/src/main/java/org/jboss/pnc/common/util/ReadEnvProperty.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/OpenshiftEnvironmentDriverModuleConfig.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/exceptions/PodFailedStartException.java
This commit adds retries for build env creation. The number of retries
is configurable by setting 'creationPodRetry' value in the
pnc-config.json
We do the retry by identifying when the pod creation failed by checking
its status periodically in monitors (or RunningTasks). The
monitors are setup in `monitorInitialization`. Once the monitors are
setup, they run in the background and `monitorInitialization` returns.
If the pod creation failed, we throw an exception that is ultimately
captured in `retryPod`. The latter will check the current number of
retries allowed. If 0: we call the `onError` consumer to end the
creation attempt. If greater than 0, we cancel and clear the existing
monitors, destroy any existing build environment Openshift objects,
recreate new build environment Openshift …
> [v1.4] Add retries for build env creation

- openshift-environment-driver/pom.xml
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriver.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
- openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java
We use Optional for the `metricRegistry` and check if
`metricsConfiguration` is null in `OpenshiftStartedEnvironment`. This is
done to facilate testing in `OpenshiftEnvironmentDriverRemoteTest`. With
those changes we can set the 'metricsConfiguration' parameter in
`OpenshiftStartedEnvironment` to null, and make metrics optional.
> [v1.4] Add metrics to track failed/success/attempts for creation of pod

- README.md
- build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java
- common/src/main/java/org/jboss/pnc/common/monitor/PullingMonitor.java
- common/src/main/java/org/jboss/pnc/common/monitor/RunningTask.java
- common/src/main/java/org/jboss/pnc/common/util/ReadEnvProperty.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/OpenshiftEnvironmentDriverModuleConfig.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/exceptions/PodFailedStartException.java
This commit adds retries for build env creation. The number of retries
is configurable by setting 'creationPodRetry' in pnc-config.json
We do the retry by identifying when the pod creation failed by checking
its status periodically in monitors (or RunningTasks). The
monitors are setup in `monitorInitialization`. Once the monitors are
setup, they run in the background and `monitorInitialization` returns.
If the pod creation failed, we throw an exception that is ultimately
captured in `retryPod`. The latter will check the current number of
retries allowed. If 0: we call the `onError` consumer to end the
creation attempt. If greater than 0, we cancel and clear the existing
monitors, destroy any existing build environment Openshift objects,
recreate new build environment Openshift objects, …
> Add retries for build env creation

- common/src/main/java/org/jboss/pnc/common/gerrit/Gerrit.java
- common/src/main/java/org/jboss/pnc/common/gerrit/GerritException.java
- common/src/test/java/org/jboss/pnc/common/gerrit/GerritTest.java
Links that it will generate:
- Gerrit Download url for an archive of a Gerrit project's
commit/sha/branch
- Gerrit Gitweb url to see the log of a Gerrit project, and optionally
ref
- Gerrit Gitweb url to see the commit of a Gerrit project, given the ref
The first link can be used in the web-ui / cli to allow users to
download an archive of the project's tag used to build the project.
The second link can be used in the SCM repository page to provide a link
to the Gerrit Gitweb page for a particular Gerrit repository.
The third link can be used in the buildconfiguration and the buildrecord
page to provide the Gerrit Gitweb page to the commit/branch/tag we're
trying to build from.
> [NCL-3766] Provide Gerrit class to generate Gerrit link

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
Sometimes object pod creation fails because of quota limits. In those
cases, an exception is thrown on pod creation indicating we are above
quota. Unfortunately we do not capture the exception and deal with it
properly.
This commit attempts to capture the exception and calls the 'onError'
callback when an exception is thrown. This is done by:
- Using CompletableFuture instead of Future
This is done to:
* be able to capture any exceptions raised in the runnables
* combine CompletableFutures together
- Adding an additional monitor to check if the Openshift
object creation CompletableFutures are finished and without
exceptions. If with exceptions, it is wrapped as a
PodFailedStartedException and thrown (and caught by the
PollingMonitor).
If the CompletableFutures are not finished yet, then …
> [v1.7][NCL-4568] Stop env monitor on error

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
Note: this is a backport of #2430 for master branch
Sometimes object pod creation fails because of quota limits. In those
cases, an exception is thrown on pod creation indicating we are above
quota. Unfortunately we do not capture the exception and deal with it
properly.
This commit attempts to capture the exception and calls the 'onError'
callback when an exception is thrown. This is done by:
- Using CompletableFuture instead of Future
This is done to:
* be able to capture any exceptions raised in the runnables
* combine CompletableFutures together
- Adding an additional monitor to check if the Openshift
object creation CompletableFutures are finished and without
exceptions. If with exceptions, it is wrapped as a
PodFailedStartedException and thrown (and caught by the
PollingMonitor).
If …
> [NCL-4568] Stop env monitor on error

- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupConfigurationEndpoint.java
[NCL-4716] Resolve HV000152 on group-configuration
This happened because 'GroupConfigurationEndpointImpl' implements
'GroupConfigurationEndpoint' and 'GroupConfigurationEndpoint' in some
sort of way implements 'AbstractEndpoint#update' method.
'GroupConfigurationEndpoint' is imposing additional contraint on the
`update` method with `@NotNull` (with AbstractEndpoint), violating the
Liskov substitution.
https://beanvalidation.org/1.1/spec/#constraintdeclarationvalidationprocess-methodlevelconstraints-inheritance
I also made sure that we are not using `@NotNull` in our Endpoint
interfaces that implements `AbstractEndpoint`.
Futher work is planned to properly add `@NotNull` constraint in our
endpoints without violating the Liskov substitution (See NCL-4767)
> [NCL-4716] Resolve HV000152 on group-configuration

- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BuildExecutionConfigurationRest.java
I believe Jackson will use the setter method to set the buildtype. Since
it doesn't do anything, buildtype is never set. This commit fixes this
situation by actually setting the buildtype field in the setter method
> [v1.7] Enable setter for buildtype

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
This commit adds the scm information of a build in case of failure. This is useful when a build has already finished alignment, and is either in the process of starting the build or building, and a failure occurs.
From the picture above, you can see that the scm revision and scm tag are not stored. This is useful information that the builder might want to see to debug her builds locally (to see for e.g the alignment done)
With this commit, the scm revision and scm tag are stored (if available).
> [v1.7][NCL-4701] Store scm info on build failure if possible

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
This commit adds the scm information of a build in case of failure. This is useful when a build has already finished alignment, and is either in the process of starting the build or building, and a failure occurs.
From the picture above, you can see that the scm revision and scm tag are not stored. This is useful information that the builder might want to see to debug her builds locally (to see for e.g the alignment done)
With this commit, the scm revision and scm tag are stored (if available).
> [NCL-4701] Store scm info on build failure if possible

- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupConfigurationEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductReleaseEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductVersionEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProjectEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/EndpointHelper.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/EnvironmentEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/GroupBuildEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/GroupConfigurationEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductReleaseEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductVersionEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProjectEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/SCMRepositoryEndpointImpl.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/UserEndpointImpl.java
It is a bit confusing from the `*EndpointImpl` the order of inheritance
between the `AbstractEndpoint` and the Endpoint interface. This hits us
with the HV000152 errors we were getting when `@NotNull` is used in
either the interface or `AbstractEndpoint` methods (See NCL-4716).
To help make things clearer, this commit makes `AbstractEndpoint` a
non-abstract class, that we can use inside our `*EndpointImpl` as a
regular object. As such, we moved `AbstractEndpoint` from inheritance to
composition (and renamed it to `EndpointHelper` to avoid confusion).
This is part 1 of the work for NCL-4767. I wanted to get this reviewed first
before I continue with it.
> [NCL-4767] Use EndpointHelper instead of AbstractEndpoint

- facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
This commit fixes a bug where the BuildConfigurationAudited object is
not fetched on the 'BuildRecord' object by default. This causes the
`mapper.toDTO` method to not be able to properly convert most of the
stuff:
```
{
"id": 57,
"submitTime": "2019-06-12T21:26:41.379Z",
"startTime": "2019-06-12T21:26:41.383Z",
"endTime": "2019-06-12T21:28:22.460Z",
"status": "DONE",
"buildContentId": "build-57",
"temporaryBuild": false,
"project": null,
"repository": null,
"environment": null,
"attributes": {},
"user": {
"id": 102,
"username": "dcheung"
},
"buildConfigurationRevision": null,
"dependentBuildIds": [],
"dependencyBuildIds": []
}
```
The project, repository, environment, and buildConfigurationRevision
fields are all obtained from the `BuildConfigurationAudited` object.
This commit tries to …
> Fetch BuildConfigAudited info in BuildProvider

- demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
- moduleconfig/src/main/resources/pnc-config.json
This is required so that ArtifactMapper won't fail on parsing URL due to empty field in pnc-config.json used for integration-tests.
> demo-data and empty field in config fix

- facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigRevisionHelper.java
- facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
- integration-test/src/test/java/org/jboss/pnc/integration_new/BuildConfigurationEndpointTest.java
The problem here is that the new revision is created only when transaction is
commited (because "Envers flushes it's audit action queue in the transaction's
before-completion callback, which happens just before the commit occurs.").
I fixed it by creating new class with
`@Transactional(Transactional.TxType.REQUIRES_NEW)`
to force new transactions.
> [NCL-4398] Fix create BC revision endpoint

- rest-api/src/main/java/org/jboss/pnc/rest/annotation/RespondWithStatus.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupConfigurationEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductReleaseEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductVersionEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProjectEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java
- rest-new/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
- rest-new/src/main/java/org/jboss/pnc/rest/provider/RespondWithStatusFilter.java
With the current strategy of implementing our REST endpoints, if
successful the JAX-RS method will always return with HTTP status 200 (or 204 if
we return void). This is because we now return the DTO in our JAX-RS
method instead of the `Response` object where we can specify the HTTP
status code.
This is problematic because we are expected to return HTTP status 201
(for creation of new stuff), and 202 for async accepted operations.
This commit adds a new annotation, `@RespondWithStatus`, to allow us to
annotate JAX-RS method with the appropriate HTTP status code. A filter
will intercept the annotation and update the HTTP to the one specified
in the annotation. The filter will only activate if a 2xx status is
returned from the JAX-RS method (typically 200 or 204)
The annotation strangely …
> [NCL-4965] JAX-RS method to specify alt HTTP code

- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/SCMRepositoryEndpointImpl.java
For the scm-repositories/create-any-sync endpoint, we should return the
appropriate HTTP status code for the following scenarios:
- scm repository already exists in the PNC database (HTTP code: 200)
- scm repository is being created (HTTP code: 202)
The implementation uses `HttpServletResponse`. The `flushBuffer` method
call is required, based on experiments. Otherwise the desired http code
is never set.
> [NCL-4960] Appropriate http code for create-and-sync

- mapper/src/main/java/org/jboss/pnc/mapper/api/TargetRepositoryMapper.java
Kinda screws with mapper consistency but we can revert it later
> [NCL-5077] workaround for RepositoryManagerResultRest not having TargetRepo

- facade/src/main/java/org/jboss/pnc/facade/providers/ProjectProviderImpl.java
- facade/src/test/java/org/jboss/pnc/facade/providers/ProductProviderTest.java
- facade/src/test/java/org/jboss/pnc/facade/providers/ProjectProviderTest.java
- The delete operation for ProjectProvider is disactivated.
- Add validation for updating a project also if the project name already
exists
ProjectProviderTest is the direct copy of ProductProviderTest
> [NCL-5006] Add ProjectProvider test

- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductReleaseEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductVersionEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java
From a558bdf commit, an extra `@Consumes(MediaType.APPLICATION_JSON_PATCH_JSON)`
is required on `getSpecific` methods whose class contains a
`patchSpecific` method with `@PATCH` annotation.
This commit applies the extra `@Consumes` on all the other endpoints.
The `ProjectEndpoint.java` does not have the fix because it is already
included in PR #2589
> Apply PATCH workaround for REST endpoints

- build-coordinator/pom.xml
- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java
- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
- build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionSession.java
- common/src/main/java/org/jboss/pnc/common/util/ProcessStageUtils.java
The build stages logged are:
- Scheduling (when a build config is being broken down into build tasks)
- Enqueued (build stayed in enqueued state)
- The various stages in `BuildExecutionStatus`
* NEW,
* REPO_SETTING_UP,
* BUILD_ENV_SETTING_UP,
* BUILD_ENV_WAITING,
* BUILD_ENV_SETUP_COMPLETE_SUCCESS,
* BUILD_SETTING_UP,
* BUILD_WAITING,
* COLLECTING_RESULTS_FROM_BUILD_DRIVER,
* COLLECTING_RESULTS_FROM_REPOSITORY_MANAGER,
* REPOSITORY_MANAGER_SEALING_TRACKING_RECORD,
* REPOSITORY_MANAGER_DOWNLOADING_TRACKING_REPORT,
* REPOSITORY_MANAGER_PROCESSING_DEPENDENCIES,
* REPOSITORY_MANAGER_PROCESSING_BUILT_ARTIFACTS,
* REPOSITORY_MANAGER_REMOVE_BUILD_AGGREGATION_GROUP,
* REPOSITORY_MANAGER_PROMOTION_BUILD_CONTENT_SET,
* COLLECTING_RESULTS_FROM_REPOSITORY_MANAGER_COMPLETED_SUCCESS,
* …
> [v1.8][NCL-5267] Log PNC build related stages begin and end

- auth/src/test/resources/testConfig.json
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/KeycloakClientConfig.java
- pnc-mock/src/main/resources/keycloakClientConfig.json
This is done so that we don't leak our secret in our main config file.
As such, the change required in the config file is from:
```
credentials: {
"secret": "super-secret-token"
}
```
to:
```
credentials: {
"secretFileLocation": "/path/to/file/that/contains/token"
}
```
> [NCL-5254] Move the keycloak client secret to a path

- auth/src/test/resources/testConfig.json
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/KeycloakClientConfig.java
- pnc-mock/src/main/resources/keycloakClientConfig.json
This is done so that we don't leak our secret in our main config file.
As such, the change required in the config file is from:
```
credentials: {
"secret": "super-secret-token"
}
```
to:
```
credentials: {
"secretFileLocation": "/path/to/file/that/contains/token"
}
```
> [v1.8][NCL-5254] Move the keycloak client secret to a path

- datastore/src/main/java/org/jboss/pnc/datastore/repositories/GenericSettingRepositoryImpl.java
- datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/GenericSettingSpringRepository.java
- model/src/main/java/org/jboss/pnc/model/GenericSetting.java
- model/src/main/resources/db-update/00006-from-1.7.1-to-1.8.0.sql
- rest/src/main/java/org/jboss/pnc/rest/provider/HealthCheckProvider.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/GenericSettingPredicates.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/GenericSettingRepository.java
The new entity will be more generic and will also be used to setup the
maintenance mode.
In general you can now use the new entity for key=value settings
> [v1.8] Replace entity healthcheck with generic setting

- rest-model/src/main/java/org/jboss/pnc/rest/restmodel/BannerRest.java
- rest/src/main/java/org/jboss/pnc/rest/configuration/JaxRsActivator.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/GenericSettingEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/provider/GenericSettingProvider.java
- rest/src/main/java/org/jboss/pnc/rest/trigger/BuildTriggerer.java
When maintenance mode is on, no new builds will be allowed into the
system. An exception will be thrown with reason being that PNC is in
maintenance mode.
The announcement banner is used to display messages to users for future
migration dates and announcements.
When the maintenance mode is switched to on with a reason, the
announcement banner will be set with the reason.
> [v1.8][NCL-5297] Add Maintenance mode an annoucement banner

- build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/AbstractDependentBuildTest.java
- datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
- datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
- datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/BuildRecordSpringRepository.java
- model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/datastore/DatastoreMock.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildConfigurationAuditedRepositoryMock.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BuildRecordPushEndpoint.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java
@thescouser89 @jbartece 
Recreated from https://github.com/project-ncl/pnc/pull/2772.
So working on https://github.com/project-ncl/pnc/pull/2771, I noticed that the "record.getDependencies()" call generates one single query, while the ".map(Artifact::getBuildRecords)" generates one query per dependency. So if there is a list of 1000 dependencies in a BuildRecord, 1000 queries are generated. I kept the first query and then attempted to create a single query for the rest, using a JPA query to optimize as much as possible. This should improve the checks for the implicit rebuilds by drastically reducing the number of executed queries. There could be more optimizations coming also (e.g. not trying to query multiple times for the same dependency).
Also, I resolved some warnings about …
> [v1.8] NCL-5276 - optimization of implicit rebuild generated queries 

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java
- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
- build-coordinator/src/test/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinatorTest.java
- datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/datastore/DatastoreMock.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/Datastore.java
@jbartece this is an extension of the work done in https://github.com/project-ncl/pnc/pull/2777, to create a cache to avoid duplicated checks. As we are processing dependencies, it could be very common that in a set of BuildRecords to be verified during an implicit rebuild, the same dependencies are present (e.g. parent upstream poms). This cache aims to avoid making the same queries for the same dependencies. Thanks for the review!
> [v1.8] NCL-5276 implicit rebuild optimization 2

- common/src/main/java/org/jboss/pnc/common/util/StringUtils.java
Replace it with:
```
<str>.trim().isEmpty()
```
Reasoning:
`isBlank` String method is only available in Java 11, and since we're
still targetting Java 1.8, this method shouldn't be used.
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#isBlank()
> Remove `<str>.isBlank()` method call

- common/src/main/java/org/jboss/pnc/common/json/JsonOutputConverterMapper.java
- common/src/test/java/org/jboss/pnc/common/json/JSonOutputConverterTest.java
- integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/ProcessProgressNotificationTest.java
- integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/notifications/WebSocketsNotificationTest.java
In REST we serialize also NULL values, in WS we use object mapper from
common and it was not ommiting fields with NULL values.
> [NCL-5413] Serialize also null values to JSON

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
When we set the initial states for the build task, both for internal and
logging purposes, the log context is not set properly. This commit
attempts to fix this.
> Add log context when setting waiting for dep/enqueued

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
If a build is in 'enqueued' or waiting for dependencies', and one of its
dependencies fail, the stage end is not logged. This tricks the build
metrics into thinking nothing happened.
This commit properly logs the process stage end if a dependent build
failed.
CC: @matedo1
> [v1.8] Log process stage end for enqueued/waiting for dependencies

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
If a build is in 'enqueued' or waiting for dependencies', and one of its
dependencies fail, the stage end is not logged. This tricks the build
metrics into thinking nothing happened.
This commit properly logs the process stage end if a dependent build
failed.
> Log process stage end for enqueued/waiting for dependencies

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
When we set the initial states for the build task, both for internal and
logging purposes, the log context is not set properly. This commit
attempts to fix this.
Currently this is what happens:
The logs from Kibana indicates that different builds were logged with the same processContext.
CC: @matedo1
> [v1.8] Add log context when setting waiting for dep/enqueued

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
This caused us to accidentally delete the MDC context on method calls.
Only the essential ones are used now.
> [NCL-5520] Remove too many MDCUtils.clear()

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
Once a build is done, PNC scans for builds that depend on the completed
build and triggers its lambda.
The issue is that the lambda sets an MDC value for the waiting build,
but doesn't reset it back to the old MDC values for the done build. This
causes the subsequent logs to be printed with the waiting build instead
of the done build.
This commit fixes it.
> [v1.8][NCL-5520] Reset the MDC value after waiting task run

- facade/src/main/java/org/jboss/pnc/facade/impl/BuildTriggererImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/GenericSettingEndpointImpl.java
GenericSettingProvider in facade/src/main/java/org/jboss/pnc/facade/providers/ declared package org.jboss.pnc.rest.provider which is obviously wrong. Eclipse refused to compile the class.
> Fix package of moved GenericSettingProvider

- bpm/src/main/java/org/jboss/pnc/bpm/BpmEventType.java
- bpm/src/main/java/org/jboss/pnc/bpm/model/RepositoryCloneSuccess.java
- bpm/src/main/java/org/jboss/pnc/bpm/model/RepositoryCreationDataWrapper.java
- facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
- rest/src/main/java/org/jboss/pnc/rest/endpoint/BpmEndpoint.java
- rest/src/test/java/org/jboss/pnc/rest/endpoint/BpmEndpointTest.java
Instead of BPM creating the scm repository as part of its process, BPM
should now only report the internal url in its success notification.
From there on, PNC-Orch will use the internal url to create the scm
repository in its database.
This should simplify the BPM process for repository configuration.
> [NCL-5490] Create scm repository from bpm notification

- ui/app/build-configs/directives/pnc-create-build-config-wizard/pnc-create-build-config-wizard.html
- ui/app/build-configs/directives/pnc-select-build-parameters/pncDisplayBuildParameters.js
- ui/app/build-configs/directives/pnc-select-build-parameters/pncSelectBuildParameters.js
- ui/app/common/pnc-client/resources/BuildConfigResource.js
If the user comes back in the build configuration process and changes buildType, the parameters he added will be overridden. It could be done better if the new ones would stay but I don't know if this feature is so important to be included.
> Propagating default ALIGNMENT_PARAMETERS into build configuration wizard

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
- build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/SkippingBuiltConfigsTest.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/repository/RepositoryMock.java
InGroupDependentBuildsTest.shouldCreateTaskForDependentBuilt
There were 2 running conditions:
1. concurrent modification of mocked BuildRecordRepository (circa 1/100 probability)
- repository was returning direct reference to the data collection
- a method looping through the collection (in a stream) had the collection modified in the middle of loop resulting in a ConcurrentModificationException thrown from the inside of the Collection
- tried to wrap the collection in a new array so it wouldn't have direct reference but it caused some failures so I've decided to change the collection implementation to CopyOnWriteArray which is thread-safe (I haven't seen noticeable performance overhead)
2. successful BuildTask failing to notify dependant BuildTasks (circa 1/400 probability)
- the …
> [NCL-5597] fix running conditions in BuildCoordinator's tests

- termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java
- termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriverTest.java
@matejonnet You probably know why there was a thread sleep. After BuildAgent reports that the build is RUNNING we should be able to immediately call cancel. 
The script executed in the test by BuildAgent always fails (it tried to execute "git clone null"). This test tries to cancel it before BuildAgent reports the execution as failed. There is a running condition where mostly cancellation wins(98/100). The sleep there is contra-productive as it gives BuildAgent more time to report failing execution. 
I've deleted a thread sleep so that is calls cancel earlier. It didn't solve the issue but it made the test more stable. 
Statistics: 
- with sleep: 31 tests failed out of 2000 
- without sleep: 2 tests failed out of 2000
Is there an additional reason for the Thread.sleep? I for sure could've …
> [NCL-5596] improve stability of TermBuildDriver cancelling test

- datastore/src/main/resources/META-INF/persistence.xml
- model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
As the other side of the relation is not cached
> [v1.8] NCL-5686 - Remove cache on collections related to BuildConfigurations dependencies

- build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/CancelledBuildTest.java
- build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/ProjectBuilder.java
- constants/src/main/java/org/jboss/pnc/enums/BuildCoordinationStatus.java
- constants/src/main/java/org/jboss/pnc/enums/BuildStatus.java
> [NCL-5507] fix WS messages not having set startTime when reporting BUILDING BuildTasks

- auth/src/main/java/org/jboss/pnc/auth/DefaultKeycloakServiceClient.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java
The logic for the `refreshRequired` method in
`DefaultKeycloakServiceClient` is the reverse of what it should be
returning.
It should be:
- If the token is expiring *before* now + the max duration of the build,
then we need to renew
It seems to have accidentally gone unnoticed for many years because
builds happening frequently (in less than 1 hour of each other)
accidentally renews the token. This is generally the case in Production
orch but not the case in Stage.
Furthermore if we redeploy our Devel environment after every commit
(which happens frequently), this tends to hide the issue.
The default for 'serviceTokenRefreshIfExpiresInSeconds' is also changed
from 1 hour to 24 hours to reflect the max allowed time for a build to
happen.
> [v1.8][NCLSUP-40] Fix logic for keycloak `refreshRequired`

- auth/src/main/java/org/jboss/pnc/auth/DefaultKeycloakServiceClient.java
- moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java
The logic for the `refreshRequired` method in
`DefaultKeycloakServiceClient` is the reverse of what it should be
returning.
It should be:
- If the token is expiring *before* now + the max duration of the build,
then we need to renew
It seems to have accidentally gone unnoticed for many years because
builds happening frequently (in less than 1 hour of each other)
accidentally renews the token. This is generally the case in Production
orch but not the case in Stage.
Furthermore if we redeploy our Devel environment after every commit
(which happens frequently), this tends to hide the issue.
The default for 'serviceTokenRefreshIfExpiresInSeconds' is also changed
from 1 hour to 24 hours to reflect the max allowed time for a build to
happen.
> [NCLSUP-40] Fix logic for keycloak `refreshRequired`

- bpm/src/test/java/org/jboss/pnc/bpm/test/BuildResultSerializationTest.java
- bpm/src/test/java/org/jboss/pnc/bpm/test/RepositoryManagerResultSerializationTest.java
- datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
- datastore/src/main/java/org/jboss/pnc/datastore/repositories/ArtifactAuditedRepositoryImpl.java
- datastore/src/main/java/org/jboss/pnc/datastore/repositories/ArtifactRepositoryImpl.java
- demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
- dto/src/main/java/org/jboss/pnc/dto/Artifact.java
- dto/src/main/java/org/jboss/pnc/dto/ArtifactRef.java
- dto/src/main/java/org/jboss/pnc/dto/ArtifactRevision.java
- dto/src/main/java/org/jboss/pnc/dto/ArtifactRevisionRef.java
- facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
- facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java
- facade/src/test/java/org/jboss/pnc/facade/providers/ArtifactProviderTest.java
- integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ArtifactEndpointTest.java
- mapper/src/main/java/org/jboss/pnc/mapper/AbstractArtifactMapper.java
- mapper/src/main/java/org/jboss/pnc/mapper/api/ArtifactRevisionMapper.java
- model/src/main/java/org/jboss/pnc/model/Artifact.java
- model/src/main/java/org/jboss/pnc/model/ArtifactAudited.java
- model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java
- rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ArtifactAuditedRepository.java
Created a new ArtifactAudited table, to watch and record changes related to the ArtifactQuality related fields. Added new fields to record the creationTime, creationUser, modificationTime and modificationUser, and the reason why an ArtifactQuality has changed.
> [NCL-5680] - Update the model related to Artifacts and revision of quality levels change

- dto/src/main/java/org/jboss/pnc/dto/notification/SCMRepositoryCreationSuccess.java
- rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedSCMRepositoryClient.java
- rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java
- rest-client/src/main/java/org/jboss/pnc/restclient/websocket/predicates/SCMRepositoryNotificationPredicates.java
This will handle websocket notifications for both success and failures
of scm creation
> Add AdvancedSCMRepositoryClient for websocket notifications

- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
When deciding whether to only search for temp builds, or to include
permanent builds during implicit dependency check, we need to search for
*successful* temporary builds.
If only the search for *successful* temporary builds is empty, should we
consider permanent builds only.
If the extra successful check is not added, we'll also consider the not successful builds, which is not ok.
> [v1.8.1][NCLSUP-82] Search for temp, successful builds

- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
When deciding whether to only search for temp builds, or to include
permanent builds during implicit dependency check, we need to search for
successful temporary builds.
If only the search for successful temporary builds is empty, should we
consider permanent builds only.
If the extra successful check is not added, we'll also consider the not
successful builds, which is not ok.
> [NCLSUP-82] Search for temp, successful builds

- pom.xml
- rest-api/pom.xml
Bump versions:
- jboss-eap-jakartaee8 from 7.3.0 to 7.3.1
- swagger-maven-plguin from 2.1.2 to 2.1.3
- wiremock-jre8 from 2.26.3 to 2.27.1
- rest-assured from 4.3.0 to 4.3.1
- snakeyaml from 1.24 to 1.26
> Bump versions: jakartaee8

- rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java
- rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildConfigurationClient.java
- rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedGroupConfigurationClient.java
In some cases, we can use the Advanced* clients without having to use
any websocket listener. In those cases, the websocket client is never
closed / disconnected and the vertx event loop runs forever in the
background, causing the application to never exit properly.
This commit adapts the try-with-resources (AutoCloseable) feature in
those clients so that the websocket clients are properly closed once we
are done with them.
> [NCL-5895] Auto-close vertx websocket for the advanced clients

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
> [NCL-6066] WARNING instead of ERROR when retring to create BuildEnv

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java
The check was wrong because it checked wrong repo in the group. We
can remove the check as the TODO said because all builds are now
in consolidated repository.
> [NCL-5922] Remove wrong check when deleting builds from indy

- model/src/main/java/org/jboss/pnc/model/ArtifactAudited.java
- model/src/main/java/org/jboss/pnc/model/BuildConfigurationAudited.java
- model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java
- model/src/main/java/org/jboss/pnc/model/BuildRecordAttribute.java
- model/src/main/java/org/jboss/pnc/model/IdRev.java
- model/src/main/java/org/jboss/pnc/model/TargetRepository.java
- model/src/main/java/org/jboss/pnc/model/User.java
When a proxy is loaded, the data is not stored in thr proxy object, but in the
“target” object. The fields in the proxy object will remain null forever (or any
value that they have been initialized with), since all methods invoked on the
proxy will be delegated to the target object. [1]
[1]: https://xebia.com/blog/advanced-hibernate-proxy-pitfalls/
> [NCL-5812] Make sure LazyLoading Proxy is used when accesing fields

- bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationRest.java
- bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationWithCallbackRest.java
- bpm/src/main/java/org/jboss/pnc/bpm/task/BpmBuildTask.java
- bpm/src/test/java/org/jboss/pnc/bpm/test/BuildExecutionConfigurationTest.java
- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/local/LocalBuildScheduler.java
- build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionConfiguration.java
- build-executor/src/test/java/org/jboss/pnc/executor/BuildEnvironmentTest.java
- build-executor/src/test/java/org/jboss/pnc/executor/BuildExecutionBase.java
- dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRevision.java
- dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRevisionRef.java
- indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/fixture/TestBuildExecution.java
- integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildTaskEndpointTest.java
- model/src/main/java/org/jboss/pnc/model/BuildConfigurationAudited.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/executor/BuildExecutionConfigurationMock.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/spi/BuildExecutionConfigurationMock.java
- spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionConfiguration.java
- spi/src/main/java/org/jboss/pnc/spi/repositorymanager/BuildExecution.java
BEC = BuildExecutionConfiguration
We use BEC as our DTO (or one of) to submit build requests to Maitai.
Adding `brewPullActive` there created this chain of other objects that
needed to be adjusted to propagate that value. If you're asking
yourself: "Why did he change that object?", it's because I had to
propagate it, otherwise the compiler gets upset at me.
> [NCL-6165] Propagate the brewPullActive DTO to BEC

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
This PR fixes an issue where the internal url may not be properly
constructed at the beginning of the
`OpenshiftStartedEnvironment::monitorInitialization` method. When the
method is called, we don't know yet if the service object has been
created with a proper cluster IP yet. The url might look like this in
those cases: 'http:/pnc-ba-1234/', which strangely the 'URL' object
doesn't complain.
This PR tries to get the latest internal url everytime it checks if
the internal url is online.
This PR also sets a read timeout of 2 seconds so that we do not wait
forever for data to be sent back.
The `isBuildAgentFuture` completablefuture checks whether the internal
url of the service can be used to talk to the build agent server. This
establishes the readiness of the pod. The same url is used …
> [NCLSUP-217] Improvements to internal url check for builder pod creation

- common/src/main/java/org/jboss/pnc/common/util/CompletableFutureUtils.java
- common/src/test/java/org/jboss/pnc/common/util/CompletableFutureUtilsTest.java
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
This method terminates early if any of the futures fail, as opposed to
CompletableFuture's `allOf`, which waits for all futures to complete
before signalling one of them completed exceptionally.
However, `allOfOrException` will wait for all the futures to complete if
all of them are completed successfully.
Tests are also written to verify the functionality.
> Move allOfOrException to its own utils class

- rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java
Error handling enhancement. When a build trigger failed because of a
conflicting build already running, it got thrown as a RuntimeException.
Switched that to AlreadyRunningException with conflicting task ID as
the response object.
> Return relevant error in case of BuildConflictException

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
In OCP 4.6, this call is authenticated and will fail when we call that
method using the current client. The client calls that method
unauthenticated, which is fine on OCP 3.11 but fails on OCP 4.6 due to
the new authentication requirement.
Let's remove it.
> Remove ocp client getServerReadyStatus call

- facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
- integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
> [NCL-6340] Make '!' operator available in buildConfigName filtering

- openshift-environment-driver/pom.xml
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
- openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java
- pom.xml
This is done to support the latest version of OCP 4.6, which
unfortunately the version we used for openshift-restclient-java does not
support anymore. Since the latter is also deprecated and fabric8 is the
recommended library, let's use this instead
> Migrate to fabric8 client instead of openshift-restclient-java

- openshift-environment-driver/pom.xml
- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
- openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftEnvironmentDriverRemoteTest.java
- pom.xml
This is done to support the latest version of OCP 4.6, which
unfortunately the version we used for openshift-restclient-java does not
support anymore. Since the latter is also deprecated and fabric8 is the
recommended library, let's use this instead
> [v2.0] Migrate to fabric8 client instead of openshift-restclient-java

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
Without the change, the original check for isInternalServletAvailable throws an NPE which is not caught and makes the first builder pod created to be marked as broken. A second builder pod is then created. This commit fixes this so that we can use the first builder pod.
> [v2.0] getInternalEndpointUrl might return null if service not ready

- openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
Without the change, the original check for isInternalServletAvailable throws an NPE which is not caught and makes the first builder pod created to be marked as broken. A second builder pod is then created. This commit fixes this so that we can use the first builder pod.
> getInternalEndpointUrl might return null if service not ready

- common/src/main/java/org/jboss/pnc/common/util/UrlUtils.java
- common/src/test/java/org/jboss/pnc/common/test/util/UrlUtilsTest.java
This helper method replaces the host in a particular url with a new
host (including the new scheme and port). The new host is in the format:
- `<scheme>://<host>[:<port>]`
where 'port' is optional
If the default ports for http / https are used, then the port
information is omitted.
> [NCL-6456] Add helper method replaceHostInUrl

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
- common/src/main/java/org/jboss/pnc/common/util/Quicksort.java
- common/src/test/java/org/jboss/pnc/common/util/QuicksortTest.java
The comparison between tasks to put dependants at the beginning is
unfortunately not stable since it allows this scenario:
If task1 depends on task2, and task3 doesn't depend on any tasks, then
this comparator allows for this:
- task1 = task3
- task2 = task3
- task1 < task3
If both task1 and task2 = task3, it would infer that task1 = task3.
Alas, this is not the case for this comparison and it makes Java's
default sort implementation upset (Error is: Comparison method violates
its general contract!)
This commit implements our own Quicksort algorithm that *doesn't* check
if the comparator is stable and sorts the list.
> [NCLSUP-393] Use own sort implementation for tasks

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
- common/src/main/java/org/jboss/pnc/common/util/Quicksort.java
- common/src/test/java/org/jboss/pnc/common/util/QuicksortTest.java
The comparison between tasks to put dependants at the beginning is
unfortunately not stable since it allows this scenario:
If task1 depends on task2, and task3 doesn't depend on any tasks, then
this comparator allows for this:
- task1 = task3
- task2 = task3
- task1 < task3
If both task1 and task2 = task3, it would infer that task1 = task3.
Alas, this is not the case for this comparison and it makes Java's
default sort implementation upset (Error is: Comparison method violates
its general contract!)
This commit implements our own Quicksort algorithm that *doesn't* check
if the comparator is stable and sorts the list.
> [v2.1][NCLSUP-393] Use own sort implementation for tasks

- datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/repository/RepositoryMock.java
When the /build-task/<ID>/complete endpoit is called multiple times at
the seme time, it lead to race condition in the
DatastoreAdapter.storeResult and DefaultDatastore.storeCompletedBuild
methods.
The first invocation of storeCompletedBuild could successfully store
the artifacts and build, which lead to conflicts in the simultaneous
calls to that method. These conflicts resulted in exception catched in
storeResult which was handled by marking the build as SYSTEM-ERROR and
trying to save the failed build again. This now overwrote* the first
correctly saved build with the failed build.
* We use Spring CrudRepository.save method which calls em.merge if the
entity already is in DB.
> [NCL-6861] Don't overwrite existing Build when saving it

- facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/api/SCMRepositoryProvider.java
On creation of a build configuration, PNC:
1. creates a repository configuration (via RHPAM)
2. creates the build configuration with the repository configuration info
In step 1, the external scm repository is synced to the internal scm repository.
If a revision is specified, then we should only sync that revision. This
is already implemented in Repour, but the revision information is not
being sent to Repour.
To do so, we need to pass the information of the revision from PNC to
RHPAM. This commit is the implementation of this.
> [NCLSUP-507] Send revision info to RHPAM when creating build config

- facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
- facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
Handle the % wildcard as received from the UI
> [NCL-6965] - Fix running builds search by BuildConfigName

- datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/BuildRecordSpringRepository.java
The updated query has a significant speedup compared to the JPA one for build configs with a lot of builds.
Whereas the previous query took 40 seconds in the worst case scenario, the new query takes 0.02 seconds.
However, we need to use the native query option since it is hard to translate what we want to achieve in JPASQL
> Update the query for getLatestBuildsWithConfigIds

- auth/pom.xml
- build-coordinator/pom.xml
- datastore/pom.xml
- datastore/src/main/java/org/jboss/pnc/datastore/limits/CursoredPageRequest.java
- datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/AbstractRepository.java
- datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/PageableMapper.java
- dto/pom.xml
- integration-test/pom.xml
- model/pom.xml
- moduleconfig/pom.xml
- pom.xml
- remote-build-coordinator/pom.xml
- remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/MockBuildScheduler.java
- rest-client/pom.xml
- rest/pom.xml
Summary (I may have missed some dependency changes):
changed: 
rh-sso-adapter: 7.4.0.GA -> 7.4.8.GA
keycloak: 9.0.3.redhat-00002 -> 9.0.14.redhat-00001
byte-buddy: 1.10.18 -> 1.10.20
hsqldb: 2.4.1-jdk8 -> 2.7.1-jdk11
spring-data-jpa 1.11.23.RELEASE -> 2.3.9.RELEASE
spring-data-commons 1.13.23.RELEASE -> 2.3.9.RELEASE
fluent-hc: 4.5.4-> 4.5.14
vertx: 3.8.5 -> 3.9.14
swagger2: 2.1.4 -> 2.2.8
gav-changed:
com.github.fge:json-patch:1.9 -> com.github.java-json-tools:1.13
removed:
jbpm-test: 6.2.0
jackson-xc
jcip-annotations: 1.0.0.redhat-8
jsch:
jsoup:1.8.3
packageurl-java:
awaitility: 4.2.0
snakeyaml: 1.27
org.glassfish.web:javax.el: 2.2.6
net.joday:failsafe: 2.4.0
io.fabric8:openshift-client: 5.0.1
indy-model-core-java
indy-embedder
indy-client-core-java
indy-text-fixtures-core …
> [NCL-7381] get rid of CVEs 

- facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildRSQLMapper.java
We don'T know how to use current framework with data from audited
enitity. Environment is unused deprecated field in Build Record, we take
the data for REST from BCAudited
> Explicitly disallow RSQL on BCAudited data in Build

- datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
- datastore/src/main/java/org/jboss/pnc/datastore/repositories/ArtifactRepositoryImpl.java
- datastore/src/test/java/org/jboss/pnc/datastore/DatastoreTest.java
- pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ArtifactRepositoryMock.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ArtifactRepository.java
Current implementation in one case   took over 30 s for 387 checksums and returned 217548 artifacts. This implementation returns only 387 artifacts and seems to be faster (can't tell exaclty how, because the DB was warmed up, butt it's still at least 1 second).
> [NCLSUP-864] Optimize withIdentifierAndSha256 artifact search

- .github/PULL_REQUEST_TEMPLATE.md
We do not use the changelog here for a long time already
> Remove changelog mention from PR tempate

- rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
Swagger can't deal with duplicate class names (like Build in 3 different classes), so switiching to FQN should fix the openapi
> [NCL-7933] Use FQN for swagger class names

- model/src/main/resources/db-update/20050-from-2.4.0-to-2.5.0.sql
- model/src/main/resources/db-update/20060-from-2.5.0-to-2.6.0.sql
The change from int to long in the BuildConfigSetRecord wasn't backproted in 2.5.x and should therefore only be run for the 2.6.0 migration.
> Schema update for BuildConfigSetRecord

- datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java
We noticed a StackOverflow error for builds which have a huge list of dependencies (> 7800).
We generate our query to search for artifacts by generating a statement that is of nature:
```
SELECT *
FROM artifacts
WHERE (identifier = <identifier1> AND sha256 = <sha2561>) OR
(identifier = <identifier2> AND sha256 = <sha2562>) OR
...
(identifier = <identifierN> AND sha256 = <sha256N>);
```
Hibernate struggles to generate that query for more than 7800 artifacts (I don't really know the real number) since it is using recursion to generate that query and we eventually hit the StackOverflow error.
We try to workaround the issue by partitioning the artifacts we query at once to QUERY_ARTIFACT_PARITION_SIZE (set to 1000, since we know it'll succeed with those sizes). This avoids the StackOverflow …
> [NCLSUP-912] Partition artifact query to avoid stackoverflow

- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java
When IN is empty, we get syntax error at or near ")"
> Fix: empty IN in SQL throws syntax error

- dto/pom.xml
- dto/src/main/java/org/jboss/pnc/dto/AlignmentStrategy.java
- dto/src/main/java/org/jboss/pnc/dto/ArtifactRef.java
- dto/src/main/java/org/jboss/pnc/dto/ArtifactRevisionRef.java
- dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRef.java
- dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRevisionRef.java
- dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationWithLatestBuild.java
- dto/src/main/java/org/jboss/pnc/dto/BuildPushResultRef.java
- dto/src/main/java/org/jboss/pnc/dto/BuildRef.java
- dto/src/main/java/org/jboss/pnc/dto/Environment.java
- dto/src/main/java/org/jboss/pnc/dto/GroupBuildRef.java
- dto/src/main/java/org/jboss/pnc/dto/GroupConfigurationRef.java
- dto/src/main/java/org/jboss/pnc/dto/OperationRef.java
- dto/src/main/java/org/jboss/pnc/dto/ProductMilestoneCloseResultRef.java
- dto/src/main/java/org/jboss/pnc/dto/ProductMilestoneRef.java
- dto/src/main/java/org/jboss/pnc/dto/ProductRef.java
- dto/src/main/java/org/jboss/pnc/dto/ProductReleaseRef.java
- dto/src/main/java/org/jboss/pnc/dto/ProductVersionRef.java
- dto/src/main/java/org/jboss/pnc/dto/ProjectRef.java
- dto/src/main/java/org/jboss/pnc/dto/SCMRepository.java
- dto/src/main/java/org/jboss/pnc/dto/TargetRepository.java
- dto/src/main/java/org/jboss/pnc/dto/User.java
- dto/src/test/java/org/jboss/pnc/dto/UserTest.java
- pom.xml
This is done to prevent any XSS attacks in the PNC-UI, even though the PNC-UI (Angular and React based) already have safety mechanisms to prevent it.
For some scenarios where HTML tags might make sense in the string (like for the build script), there are no `@NoHtml` annotation.
> [PSX-303] Add @NoHtml validations on string DTOs

- bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java
This isn't needed anymore since BPM will use its own service account
> [NCL-8048] Omit the auth in the request for BPM

- facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
- facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
- facade/src/main/java/org/jboss/pnc/facade/impl/OperationsManagerImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
- facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
We need to stop using the user token to send other requests to other services.
Instead we'll use our service account.
This is done because we do not know when the user token will expire and should therefore use a service account token that we can control and renew.
Moreover, the user token may not have the appropriate roles to submit requests to other applications.
> [NCL-8047] Stop using user token for other requests

- integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java
The test had a few issues:
- we were comparing the parent build configuration's modification time
with the dependency modification time
- we weren't updating the 'updatedDependency' object after it was
modified
>  Fix BuildTest::dontRebuildTemporaryBuildWhenThereIsNewerPersistentOnSameRev

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
- remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/DatastoreAdapter.java
Do not report cancelled builds as ERROR in userLog.
> [NCL-7279] Stop logging cancelled builds as ERROR

- datastore/src/main/java/org/jboss/pnc/datastore/limits/rsql/EmptySortInfo.java
- datastore/src/main/java/org/jboss/pnc/datastore/limits/rsql/StableEmptySortInfo.java
- facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java
- integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
- integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildPushTest.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/SortInfo.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/impl/DefaultSortInfo.java
@janinko As more than one endpoint uses `getBuildList(...)` method, the default sort change from `ID asc` to `submitTime desc, ID desc` will also affect default sorting on these endpoints:
- **GET /product-milestones/{{id}}/builds**
- **GET /projects/{{id}}/builds**
- **GET /build-configs/{{id}}/builds**
- **GET /users/{{id}}/builds**
- **GET /group-builds/{{id}}/builds**
- **GET /group-configs/{{id}}/builds**
> [NCL-8156] achieve determinism for build endpoints

- facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
During sustaining, I've found an issue when Orch was creating extra TargetRepositories without ending slash (apparently all should have an ending slash) after DeliverableAnalyzer finishes. 
I am not familiar with the code but I think this should fix it.
Additionally, I think this should be backported to 2.6.X branch.
> [NCLSUP-988] fix creation of extra TRs during del-analysis

- facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
- facade/src/main/java/org/jboss/pnc/facade/providers/GroupBuildProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/OperationProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/TargetRepositoryProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/api/UserRoles.java
- integration-test-rex/src/test/resources/WEB-INF/web.xml
- integration-test/pom.xml
- integration-test/src/test/resources/WEB-INF/web.xml
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/EnvironmentEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/OperationEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/TargetRepositoryEndpoint.java
- rest/src/main/webconfig/auth/web.xml
The roles are:
- pnc-users-artifact-admin: can do any actions with artifact endpoint
- pnc-users-build-admin: can do any actions with build enpodint
- pnc-users-build-delete: can delete temporary builds only
- pnc-users-environment-admin: can do any actions with environment endpoint
- pnc-users-admin: pnc human admins
> [NCL-8152] Use fine-grained roles for PNC endpoints

- facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
- facade/src/main/java/org/jboss/pnc/facade/providers/GroupBuildProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/OperationProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/TargetRepositoryProviderImpl.java
- facade/src/main/java/org/jboss/pnc/facade/providers/api/UserRoles.java
- integration-test/pom.xml
- integration-test/src/test/resources/WEB-INF/web.xml
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/EnvironmentEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/OperationEndpoint.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/TargetRepositoryEndpoint.java
- rest/src/main/webconfig/auth/web.xml
The roles are:
- pnc-users-artifact-admin: can do any actions with artifact endpoint
- pnc-users-build-admin: can do any actions with build enpodint
- pnc-users-build-delete: can delete temporary builds only
- pnc-users-environment-admin: can do any actions with environment endpoint
- pnc-users-admin: pnc human admins
> [v2.6.x][NCL-8152] Use fine-grained roles for PNC endpoints

- rest/src/main/java/org/jboss/pnc/rest/SecurityConstraintFilter.java
Thanks to @michalovan for pointing this out!
HEAD requests will erturn HTTP headers from the server as if the document was requested using the HTTP GET method [1]
Since we don't require authentication in this filter for GET requests, we shouldn't also require authentication for HEAD requests.
[1]: https://reqbin.com/Article/HttpHead
> Remove requirement to be authenticated for HEAD requests

- facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
- integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
- integration-test/src/test/resources/pnc-config.json
This refers to updates on the BuildConfiguration entity.
Pre-amble
---------
The flow when creating a new entity in PNC is:
```
Endpoint#createNew -> EndpointHelper#create ->
Provider#store -> Repository#save
```
For updating an entity, we typically just obtain the entity from the DB and update the field. The `Repository#save` method is not called.
The logic to set the `BuildConfiguration`'s default alignment parameters based on the build type is in `BuildConfigurationRepositoryImpl#save`.
Issue
-----
However, since the `save` method is only called for creating new entities but not for updates, the logic to set the default alignment parameters (and global align strategies) is not called for updates.
Fix
---
The fix is to add the logic to set the proper default alignment parameters on …
> [NCL-6729] Update defaultAlignmentParam on BuildType change

- facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
- integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
- integration-test/src/test/resources/pnc-config.json
This refers to updates on the BuildConfiguration entity.
Pre-amble
---------
The flow when creating a new entity in PNC is:
```
Endpoint#createNew -> EndpointHelper#create ->
Provider#store -> Repository#save
```
For updating an entity, we typically just obtain the entity from the DB and update the field. The `Repository#save` method is not called.
The logic to set the `BuildConfiguration`'s default alignment parameters based on the build type is in `BuildConfigurationRepositoryImpl#save`.
Issue
-----
However, since the `save` method is only called for creating new entities but not for updates, the logic to set the default alignment parameters (and global align strategies) is not called for updates.
Fix
---
The fix is to add the logic to set the proper default alignment parameters on …
> [v2.6][NCL-6729] Update defaultAlignmentParam on BuildType change

- model/src/main/java/org/jboss/pnc/model/User.java
- spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/UserPredicates.java
We use several account like `service-account-pnc-one` and `service-account-pnc-two` which all use the same email e.g. `pnc-service@example.com`.
Alternatively, we could use accounts with emails like `pnc-service+one@example.com` and `pnc-service+two@example.com`, but that would mean changing bunch of accounts.
> Drop unique constrain on User's email

- common/src/main/java/org/jboss/pnc/common/util/TimeUtils.java
- common/src/test/java/org/jboss/pnc/common/util/TimeUtilsTest.java
In TimeUtils.getDateXDaysAgo, there's a bug where a big int number is multiplied by another number. The final int overflows if the "other number" is greater than 21 and the getDateXDaysAgo returns a wrong date.
This commit fixes this.
> Fix integer overflow error in TimeUtils

- common/src/main/java/org/jboss/pnc/common/util/TimeUtils.java
- common/src/test/java/org/jboss/pnc/common/util/TimeUtilsTest.java
In TimeUtils.getDateXDaysAgo, there's a bug where a big int number is multiplied by another number. The final int overflows if the "other number" is greater than 21 and the getDateXDaysAgo returns a wrong date.
This commit fixes this.
> [v2.7] Fix integer overflow error in TimeUtils

- model/src/main/java/org/jboss/pnc/model/BuildRecord.java
FetchMode.SUBSELECT causes the subselect to read whole table, because it doesn't use LIMIT
> Use BatchSize instead of FetchMode

- processor/src/main/java/org/jboss/pnc/processor/ClientGenerator.java
- rest-api/src/main/java/org/jboss/pnc/client/BearerAuthentication.java
- rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java
- rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java
Use the tokenSupplier to get a token for the PNC REST client on every request. The advantage is that the token supplier has the ability to refresh the token before it expires.
The old method relied on using a hardcoded token string, which will expire if the request takes more than 5 minutes and everything fails afterwards.
The old "hardcoded token string" method is still supported but now deprecated.
> [NCL-8487] Use the tokenSupplier to get token

- common/src/main/java/org/jboss/pnc/common/net/GitSCPUrl.java
- common/src/main/java/org/jboss/pnc/common/util/UrlUtils.java
- common/src/test/java/org/jboss/pnc/common/net/GitSCPUrlTest.java
Improve GitSCPUrl parsing
=========================
This is done by adapting the regex for GitSCPUrl to satisfy the naming requirements for Gitlab.
Improve error message
=====================
If there was an error with the internal repository url, and it was in SCP format, the error message on the UI would say:
```
Supplied URL:http://git@gitlab:work/owner1/repo.git is neither regular URI nor in Git SCP-style format.""
```
Instead, this is changed to show the original url in scp-style:
```
Supplied URL:git@gitlab:work/owner1/repo.git is neither regular URI nor in Git SCP-style format.""
```
> Improve GitSCPUrl parsing and error message

- common/src/main/java/org/jboss/pnc/common/net/GitSCPUrl.java
- common/src/main/java/org/jboss/pnc/common/util/UrlUtils.java
- common/src/test/java/org/jboss/pnc/common/net/GitSCPUrlTest.java
Improve GitSCPUrl parsing
=========================
This is done by adapting the regex for GitSCPUrl to satisfy the naming requirements for Gitlab.
Improve error message
=====================
If there was an error with the internal repository url, and it was in SCP format, the error message on the UI would say:
```
Supplied URL:http://git@gitlab:work/owner1/repo.git is neither regular URI nor in Git SCP-style format.""
```
Instead, this is changed to show the original url in scp-style:
```
Supplied URL:git@gitlab:work/owner1/repo.git is neither regular URI nor in Git SCP-style format.""
```
> [v2.7] Improve GitSCPUrl parsing and error message

- facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
This is run in async code and executed with BPM's system user, so calling UserService is both wrong and broken.
> Reuse operation's user when storing scratch Deliverables Analysis

- remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/maintenance/DefaultRemoteBuildsCleaner.java
- remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/maintenance/IndyFactory.java
BuildCleaner couldn't delete temporary builds properly since PNC 3.0.x deployment in prod. This is caused because the delete endpoint in PNC would eventually get stuck after some time and not delete anything.
Background
==========
In PNC 2.7.6 and prior, we requested a fresh Indy client object to delete stuff in Indy, as part of the temporary build cleanup. The Indy client object came with its own connection pool
([proof](https://github.com/project-ncl/pnc/blob/7228e8d2af6a6da4bcf23f5c7496dea125c43dab/build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java#L144)).
In PNC 3.0.x, we wanted to reuse the same Indy client object for delete requests so that we can reuse the same connection pool, saving both garbage collection and object/connection …
> [NCLSUP-1175] Fix temporary build cleanup

- dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java
We were picking it from buildConfigurationAudited and that didn't go well.
> Dingrogu integration: pickup buildType from buildconfiguration

- facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
- pom.xml
> Add support for Windows artifacts to Deliverables Analyzer

- build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java
- build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/IndyFactory.java
- pom.xml
- remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/maintenance/DefaultRemoteBuildsCleaner.java
- remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/maintenance/IndyFactory.java
- rest-api/pnc-openapi.json
- rest-api/pnc-openapi.yaml
Commit: https://github.com/project-ncl/pnc/commit/581505d822483a4d1ec1dc89375bcb53d36c2a5b
We had to previously revert the change in remote builds cleaner to use a
shared Indy object for deletion of temporary builds.
On paper, the shared Indy object makes a lot of sense since we can
re-use the underlying threadpool for http requests. In practice, the
resource in the thread pool wasn't cleaned up properly and stayed in the
pool. This eventually caused all the threads in the threadpool to be
unavailable and cause further deletions to hang.
We workaround it by switching back to creating an Indy object for every
request.
This is all fixed now in Indy client 3.4.1, so this commit removes the
workaround.
> [NCLSUP-1175] Revert temporary build cleanup commit

- demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
- facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/DeliverableArtifactRSQLMapper.java
- integration-test/src/test/java/org/jboss/pnc/integration/endpoints/DeliverableAnalyzerReportEndpointTest.java
This change was made to make the name consistent with DTO field, not model field
> Rename brewBuildId -> brewId in delAn RSQL Mapper

- integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
- rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
- rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
BREAKING CHANGE! Breaks java client API. REST API is unbroken. Sadly we can't use default methods as they are unsupported and having two implementations of the same endpoint make RestEasy chose one at random.
> Remove old closeMilestone method from milestone endpoint

- model/src/main/java/org/jboss/pnc/model/DeliverableArtifact.java
- model/src/test/java/org/jboss/pnc/model/DeliverableArtifactTest.java
A `DeliverableAnalyzerReport` (or a deliverable analysis run) may contain one or more distribution urls, which are urls to zips that we distribute to customers.
A particular artifact can be found in many of those distribution urls. The `DeliverableAnalyzerReport` stores those artifact information (`DeliverableArtifact`) inside a set.
Unfortunately `DeliverableArtifact` equals and hashCode method does not take into account the distribution during comparison. This causes additions into the `DeliverableAnalyzerReport` artifact set to *not* add a second `DeliverableArtifact` which has the same artifact and report, but different distribution urls. The set thinks it's a duplicate entry.
This commit fixes it by considering the distribution in the comparison. A unit test is added to make sure we …
> [NCL-9215] Fix equality/hash comparison for DeliverableArtifact

- model/src/main/java/org/jboss/pnc/model/DeliverableArtifact.java
- rest-api/pnc-openapi.json
- rest-api/pnc-openapi.yaml
This is done to avoid the N+1 problem when loading licenses for the list of deliverable artifacts that we fetched.
> [NCLSUP-1265] Load the licenses in batch size of 50

- model/src/main/java/org/jboss/pnc/model/Artifact.java
This will be useful when loading a list of artifacts. We need to make the ManyToOne lazy to be able to use the BatchSize optimization.
We cannot really use the Join Fetch optimization because of our use of pagination and max result size.
> Artifact: Make ManyToOne lazy and batch loaded
