project-ncl/pnc

ui/app/build-configs/directives/pnc-create-build-config-product-version-form/pnc-create-build-config-product-version-form.html
ui/app/build-configs/directives/pnc-create-build-config-product-version-form/pncCreateBuildConfigProductVersionForm.js
ui/app/build-configs/directives/pnc-create-build-config-wizard/pnc-create-build-config-wizard.html
ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js
ui/app/build-configs/directives/pnc-create-build-config-wizard/review-product-version.html
ui/app/common/components/pnc-product-combobox/pncProductCombobox.js
ui/app/common/components/pnc-product-version-combobox/pnc-product-version-combobox.html
ui/app/common/components/pnc-product-version-combobox/pncProductVersionCombobox.js
ui/app/common/pnc-client/resources/ProductVersionResource.js

[NCL-5671]New 2 step process for product versions in new build-config wizard

---

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/SCMRepositoryEndpointImpl.java

[NCL-5792] Set the content-type for scm's create-and-sync

---

pom.xml

Update byte-buddy to 1.10.11

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

This commit refactors the private method names used in `create-and-sync`
to make their intentions more explicit.

Refactor scm repository provider private method names

---

ui/Gruntfile.js
ui/app/builds/directives/pnc-log-streamer/pncLogStreamer.js
ui/app/index.js
ui/app/pnc.module.js
web/src/main/java/org/jboss/pnc/web/UiConfigRest.java
web/src/main/java/org/jboss/pnc/web/UiConfigRestBuilder.java

[NCL-5592] Update UI to work with the new config structure

---

rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/BuildsFilterParameters.java
rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/ProductMilestoneCloseParameters.java

[NCL-5796] Fix switched documentation strings

---

facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
integration-test/src/test/java/org/jboss/pnc/integration_new/endpoint/ProductMilestoneEndpointTest.java

[NCL-5760] Fix Product Milestone update

---

indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/AbstractRepositoryManagerDriverTest.java
pom.xml

Bump Indy version to 2.2.0

---

common/src/main/java/org/jboss/pnc/common/concurrent/MDCThreadPoolExecutor.java
messaging/src/main/java/org/jboss/pnc/messaging/UnreliableMessageSender.java
messaging/src/test/java/org/jboss/pnc/messaging/UnreliableMessageSenderTest.java

Use MDCExecutor in JMS messages sender.

---

openshift-environment-driver/pom.xml

Manifest module dependency to dmr.

---

datastore/src/main/resources/META-INF/persistence.xml
facade/src/main/java/org/jboss/pnc/facade/providers/CacheProviderImpl.java
model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java
model/src/main/java/org/jboss/pnc/model/BuildRecord.java
model/src/main/java/org/jboss/pnc/model/GenericSetting.java
model/src/main/java/org/jboss/pnc/model/RepositoryConfiguration.java
model/src/main/java/org/jboss/pnc/model/TargetRepository.java
model/src/main/java/org/jboss/pnc/model/User.java
model/src/main/java/org/jboss/pnc/model/utils/HibernateStatsUtils.java
model/src/test/java/org/jboss/pnc/model/CacheHandlerTest.java
model/src/test/resources/META-INF/persistence.xml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/CacheEndpoint.java

[NCL-5748] - Port the tuning of the cache from v1.8 branch

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildPageInfo.java
facade/src/test/java/org/jboss/pnc/facade/providers/AbstractIntIdProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/ArtifactProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildConfigProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/EnvironmentProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/GroupBuildProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductReleaseProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductVersionProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProjectProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/UserProviderImplTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/BuildsFilterParameters.java
rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConstants.java
rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java

[NCL-5755]: Allow filtering builds by Build Config name

---

maven-repository-manager/src/test/java/org/jboss/pnc/mavenrepositorymanager/AbstractRepositoryManagerDriverTest.java
pom.xml

The bump is to try to workaround the issue around NCLSUP-51. Thanks to
Petr (@pkocandr) and Rui (@ruhan1) for their PR on master and guide on how to do it! :)

[v1.8.1] Use Indy client 2.2.0

---

maven-repository-manager/src/main/java/org/jboss/pnc/mavenrepositorymanager/MavenRepositorySession.java

Cache validator factory.

---

ui/app/index.html

NCL-2933 Menu refreshment

---

rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedSCMRepositoryClient.java

SCM Client: create the websocket client lazily

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/AbstractImportTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/AbstractRepositoryManagerDriverTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/AllSessionUrlsForBuildAreAlikeTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/BuildGroupIncludesConfSetGroupTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/BuildGroupIncludesProductVersionGroupTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/DependencyUrlIncludesTrackingIdAndGeneratedBuildGroupNameTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/DownloadTwoThenVerifyExtractedArtifactsContainThemTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExcludeInternalRepoByNameTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExcludeInternalRepoByRegexTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ImportDepVerifyPromotionToSharedImportsTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/UploadOneThenDownloadAndVerifyArtifactHasOriginUrlTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/UploadTwoThenVerifyExtractedArtifactsContainThemTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyBuildGroupRemovedAfterArtifactExtractionTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyBuildRepoPromotionToUntestedBuildsGroupTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyManualDeletionOfBuildRepoTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/VerifyManualPromotionOfBuildRepoTest.java

[NCL-5626] Rework deletion of temporary builds to use batch delete

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductMilestoneRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductReleaseRSQLMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProductMilestoneMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProductReleaseMapper.java
model/src/main/java/org/jboss/pnc/model/ProductMilestone.java
model/src/main/java/org/jboss/pnc/model/ProductRelease.java
model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql
rest-model/src/main/java/org/jboss/pnc/rest/restmodel/ProductMilestoneRest.java
rest-model/src/main/java/org/jboss/pnc/rest/restmodel/ProductReleaseRest.java

[NCL-5799]: Remove fields from Product Milestone/Release - Add DB migration script

---

ui/app/dashboard/directives/pnc-my-builds-panel/pncMyBuildsPanel.js
ui/app/dashboard/directives/pnc-my-group-builds-panel/pncMyGroupBuildsPanel.js

[NCL-5740] The "My Builds" section in the dashboard date order is reversed

---

ui/app/dashboard/directives/pnc-my-builds-panel/pncMyBuildsPanel.js
ui/app/dashboard/directives/pnc-my-group-builds-panel/pncMyGroupBuildsPanel.js

Sort by submitTime as sorting by id is not currently supported

---

ui/app/dashboard/directives/pnc-my-group-builds-panel/pncMyGroupBuildsPanel.js

[NCL-5740] - Order BuildGroups by startTime

---

ui/app/builds/detail/alignment-log/pnc-build-detail-alignment-log-page.html
ui/app/builds/detail/alignment-log/pncBuildDetailAlignmentLogPage.js
ui/app/common/pnc-client/resources/BuildResource.js

[NCL-5814] - Alignment log not visible

---

ui/app/product-milestones/close/pnc-product-milestone-close-page.html
ui/app/product-milestones/components/pnc-product-milestones-list/pnc-product-milestones-list.html
ui/app/product-milestones/create-update/pnc-product-milestone-create-update-page.html
ui/app/product-milestones/detail/pnc-product-milestone-detail-page.html
ui/app/product-releases/components/pnc-product-releases-list/pnc-product-releases-list.html
ui/app/product-releases/create-update/pnc-product-release-create-update-page.html

[NCL-5798] - Remove fields from Product Milestone/Release

---

ui/app/product-milestones/components/pnc-product-milestones-list/pnc-product-milestones-list.html
ui/app/product-releases/components/pnc-product-releases-list/pnc-product-releases-list.html

Remove deprecated headers from Product Milestone and Release tables

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/PromotionValidationException.java

[NCL-5807] Better handling of promotion validation errors

---

ui/app/builds/directives/pnc-build-link/pncBuildLink.js
ui/app/common/components/pnc-build-status/pnc-build-status.html

NCL-5813 Fixes "links to builds do not work due to TypeError on Group Config detail page"

---

rest-new/pom.xml

Fix authentication

---

ui/app/build-configs/directives/pnc-build-configs-list/pnc-build-configs-list.html
ui/app/build-configs/list/pncBuildConfigsListPage.js

[NCL-4440] - Remove Created and Modifed columns from build-configs page

---

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java

[NCLSUP-82] Print the buildrecord id having issues for rebuild check

---

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java

[v1.8.1][NCLSUP-82] Print problematic build record

---

ui/app/product-milestones/close-result/pnc-product-milestone-close-result-page.html
ui/app/product-milestones/components/pnc-milestone-close-status-label/pnc-milestone-close-status-label.html
ui/app/product-milestones/components/pnc-milestone-close-status-label/pncMilestoneCloseStatusLabel.js
ui/app/product-milestones/components/pnc-product-milestone-close-results-data-table/pnc-product-milestone-close-results-list.html

NCL-5633 Improve close status label appearance

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

[NCL-5777 update] Change scm protocol just for internal scms

---

ui/app/common/pnc-client/resources/ReportResource.js

NCL-5828 remove disused report resource methods

---

ui/app/builds/detail/brew-push/pncBuildDetailBrewPushPage.js
ui/app/product-milestones/close-result/pncProductMilestoneCloseResultPage.js

NCL-5011 / NCL-5633 Change bifrost params for causeway related logging features

---

constants/src/main/java/org/jboss/pnc/enums/BuildStatus.java

[NCL-5765] improved BuildStatus documentation

---

ui/app/build-configs/directives/pnc-build-configs-list/pnc-build-configs-list.html

Add ellipsis in case description is trimmed

---

ui/app/build-configs/directives/pnc-build-configs-list/pnc-build-configs-list.html

Escape special char

---

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/internal/BpmEndpointImpl.java

Set BpmEndpointImpl as ApplicationScoped

---

ui/app/builds/detail/details/pnc-build-detail-details-page.html
ui/app/common/pnc-client/resources/BuildResource.js

[NCL-3767] - Provide a link to download a zip of sources in PNC-UI

---

pom.xml

javapoet to: 1.13.0
byte-buddy to: 1.10.12

Update javapoet and byte-buddy

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java

Thanks to Honza (@janinko) for pointing this out!

[NCL-5830] Port count endpoint to rest-new

---

dto/src/main/java/org/jboss/pnc/dto/response/RunningBuildCount.java

[NCL-5830] Renaming awaitingForDependencies to waitingForDependencies

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildConfigurationProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java
rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildConfigurationPredicates.java

[NCL-5831] Add build configuration dependants endpoint

---

.gitignore
pom.xml

mockito-core: 3.3.4 -> 3.4.0
formatter-maven-plugin: 2.11.0 -> 2.12.1

Bump mockito and formatter-maven-plugin

---

ui/app/build-configs/detail/pnc-build-config-detail-main.html
ui/app/group-configs/detail/pnc-group-config-detail-page.html

[NCL-5847]Remove delete buttons on Build Config and Group Config

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleaner.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
datastore/src/test/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryTest.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/TemporaryBuildsCleanerTest.java
integration-test/src/test/java/org/jboss/pnc/integration/setup/Deployments.java
model/src/main/java/org/jboss/pnc/model/BuildRecord.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest-new/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java

[NCL-5202] redesign temporary builds cleaner logic

---

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java

[NCLSUP-93] Prevent NPE when checking if rebuild is required

---

facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java

NCL-5868 - remove DTO form milestone close endpoint.

---

facade/src/main/java/org/jboss/pnc/facade/providers/ProductProviderImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ProductPredicates.java

[NCL-5853] validate against Product abbreviation

---

rest-new/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java

Use milestone releaseId instead of milestone id as MDC.processContext.

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

no review or new info how it should be implemented... reverting

Revert "[NCL-5777 update] Change scm protocol just for internal scms"

---

ui/app/common/components/pnc-product-combobox/pnc-product-combobox.html
ui/app/group-configs/create/pnc-group-config-create-page.html
ui/app/group-configs/create/pncGroupConfigCreatePage.js

NCL-5752 Fix creation of a group config

---

constants/src/main/java/org/jboss/pnc/constants/Attributes.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/ArtifactAuditedRepositoryImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java
facade/src/main/java/org/jboss/pnc/facade/util/UserService.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ArtifactAuditedRepository.java
ui/app/common/components/pnc-corrupted-build-label/pncCorruptedBuildLabel.js

[NCL-4507] - Endpoints to set Artifact Quality Level

---

common/src/main/java/org/jboss/pnc/common/graph/GraphBuilder.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
datastore/src/test/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryTest.java
dto/src/main/java/org/jboss/pnc/dto/response/Graph.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/util/GraphDtoBuilder.java
facade/src/main/java/org/jboss/pnc/facade/validation/CorruptedDataException.java
facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java
rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerGraphs.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java

NCL-5866 - build dependency graph: include completed dependency

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java

[NCL-5878] fix BCA in BuildRecord being null causing NPE

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
bpm/src/main/java/org/jboss/pnc/bpm/causeway/InProgress.java
facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java

Add build push user logging.

---

facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java

Single push logContext.

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java

Use buildId in the Causeway callback for the single push.

---

ui/app/builds/detail/brew-push/pncBuildDetailBrewPushPage.js

NCL-5011 Update bifrost params for retrieving brew push logs

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
integration-test/src/test/java/org/jboss/pnc/integration/notifications/WebSocketClientTest.java

[NCL-5885] DONE WS message wrongly sent after final NO_REBUILD_REQUIRED

---

ui/app/build-configs/detail/dependencies-tab/pnc-build-config-dependencies-tab.html
ui/app/build-configs/detail/dependencies-tab/pncBuildConfigDependenciesTab.js
ui/app/build-configs/directives/pnc-build-configs-data-table/pncBuildConfigsDataTable.js
ui/app/common/pnc-client/resources/BuildConfigResource.js
ui/app/common/pnc-client/resources/GroupConfigResource.js
ui/app/group-configs/detail/build-configs-tab/pnc-group-config-build-configs-tab.html
ui/app/group-configs/detail/build-configs-tab/pncGroupConfigBuildConfigsTab.js

[NCL-5166] Edit functionality of build configs on group config detail view doesn't work

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmException.java
bpm/src/main/java/org/jboss/pnc/bpm/InvalidReferenceException.java
bpm/src/main/java/org/jboss/pnc/bpm/MissingInternalReferenceException.java
bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
bpm/src/main/java/org/jboss/pnc/bpm/causeway/InProgress.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildPushTest.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildPushResultMapper.java
rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
rest/src/main/java/org/jboss/pnc/rest/provider/BpmExceptionMapper.java

Set the ID of the BuildPushResult.

---

ui/app/builds/detail/brew-push/pncBuildDetailBrewPushPage.js

NCL-5011 Update bifrost params for single push log

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
causeway-client/src/main/java/org/jboss/pnc/causewayclient/remotespi/CallbackTarget.java

Set Causeway callback headers.

---

ui/app/builds/directives/pnc-brew-push-button/pncBrewPushButton.js

NCL-5011 Fixes an issue where clicking the brew push button does not reload the log viewer

---

ui/app/product-milestones/close-result/pncProductMilestoneCloseResultPage.js

NCL-5633 Update bifrost params for milestone close

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/ProductMilestoneReleaseManager.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java

Milesote close user logs.

---

ui/app/builds/detail/brew-push/pncBuildDetailBrewPushPage.js
ui/app/product-milestones/close-result/pncProductMilestoneCloseResultPage.js

Ncl 5633 4

---

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
spi/src/main/java/org/jboss/pnc/spi/datastore/Datastore.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

[NCL-5880] Fix built artifacts existence check

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildRSQLMapper.java

add milestone to Build RSQL mapper

---

model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql

[NCL-5923][NCL-3702] SQL script for addition of 'active' in group config

---

rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java

create Vertx on first WS connection to avoid blocking on creation

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/AbstractRepository.java
dto/src/main/java/org/jboss/pnc/dto/BuildConfiguration.java
dto/src/main/java/org/jboss/pnc/dto/GroupConfiguration.java
dto/src/main/java/org/jboss/pnc/dto/ProductVersion.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductVersionProviderTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/GroupConfigurationEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductVersionEndpointTest.java
model/src/main/java/org/jboss/pnc/model/ProductVersion.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/RepositoryMock.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/Repository.java

[NCL-5891] add generalized way to update OneToMany relationships and add functionality to endpoints

---

ui/app/build-configs/directives/pnc-create-build-config-product-version-form/pnc-create-build-config-product-version-form.html
ui/app/group-configs/create/pnc-group-config-create-page.html

[NCL-5913] fix select Product Version error while during Build Config creation

---

facade/src/main/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderImpl.java

[NCL-5930] fix NPE when getting a GC with non-existent ID

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java

[NCL-5928] fix listing multiple BCs with the same name

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java

[NCL-5894] Return 404 when there is no build group.

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
rest/src/main/java/org/jboss/pnc/rest/provider/ValidationExceptionExceptionMapper.java

Return 500 when dependecy graph cannot be loaded due to broken data.

---

ui/app/build-configs/directives/pnc-select-repository/pncSelectRepository.js
ui/app/common/pnc-client/jobs/buildConfigCreator.js

NCL-5917 NCL-5846 multipack

---

ui/app/build-configs/detail/revisions-tab/pncRevisionsDetails.js

[NCL-5751]hide product version link for Build Config Revisions

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinatorTest.java
spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildSetTask.java

[NCL-5932] Always store no_rebuild_required builds.

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java

[NCL-5894] Return 404 when there is no build group

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleaner.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/SkippingBuiltConfigsTest.java
datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
dto/src/main/java/org/jboss/pnc/dto/Build.java
integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java
model/src/main/java/org/jboss/pnc/model/BuildRecord.java
model/src/main/resources/db-update/20000-from-1.8.x-to-2.0.0.sql
pnc-mock/src/main/java/org/jboss/pnc/mock/datastore/DatastoreMock.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java
spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildTask.java
spi/src/main/java/org/jboss/pnc/spi/datastore/Datastore.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildRecordPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java

[NCL-5933] add a reference to a BuildRecord that caused build to be declined

---

rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java

Make ClientBase implement Closeable to allow clients to be closed

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java

404 when there is no BR for requested dependency-graph.

---

ui/bower.json

NCL-5403 NCL-5890 bump to latest version of bifrost client

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmEventType.java
bpm/src/main/java/org/jboss/pnc/bpm/causeway/ProductMilestoneReleaseManager.java
bpm/src/main/java/org/jboss/pnc/bpm/model/causeway/MilestoneReleaseResultRest.java
bpm/src/test/java/org/jboss/pnc/bpm/test/ProductMilestoneReleaseManagerTest.java
constants/src/main/java/org/jboss/pnc/enums/ReleaseStatus.java

Related: https://github.com/project-ncl/causeway/pull/124

[NCL-5940] Fix handling of error response from Milestone Brew Push

---

ui/bower.json
ui/package-lock.json
ui/package.json

NCL-5890 bump bifrost-js version to include fix

---

pom.xml

Use released version of build-agent

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java

[NCL-5965] ignore archived BuildConfigs in all cases

---

rest-client/src/main/java/org/jboss/pnc/restclient/websocket/predicates/SCMRepositoryNotificationPredicates.java

fix NPE in WS messages

---

ui/app/common/pnc-client/jobs/buildConfigCreator.js

NCL-5964 cleanup and remove unnecessary toString call

---

ui/app/build-configs/directives/pnc-create-build-config-wizard/pnc-create-build-config-wizard.html
ui/app/build-configs/directives/pnc-create-build-config-wizard/pncCreateBuildConfigWizard.js

[NCL-5909]fix Build config list not updated after new BC is created

---

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/SCMRepositoryEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/SCMRepositoryEndpointImpl.java

[NCL-5916] return 201 status when SCM/BC is created immediately

---

model/src/main/java/org/jboss/pnc/model/BuildRecord.java

NCL-6007 - fix NPE when there are no Repour or Build logs.

---

pom.xml

Ncl 5998 fix javadoc generation

---

common/src/main/java/org/jboss/pnc/common/net/GitSCPUrl.java
common/src/main/java/org/jboss/pnc/common/util/UrlUtils.java
common/src/test/java/org/jboss/pnc/common/net/GitSCPUrlTest.java
common/src/test/java/org/jboss/pnc/common/test/util/UrlUtilsTest.java

[NCL-5990] add support for git scp-like urls in SCMRepositories

---

ui/app/product-milestones/close-result/pnc-product-milestone-close-result-page.html
ui/app/product-milestones/close-result/pncProductMilestoneCloseResultPage.js

[NCL-6008] - Milestone Brewpush not showing brew-url

---

common/src/main/java/org/jboss/pnc/common/concurrent/MDCExecutors.java
common/src/main/java/org/jboss/pnc/common/concurrent/SequenceGenerator.java
common/src/main/java/org/jboss/pnc/common/json/AbstractModuleConfig.java
common/src/main/java/org/jboss/pnc/common/json/AbstractModuleGroup.java
common/src/main/java/org/jboss/pnc/common/json/JsonOutputConverterMapper.java
common/src/main/java/org/jboss/pnc/common/json/ModuleConfigJson.java
common/src/main/java/org/jboss/pnc/common/json/moduleprovider/ConfigProvider.java
common/src/main/java/org/jboss/pnc/common/monitor/ScheduledExecutorServiceWithTimeout.java
common/src/main/java/org/jboss/pnc/common/security/CheckSum.java
common/src/main/java/org/jboss/pnc/common/security/Md5.java
common/src/main/java/org/jboss/pnc/common/security/Sha256.java
common/src/main/java/org/jboss/pnc/common/tree/TreeNode.java
common/src/main/java/org/jboss/pnc/common/util/CollectionUtils.java
common/src/main/java/org/jboss/pnc/common/util/HttpUtils.java
common/src/main/java/org/jboss/pnc/common/util/RandomUtils.java
common/src/main/java/org/jboss/pnc/common/util/StringUtils.java
common/src/test/java/org/jboss/pnc/common/concurrent/MDCExecutorTest.java
common/src/test/java/org/jboss/pnc/common/test/util/StringUtilsTest.java
common/src/test/java/org/jboss/pnc/common/test/util/TimeUtilsTest.java

Code cleanups include:
- Use diamond operator
- Remove redundant fields in annotations
- Use static inner class when possible for memory
- Use method reference for lambdas
- Replace string "UTF-8" with StandardCharsets.UTF_8
- Remove unecessary variables that store result that we immediately
return
- Use Java style array declaration rather than C style

Run Intellij inspections on the common module

---

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java
openshift-environment-driver/src/test/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironmentTest.java

Minor code cleanup for the openshift-environment-driver module

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/ProductMilestoneReleaseManager.java
bpm/src/test/java/org/jboss/pnc/bpm/test/RepositoryManagerResultSerializationTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/AbstractDependentBuildTest.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/AbstractRepository.java
datastore/src/test/java/org/jboss/pnc/datastore/repositories/BuildConfigurationRepositoryImplTest.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java
facade/src/test/java/org/jboss/pnc/facade/BuildPusherRejectionsTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProjectEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/notifications/ProcessProgressNotificationTest.java
integration-test/src/test/java/org/jboss/pnc/integration/notifications/WsUpdatesClient.java
rest-api/src/main/java/org/jboss/pnc/client/Configuration.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/HealthCheckEndpoint.java
spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java

Remove unused imports

---

build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/configuration/ConfigurationTest.java
datastore/src/test/java/org/jboss/pnc/datastore/DatastoreTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExtraDependencyRepositoriesTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/IndyPromotionValidationTest.java
model/src/test/java/org/jboss/pnc/model/ArtifactTest.java
model/src/test/java/org/jboss/pnc/model/BuildRecordTest.java
model/src/test/java/org/jboss/pnc/model/ModelValidationTest.java
moduleconfig/src/test/java/org/jboss/pnc/common/json/moduleconfig/IndyRepoDriverModuleConfigTest.java
pom.xml

Javadocs: Simplify asserts

---

bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java
build-executor/src/test/java/org/jboss/pnc/executor/BuildExecutionCancellationTest.java
constants/src/main/java/org/jboss/pnc/enums/BuildPushStatus.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/DefaultSequenceHandlerRepository.java
facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderTest.java
rest/src/main/java/org/jboss/pnc/rest/RequestLoggingFilter.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/DefaultFileTranser.java

Remove extra semi-colon, and collapse exception handling

---

ui/app/products/components/pnc-products-data-table/pncProductsDataTable.js

[NCL-5742] Add abbreviation filter option to product list page

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java

[NCL-5989] don't send WS message with no async job running

---

model/src/main/java/org/jboss/pnc/model/Artifact.java

[NCL-6021] - Add index on artifact.filename

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/BlacklistAsyncInvoker.java
facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java

[NCL-5733] - Propagate the change of artifact quality to DA

---

rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java

NCL5967 : Only add port if its not null

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java
build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/ExtraDependencyRepositoriesTest.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/IndyPromotionValidationTest.java
integration-test/src/test/java/org/jboss/pnc/integration/notifications/ProcessProgressNotificationTest.java
integration-test/src/test/java/org/jboss/pnc/integration/notifications/WsUpdatesClient.java
model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java
model/src/main/java/org/jboss/pnc/model/BuildEnvironment.java
model/src/main/java/org/jboss/pnc/model/ProductVersion.java
model/src/main/java/org/jboss/pnc/model/utils/HibernateStatsUtils.java
model/src/test/java/org/jboss/pnc/model/BuildRecordTest.java
model/src/test/java/org/jboss/pnc/model/CacheHandlerTest.java
moduleconfig/src/test/java/org/jboss/pnc/common/json/moduleconfig/JenkinsBuildDriverModuleConfigTest.java
notifications/src/main/java/org/jboss/pnc/notification/TypedMessage.java
pnc-mock/src/main/java/org/jboss/pnc/mock/datastore/DatastoreMock.java
rest-api/src/main/java/org/jboss/pnc/client/PageReader.java

Use diamond operator for Java Generics initializers

---

ui/app/artifacts/artifactQualityLevels.js
ui/app/artifacts/components/pnc-artifact-quality-label/pnc-artifact-quality-label.html
ui/app/artifacts/components/pnc-artifact-quality-label/pncArtifactQualityLabel.js
ui/app/artifacts/components/pnc-artifact-quality-update-modal/artifactQualityUpdateModalFactory.js
ui/app/artifacts/components/pnc-artifact-quality-update-modal/pnc-artifact-quality-update-modal.html
ui/app/artifacts/components/pnc-artifact-quality-update-modal/pncArtifactQualityUpdateModal.js
ui/app/artifacts/detail/pnc-artifacts-detail-page.html
ui/app/artifacts/detail/pncArtifactsDetailPage.js
ui/app/artifacts/list/pnc-artifacts-list.html
ui/app/artifacts/list/pncArtifactsDataTable.js
ui/app/artifacts/list/pncArtifactsList.js
ui/app/common/authentication/authService.js
ui/app/common/authentication/keycloak.js
ui/app/common/directives/pnc-role-control/pncRoleControl.js
ui/app/common/pnc-client/resources/ArtifactResource.js
ui/app/product-versions/product-versions.module.js
ui/app/styles/app.css
ui/app/styles/directives.css
ui/app/styles/generics.css

NCL-5681 Add UI support for artifact quality levels

---

ui/app/artifacts/ArtifactModals.js
ui/app/artifacts/artifacts.module.js
ui/app/artifacts/components/pnc-artifact-revisions-datatable/pnc-artifact-revision-list.html
ui/app/artifacts/components/pnc-artifact-revisions-datatable/pnc-artifact-revisions-datatable.html
ui/app/artifacts/components/pnc-artifact-revisions-datatable/pncArtifactRevisionList.js
ui/app/artifacts/components/pnc-artifact-revisions-datatable/pncArtifactRevisionsDatatable.js
ui/app/artifacts/components/pnc-artifact-revisions-modal/pnc-artifact-revisions-modal.html
ui/app/artifacts/components/pnc-artifact-revisions-modal/pncArtifactRevisionsModal.js
ui/app/artifacts/detail/pnc-artifacts-detail-page.html
ui/app/artifacts/list/pnc-artifacts-list.html
ui/app/artifacts/list/pncArtifactsList.js
ui/app/common/pnc-client/resources/ArtifactResource.js
ui/app/styles/directives.css

NCL-5682 Visualize the quality levels revisions history

---

ui/app/builds/detail/details/pnc-build-detail-details-page.html

NCL-6052 Add build type to build details page

---

ui/app/common/select-modals/BuildGroupMultiSelectController.js
ui/app/group-configs/components/pnc-group-configs-data-table/pncGroupConfigsDataTable.js
ui/app/product-versions/detail/pncProductVersionDetailPage.js

NCL-5942 Fixes broken edit button on group configs table

---

ui/app/build-configs/directives/pnc-build-configs-data-table/pnc-build-configs-data-table.html
ui/app/build-configs/directives/pnc-build-configs-list/pnc-build-configs-list.html
ui/app/common/components/pnc-build-start/pnc-build-start.html
ui/app/common/components/pnc-build-start/pncBuildStart.js
ui/app/group-configs/components/pnc-group-configs-data-table/pncGroupConfigsDataTable.js
ui/app/product-milestones/components/pnc-product-milestone-actions/pnc-product-milestone-actions.html
ui/app/product-milestones/components/pnc-product-milestones-list/pnc-product-milestones-list.html
ui/app/product-releases/components/pnc-product-releases-list/pnc-product-releases-list.html
ui/app/styles/app.css
ui/app/styles/directives.css
ui/app/styles/generics.css

Fix actions buttons

---

pom.xml
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriverTest.java

Use only one instance of http client in BuildAgentClient.

---

termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java

Add ClientFactory initialization logging.

---

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

[NCL-6032] - Do not retry start environment if build was cancelled

---

termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/AbstractLocalBuildAgentTest.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriverTest.java

Initialize applicaiton scoped bean in PostConstruct.

---

ui/app/build-configs/directives/pnc-select-repository/pnc-select-repository.html
ui/app/scm-repositories/create/pnc-scm-repository-create-page.html

[NCL-6042] Allow scp like URLs in UI

---

ui/app/build-configs/build-configs.module.js

NCL-6046 Restore UI shortlink to build config

---

rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java

[NCL-6063] initialize WS client before BrewPush to avoid running conditions

---

bpm/src/main/java/org/jboss/pnc/bpm/ConnectorSelector.java
bpm/src/main/java/org/jboss/pnc/bpm/notification/BpmNotifier.java
facade/src/main/java/org/jboss/pnc/facade/executor/BuildExecutorTriggerer.java

Use access token in RHPAM callback.

---

bpm/src/main/java/org/jboss/pnc/bpm/notification/BpmNotifier.java

Send executor response as json in RHPAM callback.

---

facade/pom.xml
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/util/RepourClient.java
pom.xml

Check for conflict with exising SCM repo, when creating new one

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/SCMRepositoryEndpointTest.java

[NCL-6016] Validate ExternalUrl does not exist when updating SCMR

---

ui/app/group-configs/detail/pnc-group-config-detail-page.html
ui/app/group-configs/detail/pncGroupConfigDetailPage.js
ui/app/product-versions/components/pnc-product-version-link/pncProductVersionLink.js

[NCL-5848] Product version can be edited on GC detail page

---

ui/app/common/components/pnc-admin-panel/pnc-admin-panel.html
ui/app/common/components/pnc-admin-panel/pncAdminPanel.js
ui/app/common/components/pnc-global-alert/pnc-global-alert.html
ui/app/common/components/pnc-global-alert/pncGlobalAlert.js
ui/app/common/pnc-client/message-bus/messageBus.js
ui/app/common/pnc-client/resources/GenericSetting.js

[NCL-5918]Announcement Banner for global notice

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildTaskEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/SCMRepositoryEndpointTest.java
rest-api/pom.xml
rest-api/src/main/java/org/jboss/pnc/rest/jackson/JacksonProvider.java

Register jackson JDK8 module.

---

rest/src/main/java/org/jboss/pnc/rest/provider/RuntimeExceptionMapper.java

[NCL-6067] Log already active build as WARNING

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmManager.java
bpm/src/main/java/org/jboss/pnc/bpm/Connector.java
bpm/src/main/java/org/jboss/pnc/bpm/KieClientConnector.java
bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java

BPM REST connector: cancel support.

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/BlacklistAsyncInvoker.java
common/src/main/java/org/jboss/pnc/common/util/HttpUtils.java

[NCL-5733] Add authorization when posting requests to blacklist artifacts in DA

---

model/src/main/java/org/jboss/pnc/model/BuildRecord.java

[NCL-6069] NPE when storing failed build

---

facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLException.java
facade/src/main/java/org/jboss/pnc/facade/validation/AlreadyRunningException.java
facade/src/main/java/org/jboss/pnc/facade/validation/DTOValidationException.java
facade/src/main/java/org/jboss/pnc/facade/validation/OperationNotAllowedException.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/EnvironmentEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductReleaseEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductVersionEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProjectEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/UserEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/CacheEndpointImpl.java

[NCL-6065] avoid some EJB ERROR logs that are not actually errors

---

facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java

[NCL-5733] If the quality level is not changing in a bulk update, ignore the subsequent stricter checks

---

ui/app/product-milestones/components/pnc-product-milestone-actions/pnc-product-milestone-actions.html
ui/app/product-milestones/detail/pnc-product-milestone-detail-page.html
ui/app/product-milestones/product-milestone.module.js

[NCL-5763] Make Milestone Update and Close states nested in detail state

---

ui/app/builds/directives/pnc-brew-push-button/pnc-brew-push-button.html
ui/app/common/pnc-client/resources/helpers/buildStatusHelper.js

[NCL-6085] Allow only SUCCESS builds to be pushed to brew

---

ui/app/product-milestones/components/pnc-product-milestone-actions/pnc-product-milestone-actions.html

[NCL-6095] Fix Milestone Actions buttons layout

---

ui/app/group-configs/detail/build-history-tab/pnc-group-config-build-history-tab.html
ui/app/group-configs/detail/build-history-tab/pncGroupConfigBuildHistoryTab.js

[NCL-5992]remove group config submit time

---

ui/app/builds/directives/pnc-build-tree/pncBuildTree.js
ui/app/common/components/pnc-build-status-icon/pnc-build-status-icon.html
ui/app/common/pnc-client/pagination/filteringPaginator.js
ui/app/common/pnc-client/resources/helpers/buildStatusHelper.js

[NCL-6099] Remove deprecated build statuses in UI

---

ui/app/common/pnc-client/pagination/page.js

[NCL-5938] Page maximum size check

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ArtifactRSQLMapper.java

[NCL-6079] Fix filtering on TargetRepository

---

ui/app/common/util/ProductMilestoneHelper.js
ui/app/product-milestones/components/pnc-product-milestone-actions/pnc-product-milestone-actions.html
ui/app/product-milestones/components/pnc-product-milestone-actions/pncProductMilestoneActions.js
ui/app/product-milestones/components/pnc-product-milestone-link/pnc-product-milestone-link.html
ui/app/product-milestones/components/pnc-product-milestones-list/pnc-product-milestones-list.html
ui/app/product-milestones/components/pnc-product-milestones-list/pncProductMilestonesList.js
ui/app/product-milestones/detail/pnc-product-milestone-detail-page.html
ui/app/product-milestones/detail/pncProductMilestoneDetailPage.js

[NCL-6199] Indicate current milestones

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
model/src/main/java/org/jboss/pnc/model/BuildRecord.java

Make executionRootName and executionRootVersion updatable as they should be modifiable as attributes

---

dto/src/main/java/org/jboss/pnc/dto/BuildConfiguration.java
dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRef.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildConfigProviderTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildConfigurationMapper.java
model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java

[NCL-6158]: Add 'Brew pull active' flag on build config

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationAuditedRepositoryImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConstants.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildConfigurationAuditedRepository.java

[NCL-6128]: Add LIKE support to filter builds by BuildConfig.name

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java

[NCL-6068] Log Artifact promotion failure as WARNING

---

model/src/main/resources/db-update/2000X-from-2.0.x-to-2.1.0.sql

[NCL-6158]: Add DB migration script

---

indy-repository-manager/pom.xml
indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/fixture/TestBuildExecution.java
spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionConfiguration.java
spi/src/main/java/org/jboss/pnc/spi/repositorymanager/BuildExecution.java

[NCL-4725] Add gradle plugins repository into build group for Gradle builds

---

indy-repository-manager/pom.xml
indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java
indy-repository-manager/src/test/java/org/jboss/pnc/indyrepositorymanager/fixture/TestBuildExecution.java
spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionConfiguration.java
spi/src/main/java/org/jboss/pnc/spi/repositorymanager/BuildExecution.java

[v2.0] [NCL-4725] Add gradle plugins repository into build group for Gradle builds

---

ui/app/artifacts/list/pncArtifactsDataTable.js

[v2.0] [NCL-6173] Add deleted artifact quality into artifacts filter

---

ui/app/artifacts/list/pncArtifactsDataTable.js

[NCL-6173] Add deleted artifact quality into artifacts filter

---

pom.xml

change from SNAPSHOT for build-agent and pnc-api

---

common/src/main/java/org/jboss/pnc/common/json/JsonOutputConverterMapper.java
common/src/test/java/org/jboss/pnc/common/json/JSonOutputConverterTest.java

[NCL-6077] Could not convert object to JSON errors

---

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/response/ArtifactInfo.java
facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

[NCL-6163] New endpoint on Artifact with direct filtering for DA

---

model/src/main/java/org/jboss/pnc/model/BuildEnvironment.java
model/src/main/resources/db-update/20001-from-2.0.0-to-2.0.1.sql

[NCL-6180] - Change the contraints on the uniqueness of the BuildEnvironment name

---

common/src/main/java/org/jboss/pnc/common/json/JsonOutputConverterMapper.java

[NCL-6077] - Try to ignore nested reference chain bits which causes the NPE

---

model/src/main/java/org/jboss/pnc/model/Artifact.java
model/src/main/java/org/jboss/pnc/model/BuildConfigSetRecord.java
model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java
model/src/main/java/org/jboss/pnc/model/BuildConfigurationSet.java
model/src/main/java/org/jboss/pnc/model/BuildRecord.java
model/src/main/java/org/jboss/pnc/model/Product.java
model/src/main/java/org/jboss/pnc/model/ProductMilestone.java
model/src/main/java/org/jboss/pnc/model/ProductMilestoneRelease.java
model/src/main/java/org/jboss/pnc/model/ProductVersion.java
model/src/main/java/org/jboss/pnc/model/Project.java
model/src/main/java/org/jboss/pnc/model/TargetRepository.java
model/src/main/java/org/jboss/pnc/model/User.java

Keep JPA relationships synchronized

---

ui/bower.json

NCL-6036 Add stack traces to build logs

---

constants/src/main/java/org/jboss/pnc/enums/JobNotificationType.java
dto/src/main/java/org/jboss/pnc/dto/notification/ProductMilestoneCloseResultNotification.java
notifications/src/main/java/org/jboss/pnc/notification/DefaultNotifier.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildConfigurationClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedGroupConfigurationClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedProductMilestoneClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/websocket/WebSocketClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/websocket/predicates/ProductMilestoneCloseResultNotificationPredicates.java

[NCL-6011] Add websocket notifications for milestone push jobs

---

constants/src/main/java/org/jboss/pnc/enums/JobNotificationType.java
dto/src/main/java/org/jboss/pnc/dto/notification/ProductMilestoneCloseResultNotification.java
notifications/src/main/java/org/jboss/pnc/notification/DefaultNotifier.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildConfigurationClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedGroupConfigurationClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedProductMilestoneClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/websocket/WebSocketClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/websocket/predicates/ProductMilestoneCloseResultNotificationPredicates.java

[NCL-6011] Add websocket notifications for milestone push jobs branch v2.0

---

ui/app/build-configs/detail/details-tab/pnc-build-config-properties.html
ui/app/build-configs/detail/details-tab/pncBuildConfigDetailsEditor.js
ui/app/build-configs/detail/details-tab/pncBuildConfigProperties.js
ui/app/build-configs/detail/revisions-tab/pncRevisionsDetails.js
ui/app/build-configs/directives/pnc-create-build-config-general-form/pnc-create-build-config-general-form.html
ui/app/build-configs/directives/pnc-create-build-config-general-form/pncCreateBuildConfigGeneralForm.js

[NCL-6161] Add brewPullActive checkbox to BC in UI

---

pom.xml
rest-api/pom.xml

- assertj: 3.18.0
- mockito: 3.6.0
- swagger2: 2.1.4
- snakeyaml: 1.27
- wiremock-jre8: 2.27.2
- jacoco-core: 0.8.6
- byte-buddy: 1.10.17
- jacoco-maven-plugin: 0.8.6
- swagger-maven-plugin: 2.1.5

Bump versions of deps

---

facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/EnvironmentProviderTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/EnvironmentEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/RestTest.java
integration-test/src/test/resources/environment.json
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/EnvironmentEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/EnvironmentEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/EnvironmentPredicates.java

[NCL-6184] - Implement the endpoint to create a new Environment

---

bpm/src/test/java/org/jboss/pnc/bpm/test/BuildResultSerializationTest.java
bpm/src/test/java/org/jboss/pnc/bpm/test/RepositoryManagerResultSerializationTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorDeployments.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/mock/EntityManagerMock.java
facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java
mapper/pom.xml
mapper/src/main/java/org/jboss/pnc/mapper/AbstractArtifactMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/MapSetMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/RefToReferenceMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ArtifactMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ArtifactRevisionMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildConfigurationMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildConfigurationRevisionMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildPushResultMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/EntityMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/EnvironmentMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/GroupBuildMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/GroupConfigurationMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProductMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProductMilestoneCloseResultMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProductMilestoneMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProductReleaseMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProductVersionMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProjectMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/SCMRepositoryMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/TargetRepositoryMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/UserMapper.java

[NCL-5812] Change mappers to map DTORefs to Entity lazy reference

---

ui/app/product-milestones/components/pnc-product-milestone-actions/pnc-product-milestone-actions.html

[NCL-6131] for branch 2.0: Fix Transaction Rejection error when trying to close or edit milestones

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java

[v2.0][NCL-6216] Fix comparison of existing remote repos

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java

[NCL-6216] Fix comparison of existing remote repos

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmManager.java
bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java
bpm/src/main/java/org/jboss/pnc/bpm/task/BpmBuildTask.java
bpm/src/main/java/org/jboss/pnc/bpm/task/MilestoneReleaseTask.java
bpm/src/main/java/org/jboss/pnc/bpm/task/RepositoryCreationTask.java
bpm/src/test/java/org/jboss/pnc/bpm/test/BpmSchedulerSmokeTest.java
constants/src/main/java/org/jboss/pnc/enums/ResultStatus.java
dto/src/main/java/org/jboss/pnc/dto/tasks/RepositoryCreationResult.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/SCMRepositoryProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/UserRoles.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/BpmModuleConfig.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BpmEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BpmEndpoint.java

New repository creation process support.

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

Repository creation process - set config.

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

Repository creation process - do not json encode process parameters.

---

ui/app/build-configs/directives/pnc-build-configs-data-table/pnc-build-configs-data-table.html
ui/app/build-configs/directives/pnc-build-configs-data-table/pncBuildConfigsDataTable.js
ui/app/projects/detail/pnc-project-detail-page.html
ui/app/projects/detail/pncProjectDetailPage.js

[NCL-3812] Improve Build Configuration section on Project detail page

---

bpm/src/main/java/org/jboss/pnc/bpm/task/RepositoryCreationTask.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

Repository creation process - add jobType to process parameters.

---

facade/src/main/java/org/jboss/pnc/facade/validation/ValidationBuilder.java
mapper/src/main/java/org/jboss/pnc/mapper/BuildBCRevisionFetcher.java

Random fixes

---

dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRef.java
model/src/main/resources/db-update/2000X-from-2.0.x-to-2.1.0.sql

[NCL-6188] Add BC Audited to brewPullActive DB migration script

---

dto/src/main/java/org/jboss/pnc/dto/tasks/RepositoryCreationResult.java

Repository creation process - add missing json builder annotations.

---

facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java

[NCL-6199] fix NPE, eliminate cross joins, fix no results returned

---

facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java

[v2.0.x] [NCL-6199] fix NPE, eliminate cross joins, fix no results returned

---

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionSession.java
facade/src/main/java/org/jboss/pnc/facade/executor/BuildExecutorTriggerer.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/TermdBuildDriverModuleConfig.java
pnc-mock/src/main/java/org/jboss/pnc/mock/executor/BuildExecutionSessionMock.java
pom.xml
rest/pom.xml
rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildExecutionEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildExecutionEndpoint.java
spi/pom.xml
spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionSession.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/ClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/AbstractLocalBuildAgentTest.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java

Build Agent use HTTP callback instead of WS.

---

ui/app/common/pnc-client/pagination/filteringPaginator.js
ui/app/common/pnc-client/rsql/comparator.js

[NCL-5709]Implement negation in search filters

---

pom.xml
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildExecutionEndpoint.java

Bump Build Agent version.

---

ui/app/build-configs/detail/revisions-tab/pncRevisionsDetails.js

[NCL-6213] Add brePullActive tag to Revisions tab

---

common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/TermdBuildDriverModuleConfig.java
spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionSession.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/ClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdServer.java

Execution callback headers and retry config.

---

common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildExecutionEndpointImpl.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/ClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java

Add missing CDI annotaion to the REST endpoint.

---

integration-test/src/test/java/org/jboss/pnc/integration/BuildExecutionTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/executor/BuildExecutorMock.java
rest/pom.xml

Remove build-agent from rest.war

---

facade/src/main/java/org/jboss/pnc/facade/executor/BuildExecutorTriggerer.java
integration-test/src/test/java/org/jboss/pnc/integration/BuildExecutionTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildExecutionEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildExecutionEndpoint.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/ClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java

Add buildExecutionSession.id to callback.

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/ProductMilestoneReleaseManager.java
bpm/src/test/java/org/jboss/pnc/bpm/test/ProductMilestoneReleaseManagerTest.java

[NCL-6011] Fire product milestone events

---

bpm/src/main/java/org/jboss/pnc/bpm/model/RepositoryCreationProcess.java
dto/src/main/java/org/jboss/pnc/dto/tasks/RepositoryCreationResult.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildConfigurationProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/SCMRepositoryProvider.java

Repository creation process - pass BC around the process.

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/ProductMilestoneReleaseManager.java
bpm/src/test/java/org/jboss/pnc/bpm/test/ProductMilestoneReleaseManagerTest.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/BpmModuleConfig.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BpmEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BpmEndpoint.java

[NCL-6141] Add milestone close process name config

---

dto/src/main/java/org/jboss/pnc/dto/Environment.java
facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/EnvironmentProviderTest.java
model/src/main/java/org/jboss/pnc/model/BuildEnvironment.java
model/src/main/resources/db-update/20002-from-2.0.1-to-2.0.2.sql
model/src/test/resources/basic-model-test-data.xml
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/EnvironmentPredicates.java
ui/app/common/components/pnc-environment-combobox/pncEnvironmentCombobox.js

[NCL-6240] Add a "hidden" field in BuildEnvironment so to hide them from the combobox 

---

facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/EnvironmentProviderTest.java

[NCL-6240] Let all users visualize via REST the environments

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/EnvironmentRSQLMapper.java

Fix RSQL mapping of hidden field

---

facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/EnvironmentRSQLMapper.java
facade/src/test/java/org/jboss/pnc/facade/providers/EnvironmentProviderTest.java

[NCL-6240] Fix RSQL mapping of hidden field

---

ui/app/builds/directives/pnc-build-config-link/pnc-build-config-link.html

[NCL-6215]fix Build History not updated in BC details page after aborted

---

ui/app/builds/detail/details/pnc-build-detail-details-page.html

[NCL-6238] Show environment description also in the build details

---

ui/app/common/components/pnc-environment-combobox/pnc-environment-combobox.html
ui/app/common/components/pnc-environment-combobox/pncEnvironmentCombobox.js

NCL-6261 Add checkbox for showing deprecated environments

---

ui/app/common/components/pnc-environment-combobox/pnc-environment-combobox.html
ui/app/common/components/pnc-environment-combobox/pncEnvironmentCombobox.js

(cherry picked from commit c3ac09c842f13dba9d9b48358eb7888e7df5362a)

[v2.0.2] NCL-6261 Add checkbox for showing deprecated environments

---

facade/src/main/java/org/jboss/pnc/facade/rsql/StreamRSQLNodeTraveller.java

Fix RSQL comparsion order in stream predicates

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java

[NCLSUP-202] Fix validation when updating SCMR to not conflict with self

---

ui/app/common/components/pnc-environment-combobox/pnc-environment-combobox.html
ui/app/common/components/pnc-environment-combobox/pncEnvironmentCombobox.js

Do not reload items on ng-change; optimize env queries

---

ui/app/common/components/pnc-environment-combobox/pncEnvironmentCombobox.js
ui/app/common/pnc-client/resources/EnvironmentResource.js

Added back pagination of 200; do not show hidden environments

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleaner.java

[v2.0] [NCLSUP-213] Temp build deletion fails with constraint violation

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/TemporaryBuildsCleaner.java

[NCLSUP-213] Temp build deletion fails with constraint violation

---

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

Commits cherry-picked from PR: https://github.com/project-ncl/pnc/pull/3428

[v2.0] [NCLSUP-217] Improvements to internal url check for builder pod creation

---

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductVersionProviderTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductVersionEndpointTest.java

[NCL-6237] Could set closed milestone as current

---

bpm/src/main/java/org/jboss/pnc/bpm/ConnectorSelector.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java

Always use new BPM connector.

---

constants/src/main/java/org/jboss/pnc/constants/ReposiotryIdentifier.java
constants/src/main/java/org/jboss/pnc/enums/ArtifactQuality.java
datastore/src/test/java/org/jboss/pnc/datastore/DatastoreTest.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/ProductMilestone.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerResultProcessor.java
facade/src/test/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerResultProcessorTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java
indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ProductMilestoneMapper.java
model/src/main/java/org/jboss/pnc/model/ProductMilestone.java
model/src/main/java/org/jboss/pnc/model/TargetRepository.java
model/src/main/resources/db-update/2000X-from-2.0.x-to-2.1.0.sql
model/src/test/java/org/jboss/pnc/model/BasicModelTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/model/builders/ArtifactBuilder.java
pom.xml
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

[NCL-6194] Add functionality to process the results of Deliverable Analysis

---

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/TermdBuildDriverModuleConfig.java
pom.xml
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/ClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/ClientFileTransfer.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/DefaultFileTransfer.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/FileTransfer.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/AbstractLocalBuildAgentTest.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/DebugInContainerTest.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/LivenessProbeTest.java

NCL-6314 - build agent file transfer retry.

---

bpm/src/main/java/org/jboss/pnc/bpm/ConnectorSelector.java
bpm/src/main/java/org/jboss/pnc/bpm/notification/BpmNotifier.java

Always use new BPM connector - fix executor response.

---

facade/src/main/java/org/jboss/pnc/facade/providers/AbstractProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigRevisionHelper.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/GroupConfigurationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProjectProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java

2.0 - log level fixes

---

pom.xml

Bump assertj, mockito, byte-buddy versions

---

indy-repository-manager/pom.xml
pom.xml
ui/pom.xml

Bump versions of lombok,git-commit-id-plugin,frontend-maven-plugin

---

termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/TermdBuildDriver.java

Faild the build with system_error when unable to flush primary logger.

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmManager.java
facade/src/main/java/org/jboss/pnc/facade/executor/BuildExecutorTriggerer.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/BuildTaskEndpoint.java

BuildTask endpoints string ids.

---

bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationRest.java
bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationWithCallbackRest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java

Use idMapper in BuildExecutionConfigurationRest.

---

facade/src/main/java/org/jboss/pnc/facade/executor/BuildExecutorTriggerer.java
model/src/main/resources/db-update/2000X-from-2.0.x-to-2.1.0.sql

Long id from the build agent response.

---

ui/app/common/templates/footer.tmpl.html

Update footer to current year: 2021

---

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

[NCL-6311] Cleanup and openshift object retry

---

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

[v2.0] [NCL-6311] Retries on openshift environment creation

---

ui/app/build-configs/buildTypes.js

[NCL-6274] - Update UI for the Scala support

---

build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutor.java
indy-repository-manager/pom.xml
indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repositorymanager/RepositoryManagerMock.java
pom.xml
spi/src/main/java/org/jboss/pnc/spi/repositorymanager/RepositoryManager.java

[NCL-6325] Add failsafe policy on repository creation

---

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

This reverts commit 902623c6e7ea24d8bb91d9406c945d5828928db0.

Revert "[NCL-6311] Retry on Openshift object creation"

---

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

This reverts commit 79c223bf146c4b612039adb9eb6377d02a27f1f3.

[v2.0] Revert "[NCL-6311] Retry on Openshift object creation"

---

build-executor/src/main/java/org/jboss/pnc/executor/BuildTypeToRepositoryType.java
constants/src/main/java/org/jboss/pnc/enums/BuildType.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
integration-test/src/test/resources/pnc-config.json

[NCL-6271] - Add Scala support to the PNC Orchestrator

---

ui/app/common/pnc-client/pagination/filteringPaginator.js
ui/app/product-milestones/components/pnc-product-milestone-builds/pncProductMilestoneBuilds.js

[NCL-6064] Fix RSQL error when filtering build config name on milestone page

---

pom.xml

Bump openshift-restclient-java v to 5.9.6.Final

---

openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

[NCL-6311] Add retries for openshift objects

---

ear-package/pom.xml
ui/app/index.html
web/src/main/java/org/jboss/pnc/web/UIConfigurationServletJs.java
web/src/main/java/org/jboss/pnc/web/UIConfigurationServletJson.java

[NCL-6337] Move UI config file(s) to new location

---

facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/GenericSettingEndpointImpl.java

[NCL-6338] Endpoint for storing and getting PNC global version

---

rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java

Error handling enhancement. When a build trigger failed because of a
conflicting build already running, it got thrown as a RuntimeException.
Switched that to AlreadyRunningException with conflicting task ID as
the response object.

[2.0] Return relevant error in case of BuildConflictException

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java

[NCL-6373] fix storing build as NEW on user alignment failure

---

facade/src/main/java/org/jboss/pnc/facade/executor/BuildExecutorTriggerer.java

Make idempotent build execution completion notification processing.

---

bpm/pom.xml
bpm/src/main/java/org/jboss/pnc/bpm/Connector.java
bpm/src/main/java/org/jboss/pnc/bpm/KieClientConnector.java
bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java
bpm/src/main/java/org/jboss/pnc/bpm/model/AnalyzeDeliverablesBpmRequest.java
bpm/src/main/java/org/jboss/pnc/bpm/model/MDCParameters.java
bpm/src/main/java/org/jboss/pnc/bpm/task/AnalyzeDeliverablesTask.java
bpm/src/test/java/org/jboss/pnc/bpm/test/RestConnectorRequestSerializationTest.java
common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java
dto/pom.xml
dto/src/main/java/org/jboss/pnc/dto/requests/DeliverablesAnalysisRequest.java
facade/src/main/java/org/jboss/pnc/facade/DeliverablesAnalyzerInvoker.java
facade/src/main/java/org/jboss/pnc/facade/impl/DeliverablesAnalyzerInvokerImpl.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/BpmModuleConfig.java
moduleconfig/src/main/resources/pnc-config.json
moduleconfig/src/test/java/org/jboss/pnc/common/json/moduleconfig/GlobalConfigTest.java
moduleconfig/src/test/resources/testConfig.json
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java

Draft, still need to create some tests

[NCL-6190] implement analyzer of deliverables endpoint

---

indy-repository-manager/pom.xml
pom.xml

- Indy to 2.5.3
- Mockito to 3.8.0
- lombok to 1.18.18
- wildfly container to 3.0.1
- gmavenplus to 1.12.1
- groovy-all to 2.4.21

Upgrade deps

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

[NCLSUP-63] - fix MDC context propagation.

---

constants/src/main/java/org/jboss/pnc/enums/BuildCategory.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/Artifact.java
dto/src/main/java/org/jboss/pnc/dto/ArtifactRef.java
dto/src/main/java/org/jboss/pnc/dto/ArtifactRevision.java
dto/src/main/java/org/jboss/pnc/dto/ArtifactRevisionRef.java
facade/src/test/java/org/jboss/pnc/facade/providers/ArtifactProviderTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
model/src/main/java/org/jboss/pnc/model/Artifact.java
model/src/main/java/org/jboss/pnc/model/ArtifactAudited.java
model/src/main/resources/db-update/2000X-from-2.0.x-to-2.1.0.sql
model/src/test/java/org/jboss/pnc/model/ArtifactTest.java

[NCL-6361]: Add to the Artifacts model a new field to store the build category

---

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/AbstractRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ArtifactRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildConfigurationRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/EnvironmentRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/GroupBuildRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/GroupConfigurationRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductMilestoneRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductMilestoneReleaseRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductReleaseRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProductVersionRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ProjectRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/RepositoryConfigurationRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/TargetRepositoryRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/UserRSQLMapper.java
integration-test/src/test/java/org/jboss/pnc/integration/RSQLTest.java

[NCL-6415] Support RSQL ManyToMany filtering

---

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/response/ArtifactInfo.java
facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ArtifactRSQLMapper.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
processor/src/main/java/org/jboss/pnc/processor/ClientGenerator.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java

[NCL-6405]: Add Artifact.buildCategories to DTOs and update endpoints

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java

[NCL-6367] Fix reading of build category

---

bpm/src/test/java/org/jboss/pnc/bpm/test/RestConnectorRequestSerializationTest.java
facade/src/main/java/org/jboss/pnc/facade/impl/DeliverablesAnalyzerInvokerImpl.java
indy-repository-manager/pom.xml
integration-test/src/test/java/org/jboss/pnc/integration/BuildExecutionTest.java
integration-test/src/test/java/org/jboss/pnc/integration/EAPModulesAccessTest.java
pom.xml
termd-build-driver/pom.xml
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/transfer/ClientFileTransfer.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/LivenessProbeTest.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdServer.java

Build agent fixes

---

dto/src/main/java/org/jboss/pnc/dto/BuildConfiguration.java
dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationWithLatestBuild.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildConfigurationProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java

[NCL-6402] Add endpoint for build configs that include latest build

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java

[NCLSUP-227] Disallowing http/https protocols for internal SCM url

---

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java

[NCL-6402] Rename the endpoint according to new convention

---

rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java

And fix the decription of the value to match the current state.

[NCL-6368] Make build category validation case-insensitive

---

dto/src/main/java/org/jboss/pnc/dto/requests/BuildPushParameters.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/GroupConfigurationEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/exception/BuildConflictException.java

Fix logging and validation issues

---

common/src/main/java/org/jboss/pnc/common/util/UrlUtils.java

Thanks @vibe13 for catching this! You're the best :)

Remove unecessary code on UrlUtils

---

bpm/pom.xml
bpm/src/test/java/org/jboss/pnc/bpm/test/BuildResultSerializationTest.java
bpm/src/test/java/org/jboss/pnc/bpm/test/RepositoryManagerResultSerializationTest.java
mapper/pom.xml
mapper/src/main/java/org/jboss/pnc/mapper/api/ArtifactMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ArtifactRevisionMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java
pom.xml

Fix a few mapper issues

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/BuildRecordSpringRepository.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java

[NCL-6402] Refactor latestBuilds endpoint for better efficiency

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmManager.java
bpm/src/main/java/org/jboss/pnc/bpm/ConnectorSelector.java
bpm/src/main/java/org/jboss/pnc/bpm/notification/BpmNotifier.java
bpm/src/main/java/org/jboss/pnc/bpm/task/BpmBuildTask.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/BpmModuleConfig.java

Make use of new BPM configurable.

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java

[NCL-6402] Optimize running builds request

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

Set jobType for Maitai BPM

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java

[NCL-6402] Remove DTO fetching

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/BuildRecordSpringRepository.java

[NCL-6575] - Cannot access scm repository page with no build config

---

bpm/src/main/java/org/jboss/pnc/bpm/model/mapper/RepositoryManagerResultMapper.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ArtifactMapper.java

Allow target repository without ID in BuildResult.

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/bpm/BpmBuildScheduler.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/AbstractDependentBuildTest.java

Fix comparing string with ==

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildCoordinator.java

NCLSUP-356 - do not reject linked builds.

---

model/src/main/resources/db-update/2000X-from-2.0.x-to-2.1.0.sql

We want to quickly search by prefix of an identifier for dependency
alignment and version increment. Adding this index should allow much
faster search.

Add pattern index on artifact identifier

---

pom.xml
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/ClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/DefaultClientFactory.java
termd-build-driver/src/main/java/org/jboss/pnc/termdbuilddriver/RemoteInvocation.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/ClientMockFactory.java
termd-build-driver/src/test/java/org/jboss/pnc/termdbuilddriver/TermdServer.java

NCLSUP-358 - auth header when calling build agent.

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
mapper/src/main/java/org/jboss/pnc/mapper/api/ArtifactMapper.java

[NCL-6632] Use String IDs when communicating with Causeway

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

Fix artifact test

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java

[NCL-6621] - Indy fails to delete temporary hosted group

---

facade/src/main/java/org/jboss/pnc/facade/rsql/ComparatorRSQLNodeTraveller.java
facade/src/test/java/org/jboss/pnc/facade/rsql/RSQLPredicateProducerTest.java

[NCL-6431] Fix comparing of nullable field in RSQL

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
openshift-environment-driver/src/main/java/org/jboss/pnc/environment/openshift/OpenshiftStartedEnvironment.java

Reduce log level

---

model/src/main/java/org/jboss/pnc/model/Base32LongID.java

Add id setter to Base32LongID

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java

Fix log message.

---

dto/src/main/java/org/jboss/pnc/dto/Artifact.java
dto/src/main/java/org/jboss/pnc/dto/ArtifactRef.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/ArtifactRSQLMapper.java
indy-repository-manager/pom.xml
indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
model/src/main/java/org/jboss/pnc/model/Artifact.java
model/src/main/resources/db-update/20010-from-2.1.0-to-2.1.1.sql
pom.xml

[NCL-6652] - Add purl field to artifacts metadata

---

model/src/main/resources/db-update/2000X-from-2.0.x-to-2.1.0.sql

Make brewPullActive migrated to true for existing records

---

facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

[NCLSUP-404] Fix paging in /artifacts/filter REST method

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerResultProcessor.java
pom.xml
rest/pom.xml
rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/DeliverableAnalysisEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/DeliverableAnalysisEndpoint.java

Requires https://github.com/project-ncl/pnc-api/pull/48

[2.2] [NCL-6195] Add endpoint for Deliverable analysis results

---

bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java

[NCL-6258] Add token to the process start invocation.

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmManager.java
bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java
bpm/src/main/java/org/jboss/pnc/bpm/RestConnectorException.java
bpm/src/main/java/org/jboss/pnc/bpm/RestProcessInstance.java
bpm/src/main/java/org/jboss/pnc/bpm/causeway/ProductMilestoneReleaseManager.java
facade/src/main/java/org/jboss/pnc/facade/impl/DeliverablesAnalyzerInvokerImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/DeliverableAnalysisEndpoint.java

[NCL-6535] Milestone release - stateless cancel.

---

bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java

[NCL-6535] Fix correlation key passing.

---

bpm/src/main/java/org/jboss/pnc/bpm/model/AnalyzeDeliverablesBpmRequest.java
bpm/src/test/java/org/jboss/pnc/bpm/test/RestConnectorRequestSerializationTest.java
facade/src/main/java/org/jboss/pnc/facade/impl/DeliverablesAnalyzerInvokerImpl.java

[NCL-6258] Add milestoneId to delA process task.

---

constants/src/main/java/org/jboss/pnc/enums/AnalysisStatus.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/AnalysisStatusChangedEvent.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/AnalysisStatusMQNotifications.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DefaultAnalysisStatusChangedEvent.java
facade/src/main/java/org/jboss/pnc/facade/impl/DeliverablesAnalyzerInvokerImpl.java
messaging-spi/src/main/java/org/jboss/pnc/messaging/spi/AnalysisStatusMessage.java
messaging-spi/src/test/java/org/jboss/pnc/messaging/spi/AnalysisStatusMessageTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/DeliverableAnalysisEndpointImpl.java

* [ Will do if accepted ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ Yes ] Have you added unit tests for your change?

[NCL-6196] Added a UMB notification about finalised analysis of a product

---

messaging/src/main/java/org/jboss/pnc/messaging/DefaultMessageSender.java

This change is done especifically for exceptions when the JMS connection is
closed abruptly:
```
stackTrace: : org.jboss.pnc.messaging.spi.MessagingRuntimeException: Cannot send the message:
...
Caused by: javax.jms.IllegalStateException: The Connection is closed
at org.apache.activemq.ra.ManagedConnectionProxy.getConnection(ManagedConnectionProxy.java:98)
at org.apache.activemq.ra.ManagedConnectionProxy.createSessionProxy(ManagedConnectionProxy.java:124)
at org.apache.activemq.ra.ManagedConnectionProxy.createSession(ManagedConnectionProxy.java:110)
at org.jboss.pnc.messaging.DefaultMessageSender.doSendMessage(DefaultMessageSender.java:117)
```
On those failures, the `DefaultMessageSender` keeps failing to send data
afterwards since it doesn't try to establish a new connection. The only …

[NCLSUP-438] Try to get a new JMS connection on Exception

---

messaging/src/main/java/org/jboss/pnc/messaging/DefaultMessageSender.java

This change is done especifically for exceptions when the JMS connection is
closed abruptly:
```
stackTrace: : org.jboss.pnc.messaging.spi.MessagingRuntimeException: Cannot send the message:
...
Caused by: javax.jms.IllegalStateException: The Connection is closed
at org.apache.activemq.ra.ManagedConnectionProxy.getConnection(ManagedConnectionProxy.java:98)
at org.apache.activemq.ra.ManagedConnectionProxy.createSessionProxy(ManagedConnectionProxy.java:124)
at org.apache.activemq.ra.ManagedConnectionProxy.createSession(ManagedConnectionProxy.java:110)
at org.jboss.pnc.messaging.DefaultMessageSender.doSendMessage(DefaultMessageSender.java:117)
```
On those failures, the `DefaultMessageSender` keeps failing to send data
afterwards since it doesn't try to establish a new connection. The only …

[v2.1][NCLSUP-438] Try to get a new JMS connection on Exception

---

facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java

[NCL-6717] Add endpoint to get delivered artifacts for milestone

---

model/src/main/java/org/jboss/pnc/model/Base32LongID.java

[NCLSUP-444] Fix Infinispan error

---

bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java
build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/bpm/BpmBuildScheduler.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/CancelledBuildByBpmTest.java

Set build task configs.

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/bpm/BpmBuildScheduler.java

Do not jsonencode process parameters when using new bpm.

---

bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java

Add more logging to build cancel.

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java

Repour completion status.

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java

Fix the conversion from BigInteger to Long

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java

[NCL-6828] - FAILED build state after Cancelling

---

model/src/main/java/org/jboss/pnc/model/BuildRecord.java

[NCLSUP-444] Remove Cache annotations on BuildRecord fields

---

model/src/main/java/org/jboss/pnc/model/BuildRecord.java

[v2.1][NCLSUP-444] Remove Cache annotations on BuildRecord fields

---

bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationRest.java
bpm/src/main/java/org/jboss/pnc/bpm/model/BuildExecutionConfigurationWithCallbackRest.java
bpm/src/main/java/org/jboss/pnc/bpm/task/BpmBuildTask.java
bpm/src/test/java/org/jboss/pnc/bpm/test/BuildExecutionConfigurationTest.java
build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/local/LocalBuildScheduler.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinatorTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/DatastoreAdapterTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/SingleProjectBuildTest.java
build-executor/src/main/java/org/jboss/pnc/executor/DefaultBuildExecutionConfiguration.java
build-executor/src/test/java/org/jboss/pnc/executor/BuildEnvironmentTest.java
build-executor/src/test/java/org/jboss/pnc/executor/BuildExecutionBase.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildTaskEndpointTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/executor/BuildExecutionConfigurationMock.java
pnc-mock/src/main/java/org/jboss/pnc/mock/spi/BuildExecutionConfigurationMock.java
pom.xml
rest-api/pom.xml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GroupConfigurationEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/BuildParameters.java
rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/GroupBuildParameters.java
rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConstants.java
rest-api/src/main/java/org/jboss/pnc/rest/validation/BuildParametersConstraint.java
rest-api/src/main/java/org/jboss/pnc/rest/validation/BuildParametersValidator.java
rest-api/src/main/java/org/jboss/pnc/rest/validation/GroupBuildParametersConstraint.java
rest-api/src/main/java/org/jboss/pnc/rest/validation/GroupBuildParametersValidator.java
rest-api/src/test/java/org/jboss/pnc/rest/validation/BuildParametersValidatorTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/GroupConfigurationEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/BuildOptions.java
spi/src/main/java/org/jboss/pnc/spi/executor/BuildExecutionConfiguration.java

[NCL-6906] Add AlignmentPreference.

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
facade/src/test/java/org/jboss/pnc/facade/BuildPusherRejectionsTest.java

[NCL-6838] Add validation that brew name is available when pushing buid

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java

[NCLSUP-547] Workaround incorrectly tracked generic downloads in a group

---

indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/IndyRepositorySession.java
indy-repository-manager/src/main/java/org/jboss/pnc/indyrepositorymanager/RepositoryManagerDriver.java

[v2.2][NCLSUP-547] Workaround incorrectly tracked generic downloads in a group

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildTasksInitializer.java
dto/src/main/java/org/jboss/pnc/dto/GroupBuild.java
dto/src/main/java/org/jboss/pnc/dto/GroupBuildRef.java
model/src/main/java/org/jboss/pnc/model/BuildConfigSetRecord.java
model/src/main/resources/db-update/20030-from-2.2.0-to-2.3.0.sql
pom.xml

NCL-6942 - Build alignment preference.

---

facade/src/main/java/org/jboss/pnc/facade/impl/OperationsManagerImpl.java

Fix missing user in new Operation

---

rest/src/main/java/org/jboss/pnc/rest/endpoints/GroupConfigurationEndpointImpl.java

[NCLSUP-607] fix NPE on group build conflict

---

model/src/main/resources/db-update/20030-from-2.2.0-to-2.3.0.sql

[NCL-6695] Add schema update for operation table

---

facade/src/main/java/org/jboss/pnc/facade/impl/OperationsManagerImpl.java

[NCL-6966] Fire change event only when operation saves to DB

---

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java

The problem was that when building the artifact cache, there were
hundreds if not thousands of duplicate artifacts with the same sha256
and identifier. This is caused by the way generic proxy artifacts are
stored.
One problem is that the DB query to form the cache is searching only by
sha256 when searchin by (sha256, identifier) tuple would be better. But
I don't know how to fix this.
But the artifact cache was not even used when storing the generic proxy
artifacts! So we can safely ignore the generic proxy artifact when
creating the cache.

[NCLSUP-641] Fix artifact storing memory issues

---

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java

Fix comment

---

facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/TargetRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/TargetRepositoryProvider.java
facade/src/test/java/org/jboss/pnc/facade/providers/TargetRepositoryProviderTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/TargetRepositoryEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/TargetRepositoryEndpointImpl.java

[NCL-6993] Add REST endpoint for target repositories

---

facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/TargetRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/TargetRepositoryProvider.java
facade/src/test/java/org/jboss/pnc/facade/providers/TargetRepositoryProviderTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/TargetRepositoryEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/TargetRepositoryEndpointImpl.java

[v2.3][NCL-6993] Add REST endpoint for target repositories

---

rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java

[NCL-6993] Activate the target repositories endpoint

---

rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java

[v2.3][NCL-6993] Activate the target repositories endpoint

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Fix formatting

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/test/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerTest.java

Fix parsing of Deliverable analyzer result

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/AbstractRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/DeliverableAnalyzerOperationRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/OperationRSQLMapper.java

Add RSQL mapper for Operation

---

model/src/main/java/org/jboss/pnc/model/User.java
model/src/main/resources/db-update/20040-from-2.3.0-to-2.4.0.sql

[NCLSUP-598] Adapt user model for kerberos service account users

---

facade/src/main/java/org/jboss/pnc/facade/rsql/EntityRSQLNodeTraveller.java
integration-test/src/test/java/org/jboss/pnc/integration/RSQLTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java

Fix escaping underscore in RSQL queries

---

constants/src/main/java/org/jboss/pnc/enums/JobNotificationType.java
dto/src/main/java/org/jboss/pnc/dto/notification/OperationNotification.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/main/java/org/jboss/pnc/facade/impl/OperationChangedEventImpl.java
facade/src/main/java/org/jboss/pnc/facade/impl/OperationsManagerImpl.java
notifications/pom.xml
notifications/src/main/java/org/jboss/pnc/notification/DefaultNotifier.java
spi/src/main/java/org/jboss/pnc/spi/events/OperationChangedEvent.java

Add websocket notification on Operation progress

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
causeway-client/src/main/java/org/jboss/pnc/causewayclient/DefaultCausewayClient.java
common/pom.xml
common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java
common/src/main/java/org/jboss/pnc/common/security/CheckSum.java
common/src/main/java/org/jboss/pnc/common/security/Md5.java
common/src/main/java/org/jboss/pnc/common/security/Sha256.java
facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java

NCL-7095 - Use Long buildId for processContext

---

facade/src/main/java/org/jboss/pnc/facade/DeliverableAnalyzerManager.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/DeliverableAnalysisEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/DeliverableAnalysisEndpoint.java

[Ncl 7132] Add tracking of changed and clear-all for deliverable analyzer

---

pom.xml

Bump pnc-api version

---

rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/DeliverableAnalysisEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/DeliverableAnalysisEndpoint.java

DelAn cleanup - Fix method name and swagger doc

---

facade/src/main/java/org/jboss/pnc/facade/impl/OperationsManagerImpl.java

Remove forgotten debug messages

---

bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java

[NCLSUP-655] Add exceptions to error messages

---

dto/src/main/java/org/jboss/pnc/dto/GroupConfigurationRef.java
dto/src/main/java/org/jboss/pnc/dto/ProductRef.java
dto/src/main/java/org/jboss/pnc/dto/ProjectRef.java

[NCL-7260] Add constrain for non-blank names on DTOs

---

pom.xml

Upgrade to Java 11

---

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java

[NCL-7280] enforce UTF-8 encoding for build logs

---

dto/src/main/java/org/jboss/pnc/dto/GroupConfigurationRef.java
dto/src/main/java/org/jboss/pnc/dto/ProductRef.java
dto/src/main/java/org/jboss/pnc/dto/ProjectRef.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProjectEndpointTest.java

[NCL-7260] Add constrain groups to NotBlank in DTO names

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java

[NCL-7052] fix NPE on Group cancel

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

DelAn: use just filename part of path for filename field

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Update artifact update time when updating the update message

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Print basic statistics of deliverable analysis to log

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildQueue.java
common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java
constants/src/main/java/org/jboss/pnc/constants/MDCKeys.java
pom.xml

[NCL-7337] Add OpenTelemetry MDC metadata mapping

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java

[NCLSUP-758] don't try to delete artifacts from indy on failed builds

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/BuildQueue.java
common/src/main/java/org/jboss/pnc/common/concurrent/MDCThreadPoolExecutor.java

Try Context.taskWrapping to propagate the trace context

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

Improve error message when SCMRepo creation conflicts

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/IndyFactory.java
causeway-client/src/main/java/org/jboss/pnc/causewayclient/DefaultCausewayClient.java
common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java
integration-test/src/test/java/org/jboss/pnc/integration/setup/RestClientConfiguration.java
pom.xml
rest-api/src/main/java/org/jboss/pnc/client/Configuration.java
rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java
rest/src/main/java/org/jboss/pnc/rest/RequestLoggingFilter.java

Use MDCUtils from pnc-common

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/bpm/BpmBuildScheduler.java

[NCL-7076] - remove old BPM invocation code - add missing injection.

---

build-coordinator/pom.xml
build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java
demo-data/pom.xml
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/util/UserService.java
integration-test/pom.xml
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ExceptionMapperTest.java
integration-test/src/test/resources/WEB-INF/web.xml
pnc-mock/pom.xml
pom.xml
rest/pom.xml
rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
rest/src/main/java/org/jboss/pnc/rest/RequestLoggingFilter.java
rest/src/main/java/org/jboss/pnc/rest/SecurityConstraintFilter.java
rest/src/main/java/org/jboss/pnc/rest/provider/AllOtherExceptionsMapper.java
rest/src/main/webconfig/auth/web.xml
spi/pom.xml

Ncl 7311 log events of interest

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java

[NCL-7409] Verify that temporary artifacts have temporary quality set

---

bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java
common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java
facade/src/main/java/org/jboss/pnc/facade/impl/OperationsManagerImpl.java
pom.xml
rest/pom.xml
rest/src/main/java/org/jboss/pnc/rest/RequestLoggingFilter.java

Use otel utilities to handle traceparent and tracestate headers

---

rest-api/src/main/java/org/jboss/pnc/client/MdcToHeadersFilter.java

Add default otel headers into client requests

---

dto/src/main/java/org/jboss/pnc/dto/tasks/RepositoryCreationResult.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/SCMRepositoryProvider.java

NCL-7407 - fix DTO int to long.

---

pom.xml

Update otel resilience version to 1.1.0

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java
moduleconfig/src/test/java/org/jboss/pnc/common/json/moduleconfig/GlobalConfigTest.java
moduleconfig/src/test/resources/testConfig.json

[NCL-7403] include uiLogger URL in ui-config module

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RemoteBuildCoordinator.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/builder/RemoteBuildCoordinatorTest.java

remove NRR buildTasks from request to remote-schedule

---

rest-client/pom.xml
rest-client/src/main/java/org/jboss/pnc/restclient/util/ArtifactUtil.java

Add ArtifactUtil with methods to parse GAV/NV

---

constants/src/main/java/org/jboss/pnc/enums/BuildCategory.java

https://issues.redhat.com/browse/NCL-7510

feat(api): added new AUTO build category

---

bpm/src/main/java/org/jboss/pnc/bpm/RestConnector.java

Add bpm request object to the otel span attributes

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
integration-test/src/test/resources/pnc-config.json
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java

[NCL-7081] read logs of completed builds from Bifrost

---

rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java

fix 500 on get-builds endpoint

---

.github/dependabot.yml

[NCL-7105] Enable dependabot for version updates

---

dto/src/main/java/org/jboss/pnc/dto/requests/EnvironmentDeprecationRequest.java
facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/validation/InvalidEntityException.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/EnvironmentEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/EnvironmentEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/EnvironmentEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/EnvironmentPredicates.java

Add new endpoint to deprecate environments
Set DEPRECATION_UPGRADE attribute when an environment is being deprecated.

[NCL-7640] Add support for upgrade paths for deprecated environments

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
integration-test/src/test/resources/pnc-config.json
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/provider/AllOtherExceptionsMapper.java

NCL-7672 - fix logs REST API.

---

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/EnvironmentEndpoint.java

[NCL-7640] Fix HTTP method in environment deprecation endpoint

---

remote-build-coordinator/pom.xml
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/rexclient/RexHttpClient.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/rexclient/provider/LoggingFilter.java

Rex client serialization.

---

model/src/main/resources/db-update/20050-from-2.4.0-to-2.5.0.sql

[NCL-7238] Add notice to run script to fix bug in NCL-7238

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/rexclient/RexHttpClient.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/rexclient/exception/TaskNotFoundException.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/rexclient/provider/NotFoundMapper.java

Rex client: Improve not found exception handling.

---

facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java

Fix ambiguous identifier

---

bpm/src/main/java/org/jboss/pnc/bpm/task/MilestoneReleaseTask.java
pom.xml

 [NCL-7424] add support for MP Config and create a scheduler @module 

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java
facade/pom.xml
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/test/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerTest.java
pom.xml

Nclsup 834

---

dto/src/main/java/org/jboss/pnc/dto/AlignmentStrategy.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
model/src/main/java/org/jboss/pnc/model/utils/DelimitedStringListTypeDescriptor.java

fix NPE when updating strategies

---

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/UIModuleConfig.java

[NCL-7860] add bifrostWsUrl param to UI config

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
integration-test/src/test/resources/pnc-config.json
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest-api/src/test/java/org/jboss/pnc/client/ClientTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/provider/AllOtherExceptionsMapper.java

[v2.5] Revert bifrost changes

---

model/src/main/resources/db-update/20050-from-2.4.0-to-2.5.0.sql

This reverts commit 07505501c5a99ab4a5729266afdb503f5d1c67c3.

Revert "Add DB update script."

---

pom.xml

Upgrade sonar and jococo version

---

mapper/pom.xml
pom.xml
rest/pom.xml

Use the renamed rex modules

---

rest-api/src/main/java/org/jboss/pnc/client/MdcToHeadersFilter.java

[NCL-7890] Set MDC headers only if not specified

---

rest-api/src/main/java/org/jboss/pnc/client/MdcToHeadersFilter.java

[v2.5][NCL-7890] Set MDC headers only if not specified

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

[NCLSUP-834] Fix missing "/maven" in origin URL

---

auth/pom.xml
bpm/pom.xml
build-coordinator/pom.xml
causeway-client/pom.xml
common/pom.xml
constants/pom.xml
datastore/pom.xml
demo-data/pom.xml
dto/pom.xml
ear-package/pom.xml
facade/pom.xml
integration-test/pom.xml
mapper/pom.xml
messaging-spi/pom.xml
messaging/pom.xml
model/pom.xml
moduleconfig/pom.xml
notifications/pom.xml
pnc-mock/pom.xml
pom.xml
processor/pom.xml
rest-api/pom.xml
rest-client/pom.xml
rest/pom.xml
spi/pom.xml
test-common/pom.xml
web/pom.xml

[v2.5.x] Reset version to 2.5.0-SNAPSHOT

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/AbstractProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildIteratorTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/impl/CursorPageInfo.java

[NCL-7852] Fix pagination in builds

---

facade/src/main/java/org/jboss/pnc/facade/util/UserService.java
rest/src/main/java/org/jboss/pnc/rest/SecurityConstraintFilter.java

[NCL-7888] Fix exception when accessing authorized endpoint

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/DeliverableAnalyzerOperationRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/GenericOperationRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/OperationRSQLMapper.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java

[NCL-7671] fix RSQL for entities with subclasses

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java

NCL-7911 - check for null.

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java

Original commit by @matejonnet . I am just backporting it to master

NCL-7911 - fix RC creation response.

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/DatastoreAdapter.java

[NCL-7417] log to user log what is appedned to build log

---

facade/src/main/java/org/jboss/pnc/facade/providers/AbstractProvider.java

[NCL-7776] Don't log error when user requests invalid ID

---

.gitignore
common/pom.xml
common/src/main/templates/org/jboss/pnc/common/BuildInformationConstants.java
pom.xml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/VersionEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/VersionEndpointImpl.java

[NCL-6709] Introduce /rest/v2/version endpoint

---

rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java

[NCL-6708] Activate Version endpoint

---

auth/pom.xml
bpm/pom.xml
build-coordinator/pom.xml
causeway-client/pom.xml
common/pom.xml
constants/pom.xml
datastore/pom.xml
demo-data/pom.xml
dto/pom.xml
ear-package/pom.xml
facade/pom.xml
integration-test-rex/pom.xml
integration-test/pom.xml
mapper/pom.xml
messaging-spi/pom.xml
messaging/pom.xml
model/pom.xml
moduleconfig/pom.xml
notifications/pom.xml
pnc-mock/pom.xml
pom.xml
processor/pom.xml
remote-build-coordinator/pom.xml
rest-api/pom.xml
rest-client/pom.xml
rest/pom.xml
spi/pom.xml
test-common/pom.xml
web/pom.xml

Update main branch to 2.6.0-SNAPSHOT

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RemoteBuildCoordinator.java

Log process stages in RemoteBuildCoordinator.

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

[NCL-7566] Rex OTEL.

---

mapper/src/main/java/org/jboss/pnc/mapper/api/BuildTaskMappers.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java

[NCL-7926] fix orch NPE on new Rex state

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/test/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerTest.java

Preload PNC artifacts to speedup Deliverables processing

---

bpm/src/main/java/org/jboss/pnc/bpm/model/MDCParameters.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java

Add MDC values to Rex request.

---

mapper/src/main/java/org/jboss/pnc/mapper/api/BuildTaskMappers.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

Ignore new proeprty in Rex.taskTDO.

---

rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java

Add exception message when re-throwing.

---

datastore/src/main/java/org/jboss/pnc/datastore/DefaultDatastore.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/ArtifactRepositoryImpl.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ArtifactRepositoryMock.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ArtifactRepository.java

Optimize storage of Deliverable analysis result

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/rexclient/RexHttpClient.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/rexclient/provider/RexJacksonProvider.java

[NCL-8092] fix passing null values in BPM body

---

facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/ScmModuleConfig.java

[NCL-8024] Add secondary internal SCM URL

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Fix NPE and forgotten cahcing

---

mapper/src/main/java/org/jboss/pnc/mapper/api/BuildTaskMappers.java
spi/src/main/java/org/jboss/pnc/spi/coordinator/DefaultBuildTaskRef.java

Requires https://github.com/project-ncl/rex/pull/53

[NCL-7906] fill in start and end times in BR from Rex

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Fix not caching found Target repos

---

pom.xml

Maven profile which doesn't run dependency-check-maven

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductVersionRepositoryImpl.java
demo-data/pom.xml
demo-data/src/main/java/org/jboss/pnc/demo/data/BuildConfigurationAuditedHelper.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DemoDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/response/statistics/ProductMilestoneArtifactQualityStatistics.java
dto/src/main/java/org/jboss/pnc/dto/response/statistics/ProductMilestoneRepositoryTypeStatistics.java
dto/src/main/java/org/jboss/pnc/dto/response/statistics/ProductVersionDeliveredArtifactsStatistics.java
dto/src/main/java/org/jboss/pnc/dto/response/statistics/ProductVersionStatistics.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductVersionProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/RSQLTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductVersionEndpointTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ProductVersionRepositoryMock.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductVersionEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductVersionEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ProductVersionRepository.java

[NCL-7651] Product Version Dashboard REST API

---

dto/src/main/java/org/jboss/pnc/dto/AlignmentStrategy.java
dto/src/main/java/org/jboss/pnc/dto/ArtifactRef.java
dto/src/main/java/org/jboss/pnc/dto/ArtifactRevisionRef.java
dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRef.java
dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationRevisionRef.java
dto/src/main/java/org/jboss/pnc/dto/BuildConfigurationWithLatestBuild.java
dto/src/main/java/org/jboss/pnc/dto/BuildPushResultRef.java
dto/src/main/java/org/jboss/pnc/dto/BuildRef.java
dto/src/main/java/org/jboss/pnc/dto/Environment.java
dto/src/main/java/org/jboss/pnc/dto/GroupBuildRef.java
dto/src/main/java/org/jboss/pnc/dto/GroupConfigurationRef.java
dto/src/main/java/org/jboss/pnc/dto/OperationRef.java
dto/src/main/java/org/jboss/pnc/dto/ProductMilestoneCloseResultRef.java
dto/src/main/java/org/jboss/pnc/dto/ProductMilestoneRef.java
dto/src/main/java/org/jboss/pnc/dto/ProductRef.java
dto/src/main/java/org/jboss/pnc/dto/ProductReleaseRef.java
dto/src/main/java/org/jboss/pnc/dto/ProductVersionRef.java
dto/src/main/java/org/jboss/pnc/dto/ProjectRef.java
dto/src/main/java/org/jboss/pnc/dto/SCMRepository.java
dto/src/main/java/org/jboss/pnc/dto/TargetRepository.java
dto/src/main/java/org/jboss/pnc/dto/User.java
dto/src/test/java/org/jboss/pnc/dto/UserTest.java

[PSX-303] Activate nohtml validation on PNC DTOs

---

facade/src/main/java/org/jboss/pnc/facade/providers/ProductVersionProviderImpl.java

[NCL-7651]: Fix pagination size counting

---

model/src/main/resources/db-update/20060-from-2.5.0-to-2.6.0.sql

[NCL-8150] fix bcsr_id foreign key types

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
facade/src/main/java/org/jboss/pnc/facade/impl/OperationsManagerImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/GroupBuildProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/DeliverableAnalyzerOperationProviderImplTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/GroupBuildProviderTest.java
integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java

[NCL-8047] Remove accessToken in callbacks

---

notifications/pom.xml
pom.xml

[NCL-8157] Snappy java - required for kafka compression.

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java

[NCL-8032] pass MDC header mapping to Rex

---

bpm/src/main/java/org/jboss/pnc/bpm/model/AnalyzeDeliverablesBpmRequest.java
bpm/src/test/java/org/jboss/pnc/bpm/RestConnectorRequestSerializationTest.java
dto/src/main/java/org/jboss/pnc/dto/requests/DeliverablesAnalysisRequest.java
facade/src/main/java/org/jboss/pnc/facade/DeliverableAnalyzerManager.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
integration-test/pom.xml
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/utils/BPMWireMock.java
integration-test/src/test/resources/pnc-config.json
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java

[NCL-8067]: Add scratch flag to DeliverableAnalysisRequest

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/DatastoreAdapter.java

[NCL-8158] append exception into userLog

---

integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/RemoteServices.java
integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/WireMockUtils.java
integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/notifications/WebSocketClientTest.java
integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/testcontainers/CustomKeycloakContainer.java
integration-test-rex/src/test/resources/keycloak-realm-export.json
integration-test-rex/src/test/resources/rex-application.yaml
pom.xml
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java

[NCL-8160] parse internal error message from Rex

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java
integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/notifications/WebSocketClientTest.java
mapper/pom.xml
pnc-mock/src/main/java/org/jboss/pnc/mock/coordinator/BuildCoordinatorMock.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RemoteBuildCoordinator.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/coordinator/BuildCoordinator.java

[NCL-8215] fix oldStatus in WS messages

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/SortInfo.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/impl/DefaultOrderInfo.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/impl/DefaultSortInfo.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/impl/StableEmptySortInfo.java

Improve API and implementation of SortInfo

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java

[NCLSUP-954][v2.6.x] fix cast exception in build insights

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java

[NCLSUP-954] fix cast exception in build insights

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalysisStatusMQNotifications.java
messaging-spi/src/main/java/org/jboss/pnc/messaging/spi/AnalysisStatusMessage.java
messaging-spi/src/test/java/org/jboss/pnc/messaging/spi/AnalysisStatusMessageTest.java

[NCL-8260] - Improve the JMS content sent after analysis status change

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

[NCL-8231] - commons-lang artifact contains null as classifier

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

[NCL-8234] - Fix the math of the DalAnalyzer report; compute the PURL for not found artifacts

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

[NCLSUP-988][v2.6.x] fix creation of extra TRs during del-analysis

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java

[NCLSUP-973][v2.6.x] fix broken build metrics

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java

[NCLSUP-973] fix broken build metrics

---

facade/src/main/java/org/jboss/pnc/facade/util/UserService.java
rest/src/main/java/org/jboss/pnc/rest/SecurityConstraintFilter.java

Remove older roles when migrating to new SSO server

---

pom.xml

Bump RHSSO version from 7.6.1 to 7.6.5

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/rexclient/MyHeaderPropagator.java

Thanks to @michalovjan for pointing this out!

Remove Auth header in start/stopRequest for rex

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/GroupBuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/OperationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/TargetRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/UserRoles.java
integration-test/pom.xml
integration-test/src/test/resources/WEB-INF/web.xml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/EnvironmentEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/OperationEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/TargetRepositoryEndpoint.java
rest/src/main/webconfig/auth/web.xml

This reverts commit b75d2605e1a6464c95deef08c3d15fc53c8eda2e.

Revert " [NCL-8152] Use fine-grained roles for PNC endpoints"

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

Do not create duplicated artifacts after DelAnalyzer analysis

---

integration-test/src/test/java/org/jboss/pnc/integration/BuildTest.java

Fix BuildTest::dontRebuildTemporaryBuildWhenThereIsNewerPersistentOnSameRev

---

auth/src/main/java/org/jboss/pnc/auth/KeycloakClient.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Make KeycloakClient publicly accessible (needed by bpm)

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Fix the DeliverableAnalyzer query in case no PNC builds are found

---

mapper/src/main/java/org/jboss/pnc/mapper/abstracts/AbstractArtifactMapper.java

[NCL-8295] Fix displayed URLs for generic-http downloads

---

mapper/src/main/java/org/jboss/pnc/mapper/abstracts/AbstractArtifactMapper.java

[v2.6.x][NCL-8295] Fix displayed URLs for generic-http downloads

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

Update the endpoint to use data in new format that uses Deliverable Analysis Reports to keep backward compatibility.

[NCL-8273] Update /product-milestones/{id}/delivered-artifacts

---

demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/DeliverableAnalyzerReportProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/DeliverableAnalyzerReportEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/DeliverableAnalyzerReportEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/DeliverableAnalyzerReportEndpointImpl.java

[NCL-8066] Add endpoints to retrieve DelAn Reports

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinator.java

apparently you've got to remove mdc context before applying a new one

[NCLSUP-973] fix broken metrics #2

---

rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/DeliverableAnalysisEndpointImpl.java

[NCL-8250] Make /deliverable-analyses/complete callback be object

---

facade/src/main/java/org/jboss/pnc/facade/DeliverableAnalyzerManager.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/DeliverableAnalysisEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/api/DeliverableAnalysisEndpoint.java

Now, cleanup is done by adding DELETED label

Remove unused internal API endpoint

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/ArtifactRepositoryImpl.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/test/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ArtifactRepositoryMock.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ArtifactRepository.java

@janinko @michalovjan I made some changes to workaround the mocks and improve the artifact detection and reuse (partially introduced in 2.6.0 already) with a further check. Let's discuss what is needed or what needs to be changed. Thanks!

[NCL-8276] Do not create extra artifacts when running a Deliverable Analysis

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Pass user from Operation because we can't get user from token

---

model/src/main/java/org/jboss/pnc/model/DeliverableAnalyzerDistribution.java

Fix storing of analysis

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Isolate bogus model mapping

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Add more log about the saved deliverable artifacts in the report

---

datastore/src/main/resources/META-INF/persistence.xml

Do now show hibernate sql log

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Fix logging and add distribution association

---

model/src/main/java/org/jboss/pnc/model/DeliverableAnalyzerOperation.java

Fix the mapping of report inside the DeliverableAnalyzerOperation

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java

Do queries only if needed

---

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/OperationEndpoint.java

Respond with 202 (ACCEPTED) when starting new scratch DelAn operation

---

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/OperationEndpoint.java

Fix /operations/deliverable-analyzer/start's OpenAPI

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java

[NCL-8367] Add additional external urls

---

constants/src/main/java/org/jboss/pnc/constants/Patterns.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java

[NCL-8044] Add support for git@hostname:path/to/repo.git SCM internal url format

---

rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java

[NCL-7585]: Deprecate /generic-setting/pnc-version endpoints

---

common/src/main/java/org/jboss/pnc/common/net/GitSCPUrl.java
common/src/test/java/org/jboss/pnc/common/net/GitSCPUrlTest.java
common/src/test/java/org/jboss/pnc/common/test/util/UrlUtilsTest.java

Add support for subgroups in Git SCP-style URLs

---

dto/src/main/java/org/jboss/pnc/dto/PncStatus.java
facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/GenericSettingEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/PncStatusEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/PncStatusEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/GenericSettingEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/PncStatusEndpointImpl.java

[NCL-7584]: Replace /generic-setting/announcement-banner endpoint

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/bpm/BpmBuildScheduler.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorDeployments.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/mock/KeycloakServiceClientMock.java

Use service account when sending request to kieserver

---

common/src/main/java/org/jboss/pnc/common/json/JsonUtils.java
dto/src/main/java/org/jboss/pnc/dto/notification/GenericSettingNotification.java
facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/PncStatusEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/GenericSettingEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/PncStatusEndpointImpl.java

[NCL-7586]: Replace maintenance-mode-related endpoints

---

dto/pom.xml
pom.xml
rest-api/pom.xml
rest-client-jakarta/pom.xml
rest-client/pom.xml

Add rest-client-jakarta module

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/bpm/BpmBuildScheduler.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorDeployments.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/mock/KeycloakServiceClientMock.java
facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/GenericSettingProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/GroupBuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/OperationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/TargetRepositoryProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/UserRoles.java
facade/src/main/java/org/jboss/pnc/facade/util/UserService.java
integration-test/pom.xml
integration-test/src/test/resources/WEB-INF/web.xml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/EnvironmentEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/GenericSettingEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/OperationEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/TargetRepositoryEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/SecurityConstraintFilter.java
rest/src/main/webconfig/auth/web.xml

[v2.6.x] Backport role changes to the branch

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java

[NCL-8367] Add external ETT URL

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java

[NCL-6729] Fix test for updating defaultalignmentparam

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildConfigurationEndpointTest.java

[v2.6][NCL-6729] Fix test for updating defaultalignmentparam

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationAuditedRepositoryImpl.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildConfigurationRepositoryImpl.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/AbstractRepository.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildIteratorTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
mapper/src/main/java/org/jboss/pnc/mapper/BrewNameWorkaround.java
mapper/src/main/java/org/jboss/pnc/mapper/BuildBCRevisionFetcher.java
mapper/src/main/java/org/jboss/pnc/mapper/BuildHelpers.java
mapper/src/main/java/org/jboss/pnc/mapper/BuildHelpersNoBCRevision.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildMapper.java
model/src/main/java/org/jboss/pnc/model/BuildRecord.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildConfigurationPredicates.java

Nclsup 1002 master

---

facade/src/main/java/org/jboss/pnc/facade/rsql/ComparatorRSQLNodeTraveller.java

Fix ComparatorRSQLNodeTraveller with multiple sort fields

---

common/src/main/java/org/jboss/pnc/common/net/GitSCPUrl.java
common/src/test/java/org/jboss/pnc/common/net/GitSCPUrlTest.java
common/src/test/java/org/jboss/pnc/common/test/util/UrlUtilsTest.java
constants/src/main/java/org/jboss/pnc/constants/Patterns.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderTest.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/ScmModuleConfig.java

GitLab support

---

pom.xml

[v2.7] Update pnc-common to 2.4.1

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RemoteBuildCoordinator.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/AbstractDependentBuildTest.java

Add groupBuild's ID when sending BuildStatusChangedEvent via websockets

---

build-coordinator/pom.xml
build-coordinator/src/main/java/org/jboss/pnc/coordinator/builder/datastore/DatastoreAdapter.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/builder/DefaultBuildCoordinatorTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/AbstractDependentBuildTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorDeployments.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/BuildCoordinatorFactory.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/DatastoreAdapterTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/MultipleProjectsBuildTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/ProjectWithDependenciesBuildTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/SingleProjectBuildTest.java
build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/mock/BifrostLogUploaderMock.java
build-coordinator/src/test/resources/beans.xml
messaging/src/test/java/org/jboss/pnc/messaging/SysConfigProducer.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java
notifications/src/test/java/org/jboss/pnc/notification/DefaultObserverTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/common/SystemConfigMock.java
pom.xml
remote-build-coordinator/pom.xml
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/BifrostLogUploaderProducer.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/DatastoreAdapter.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/builder/BifrostLogUploaderMock.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/builder/RemoteBuildCoordinatorTest.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/AbstractDependentBuildTest.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/BuildCoordinatorDeployments.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/BuildCoordinatorFactory.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/DatastoreAdapterTest.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/dependencies/AbstractDependentBuildTest.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/mock/KeycloakServiceClientMock.java
remote-build-coordinator/src/test/resources/beans.xml
remote-build-coordinator/src/test/resources/pnc-config-one-parallel-only.json

[NCL-8471] Upload final logs to bifrost

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildEndpointTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java

[NCL-8473] Change bifrost log redirect URL

---

pom.xml

Update sonar version

---

dto/pom.xml
pom.xml
rest-api/pom.xml
rest-client-jakarta/pom.xml
rest-client/pom.xml

[v2.7] backport rest-client-jakarta

---

common/pom.xml
dto/pom.xml
rest-client-jakarta/pom.xml

Exclude more javax packages in rest-client-jakarta

---

dto/pom.xml

Return pnc-common as an optional dependency to dto module

---

common/pom.xml
rest-client-jakarta/pom.xml

[v2.7] improve Jakarta module dependencies

---

rest-api/src/main/java/org/jboss/pnc/client/ClientBase.java
rest-api/src/main/java/org/jboss/pnc/client/Configuration.java

Deprecare client bearer token

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
bpm/src/main/java/org/jboss/pnc/bpm/causeway/FinalLogRestProducer.java
bpm/src/test/java/org/jboss/pnc/bpm/BuildResultPushManagerTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/BuildPushTest.java
integration-test/src/test/java/org/jboss/pnc/integration/mock/client/BifrostMock.java
integration-test/src/test/java/org/jboss/pnc/integration/mock/client/FinalLogRestMock.java

Migrate from Bifrost to FinalLogRest interface

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/api/Predicate.java

Use getBuildList in getByAttribute

---

integration-test/src/test/java/org/jboss/pnc/integration/mock/client/FinalLogRestMock.java

Fix compilation of FinalLogRestMock

---

moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/UIModuleConfig.java

[NCL-864] Add userSupportUrl to UI config

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/AbstractRepository.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/SortInfoConverter.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java
facade/src/main/java/org/jboss/pnc/facade/rsql/EntityRSQLNodeTraveller.java
facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducer.java
facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java
facade/src/main/java/org/jboss/pnc/facade/rsql/SortRSQLNodeTraveller.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/MilestoneInfoRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/UniversalRSQLMapper.java
facade/src/test/java/org/jboss/pnc/facade/providers/ArtifactProviderTest.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildProviderImplTest.java
facade/src/test/java/org/jboss/pnc/facade/rsql/RSQLPredicateProducerTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java

[NCL-8062] Artifact Product Milestones endpoint is unfiltrable and unsortable

---

integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/testcontainers/InfinispanContainer.java
integration-test-rex/src/test/resources/rex-application.yaml
mapper/pom.xml
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SystemConfig.java
pom.xml
remote-build-coordinator/pom.xml
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/mock/RexHttpClientMock.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/mock/RexQueueHttpClientMock.java

Depends on https://github.com/project-ncl/rex/pull/73

[NCL-8251] Set cancellation timeout 

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildFetcher.java
facade/src/test/java/org/jboss/pnc/facade/providers/BuildFetcherTest.java

Fix dependency graph when parents are still running

---

model/src/main/resources/db-update/20080-remove-build-logs.sql

Add SQL script to for migration out of trigger based build archival

---

pom.xml
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/maintenance/IndyFactory.java

[NCL-8365] downgrade to indy-client 2.5.4.1

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/MilestoneInfoRSQLMapper.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java

[NCL-8713] Fix ambiguous RSQL mapper for milestones

---

dto/src/main/java/org/jboss/pnc/dto/response/AnalyzedArtifact.java
facade/pom.xml
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/DeliverableAnalyzerReportProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/DeliverableAnalyzerReportProvider.java
model/src/main/java/org/jboss/pnc/model/DeliverableArtifact.java
model/src/main/java/org/jboss/pnc/model/DeliverableArtifactLicenseInfo.java
model/src/main/resources/db-update/30000-add-delartifact-license-mapping.sql
pom.xml
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/DeliverableAnalyzerLabelEntryRepository.java

[NCL-8681] Store the license information of the deliverable urls analyzed by the Deliverable Analyzer

---

model/src/main/java/org/jboss/pnc/model/DeliverableArtifactLicenseInfo.java
model/src/main/resources/db-update/30000-add-delartifact-license-mapping.sql

Improve the mapping of DeliverableArtifactLicenseInfo

---

pom.xml

[NCL-8743] update to pnc-api 3.0.4-SNAPSHOT with relaxed md5 field for brewpush

---

auth/pom.xml
bpm/pom.xml
build-coordinator/pom.xml
causeway-client/pom.xml
common/pom.xml
constants/pom.xml
datastore/pom.xml
demo-data/pom.xml
dto/pom.xml
ear-package/pom.xml
facade/pom.xml
integration-test-rex/pom.xml
integration-test/pom.xml
mapper/pom.xml
messaging-spi/pom.xml
messaging/pom.xml
model/pom.xml
moduleconfig/pom.xml
notifications/pom.xml
pnc-mock/pom.xml
pom.xml
processor/pom.xml
remote-build-coordinator/pom.xml
rest-api/pom.xml
rest-client-jakarta/pom.xml
rest-client/pom.xml
rest/pom.xml
spi/pom.xml
test-common/pom.xml
web/pom.xml

update version to 3.0.0-SNAPSHOT

---

pom.xml

update to released rex, bifrost-client

---

pom.xml

fix javadocs

---

model/src/main/java/org/jboss/pnc/model/BuildConfiguration.java

[NCL-8669] Fix brewPullActive not being copied on clone

---

integration-test-rex/pom.xml
integration-test-rex/src/main/java/org/jboss/pnc/integrationrex/GetFreePort.java

hopefully fix deadlock in maven-exec-plugin

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
model/src/main/java/org/jboss/pnc/model/BuildRecord.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/SetRecordTasks.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/AbstractDependentBuildTest.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/dependencies/AbstractDependentBuildTest.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java

Apparently, Hibernate won't do the SQL query to fetch Records related to BCSR... Probably because the query the BCSR is from is a List query and lazy fetching won't work??

[NCL-8783] make fetching BRs from BCSRs explicit

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java

[NCL-8756] Allow PNC admin to retrive ssh credentials

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/DeliverableAnalyzerReportRSQLMapper.java

[NCL-8692] Implement DeliverableAnalyzerReport RSQL Mapper

---

facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/DeliverableAnalyzerLabelEntryRSQLMapper.java

[NCL-8693] Implement DeliverableAnalyzerLabelEntry RSQL Mapper

---

rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java

NCL-6481 Add validation for long ALIGNMENT_PARAMETERS

---

pom.xml

[NCL-8768] Set pnc-api to snapshot version

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalysisStatusMQNotifications.java

[NCL-8802] Fix NPE when sending deliverables analysis started message

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalysisStatusMQNotifications.java

[v3.0.x][NCL-8802] Fix NPE when sending deliverables analysis started message

---

facade/src/main/java/org/jboss/pnc/facade/rsql/converter/CastValueConverter.java
facade/src/test/java/org/jboss/pnc/facade/rsql/RSQLPredicateProducerTest.java

[NCL-7053] Validate RSQL query for comparing entity and not field

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java

[NCL-8647] --latest flag ignoring --query on Build Configs builds list

---

rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java
rest/src/main/java/org/jboss/pnc/rest/provider/ScheduleConflictExceptionMapper.java

[NCL-8753] Return 409 Conflict instead of 500 SE on Scheduling conflict

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildPushOperation.java
bpm/src/test/java/org/jboss/pnc/bpm/BuildResultPushManagerTest.java
dto/src/main/java/org/jboss/pnc/dto/BuildPushResult.java
dto/src/main/java/org/jboss/pnc/dto/BuildPushResultRef.java
facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
model/src/main/java/org/jboss/pnc/model/BuildRecordPushResult.java

The new field will be used to identify who initiated the Brew Push request, and add it as metadata in the Brew Push information. This is needed for auditing purposes.

[NCL-8808] Add userInitiator for brew push

---

bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildPushOperation.java
bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
bpm/src/main/java/org/jboss/pnc/bpm/causeway/ProductMilestoneReleaseManager.java
bpm/src/main/java/org/jboss/pnc/bpm/model/causeway/MilestoneReleaseRest.java
bpm/src/main/java/org/jboss/pnc/bpm/task/MilestoneReleaseTask.java
bpm/src/test/java/org/jboss/pnc/bpm/BuildResultPushManagerTest.java
bpm/src/test/java/org/jboss/pnc/bpm/ProductMilestoneReleaseManagerTest.java
dto/src/main/java/org/jboss/pnc/dto/BuildPushResult.java
dto/src/main/java/org/jboss/pnc/dto/BuildPushResultRef.java
facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/test/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderTest.java
model/src/main/java/org/jboss/pnc/model/BuildRecordPushResult.java
pom.xml

[NCL-8808] Add userInitiator for milestone release

---

facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java

[NCL-8808] Log the user for userInitiator for brew push

---

remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/notifications/buildTask/BuildStatusMQNotifications.java

[SBOMER-195] Observe build change notification after transactions

---

rest-api/src/main/java/org/jboss/pnc/client/Configuration.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildConfigurationClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedGroupConfigurationClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedProductMilestoneClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedSCMRepositoryClient.java

[NCL-8933][v3.0.1] use secure websocket protocol

---

rest-api/src/main/java/org/jboss/pnc/client/Configuration.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildConfigurationClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedGroupConfigurationClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedProductMilestoneClient.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedSCMRepositoryClient.java

[NCL-8933] use secure websocket protocol

---

rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java

[NCL-8933][v3.0.x] fix port being 80 for secure protocol

---

rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java

[NCL-8933] turn on SSL for secure protocols with WSs

---

auth/pom.xml
bpm/pom.xml
build-coordinator/pom.xml
causeway-client/pom.xml
common/pom.xml
constants/pom.xml
datastore/pom.xml
demo-data/pom.xml
dto/pom.xml
ear-package/pom.xml
facade/pom.xml
integration-test-rex/pom.xml
integration-test/pom.xml
mapper/pom.xml
messaging-spi/pom.xml
messaging/pom.xml
model/pom.xml
moduleconfig/pom.xml
notifications/pom.xml
pnc-mock/pom.xml
pom.xml
processor/pom.xml
remote-build-coordinator/pom.xml
rest-api/pom.xml
rest-client-jakarta/pom.xml
rest-client/pom.xml
rest/pom.xml
spi/pom.xml
test-common/pom.xml
web/pom.xml

Rollback 3.0.4 because of a failed release

---

rest-client/src/main/java/org/jboss/pnc/restclient/websocket/VertxWebSocketClient.java

[NCL-8933] fix port being 80 for secure protocol

---

pom.xml

Update pnc-api to 3.0.5

---

pom.xml

Update rex to 1.0.1

---

model/src/main/resources/db-update/21000-add-user-initiator.sql

[NCL-8808] Add db entry for userInitiator

---

common/pom.xml
common/src/main/java/org/jboss/pnc/common/util/ArtifactCoordinatesUtils.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/DeliveredArtifactInMilestones.java
dto/src/main/java/org/jboss/pnc/dto/response/ArtifactVersion.java
dto/src/main/java/org/jboss/pnc/dto/response/DeliveredArtifactInMilestones.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/DeliverableAnalyzerReportEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductVersionEndpointTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ProductMilestoneRepositoryMock.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java
rest-client/src/main/java/org/jboss/pnc/restclient/util/ArtifactUtil.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/DeliverableAnalyzerReportPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ProductMilestoneRepository.java

[NCL-7815] Implement Product Milestone Comparison REST API

---

facade/src/main/java/org/jboss/pnc/facade/providers/DeliverableAnalyzerReportProviderImpl.java

Add report existence validation when adding/removing DelAn labels

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/DeliverableAnalyzerLabelEntryRepositoryImpl.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/DeliverableAnalyzerReportEndpointTest.java
model/src/main/java/org/jboss/pnc/model/DeliverableAnalyzerLabelEntry.java
model/src/main/java/org/jboss/pnc/model/DeliverableAnalyzerReport.java

Fix delan labels

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/DeliverableArtifactRepositoryImpl.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductVersionEndpointTest.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

NCL-8995 Not built Delivered Artifacts shows wrong number

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/DeliverableArtifactRepositoryImpl.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/DeliverableAnalyzerReportEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/DeliverableAnalyzerReportPredicates.java

[NCL-8978] Filter out SCRATCH and DELETED DelAn results on Milestone and Version dashboards

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java
moduleconfig/src/test/resources/testConfig.json
pnc-mock/src/main/resources/globalGroupConfig.json
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

This is to signal that this method is to be used for RHPAM / BPM. Also add config for dingrogu url

Rename getCreateTaskDTO to getCreateTaskRHPAMDTO

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java
dingrogu-client/pom.xml
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguBuildWorkDTO.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java
moduleconfig/src/test/resources/testConfig.json
pnc-mock/src/main/resources/globalGroupConfig.json
pom.xml
remote-build-coordinator/pom.xml
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

You can try to use dingrogu by adding generic parameter key: "USE_DINGROGU" in the build configuration.

Initial integration of dingrogu with building

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguBuildWorkDTO.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java

Use correct endpoint for dingrogu start

---

dto/src/main/java/org/jboss/pnc/dto/response/ArtifactVersion.java
dto/src/main/java/org/jboss/pnc/dto/response/DeliveredArtifactInMilestones.java
dto/src/main/java/org/jboss/pnc/dto/response/ParsedArtifact.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java

NCL-7815 Fix Artifact Version DTO to include classifier

---

dingrogu-client/pom.xml
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguDeliverablesAnalysisDTO.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

[NCL-8963] Driver code for deliverables-analyzer dingrogu

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguRepositoryCreationDTO.java

[NCL-9003] Driver for repository-creation+dingrogu

---

integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/RemoteServices.java
integration-test-rex/src/test/resources/pnc-config.json
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildTaskMappers.java
moduleconfig/src/main/java/org/jboss/pnc/common/json/moduleconfig/SchedulerConfig.java
pom.xml
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RemoteBuildCoordinator.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/AbstractDependentBuildTest.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/mock/RexHttpClientMock.java
remote-build-coordinator/src/test/java/org/jboss/pnc/remotecoordinator/test/mock/RexQueueHttpClientMock.java

[NCL-8992][NCL-8935] fix alignment and use Rex's named Queues

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguRepositoryCreationDTO.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

This is done in the global module by adding:
```json
...
"tempUseDingroguRepositoryCreation": true,
...
```

[NCL-9003] Find a way to activate dingrogu repository creation process

---

integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/RemoteServices.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildTaskMappers.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/internal/BuildTaskEndpointImpl.java

handle new Rex StopFlag and fix tests

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java

Bug fix to pass namespace to Dingrogu

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguBrewPushDTO.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java

[NCL-8963] Add brew-push client

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java

Add retries when sending requests to dingrogu

---

common/src/main/java/org/jboss/pnc/common/graph/UndirectedGraphBuilder.java
common/src/main/java/org/jboss/pnc/common/graph/VertexNeighbor.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/response/Edge.java
dto/src/main/java/org/jboss/pnc/dto/response/Graph.java
dto/src/main/java/org/jboss/pnc/dto/response/Vertex.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/DeliverableAnalyzerReportEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductVersionEndpointTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ProductMilestoneRepositoryMock.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ProductMilestoneRepository.java

[NCL-7765] Product Milestone Interconnection Graph REST API

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalysisStatusMQNotifications.java
facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/main/java/org/jboss/pnc/facade/impl/OperationsManagerImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java
notifications/src/main/java/org/jboss/pnc/notification/DefaultEventObserver.java

To be merged after https://github.com/project-ncl/pnc/pull/4187

Operationon async fire

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClientImpl.java
integration-test/src/test/java/org/jboss/pnc/integration/mock/client/DingroguClientMock.java

Update build push process to use correct dingrogu endpoint

---

pom.xml
rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml
rest-api/pom.xml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/CacheEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConfig.java

Make the generated opeanapi spec be commited in repo

---

rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml
rest-api/src/main/java/org/jboss/pnc/rest/configuration/SwaggerConfig.java

Add version to openapi spec

---

model/src/main/resources/db-update/30200-build-push.sql
model/src/main/resources/db-update/30300-drop-old-build-push.sql

[NCL-7350] Add DB scripts for new Build Push

---

facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

[NCK-7765] Product Milestone Interconnections Graph - shared Delivered Artifacts endpoint

---

common/src/main/java/org/jboss/pnc/common/json/GlobalModuleGroup.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguBuildWorkDTO.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClientImpl.java

Initial implementation of Dingrogu build process using PNC build backend
https://issues.redhat.com/browse/NCL-9004

NCL-9004 Update Orch to support PNC builds via Dingrogu

---

common/pom.xml
common/src/main/java/org/jboss/pnc/common/util/ArtifactCoordinatesUtils.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/DeliverableArtifactRepositoryImpl.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/DeliveredArtifactInMilestones.java
dto/src/main/java/org/jboss/pnc/dto/response/ArtifactVersion.java
dto/src/main/java/org/jboss/pnc/dto/response/DeliveredArtifactInMilestones.java
dto/src/main/java/org/jboss/pnc/dto/response/ParsedArtifact.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/DeliverableAnalyzerReportEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductVersionEndpointTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ProductMilestoneRepositoryMock.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java
rest-client/src/main/java/org/jboss/pnc/restclient/util/ArtifactUtil.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/DeliverableAnalyzerReportPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ProductMilestoneRepository.java

Milestone Comparison backport for v3.1.x

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
pom.xml

[v3.1.x] Add support for Windows artifacts to Deliverables Analyzer

---

rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java

Fix API docs for build push completed

---

pom.xml

Update pnc-api to 3.0.6

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguRepositoryCreationDTO.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

Update RepositoryCreationDTO to use reqour instead of repour

---

pom.xml

Update pnc-api version

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguRepositoryCreationDTO.java
facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java

Needed for notification purposes

Add taskId for scm repo creation for dingrogu

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/DeliverableAnalyzerReportPredicates.java

old endpoint: /product-milestones/{id}/delivered-artifacts

Do not include SCRATCH and DELETED deliverables in the old endpoint

---

common/src/main/java/org/jboss/pnc/common/graph/UndirectedGraphBuilder.java
common/src/main/java/org/jboss/pnc/common/graph/VertexNeighbor.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/response/Edge.java
dto/src/main/java/org/jboss/pnc/dto/response/Graph.java
dto/src/main/java/org/jboss/pnc/dto/response/Vertex.java
facade/src/main/java/org/jboss/pnc/facade/providers/ArtifactProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ArtifactProvider.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/ProductMilestoneProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/DeliverableAnalyzerReportEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductVersionEndpointTest.java
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/ProductMilestoneRepositoryMock.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ProductMilestoneRepository.java

Milestone Interconnections Graph backport for v3.1.x

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/DeliverableAnalyzerReportProviderImpl.java
model/src/main/java/org/jboss/pnc/model/DeliverableArtifactLicenseInfo.java

Change license source type to string

---

integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/ArtifactPredicates.java

Duplicate Delivered Artifacts fix backport to v3.1.x

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClientImpl.java
facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

Fix more mdc stuff for dingrogu

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClientImpl.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

This reverts commit 385f0f029927d95c624f874a9129b4209ff9bc6e.

Reapply "Always include mdc values for dingrogu client"

---

mapper/src/main/java/org/jboss/pnc/mapper/api/BuildTaskMappers.java
pom.xml
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

update to latest rex snapshot

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClientImpl.java

Add mdc values where it's missing

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClient.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClientImpl.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/RexFacade.java

Add MDC values to callback

---

facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
model/src/main/java/org/jboss/pnc/model/DeliverableArtifactLicenseInfo.java
model/src/main/resources/db-update/30301-from-3.1.5-to-3.2.0.sql

fix nullability issue with LicenseSource and add DB script

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguBuildWorkDTO.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClientImpl.java

Related to: https://github.com/project-ncl/dingrogu/pull/163

Give the build config name to dingrogu

---

facade/src/main/java/org/jboss/pnc/facade/rsql/StreamRSQLNodeTraveller.java
facade/src/test/java/org/jboss/pnc/facade/rsql/RSQLPredicateProducerTest.java

NCL-9078 Fix Stream RSQL to compare booleans with ignoring case

---

build-coordinator/src/main/java/org/jboss/pnc/coordinator/maintenance/DefaultRemoteBuildsCleaner.java
facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/maintenance/DefaultRemoteBuildsCleaner.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/OperationPredicates.java

[NCL-9125] Fix wrong enum when querying operations

---

pom.xml

Update Rex to 1.1.0-SNAPSHOT

---

datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
datastore/src/main/java/org/jboss/pnc/datastore/repositories/internal/AbstractRepository.java
demo-data/src/main/java/org/jboss/pnc/demo/data/DatabaseDataInitializer.java
dto/src/main/java/org/jboss/pnc/dto/BuildPushReport.java
facade/src/main/java/org/jboss/pnc/facade/impl/BrewPusherImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/BuildPushOperationProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildPushOperationProvider.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/BuildPushOperationRSQLMapper.java
facade/src/main/java/org/jboss/pnc/facade/rsql/mapper/GenericOperationRSQLMapper.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
mapper/src/main/java/org/jboss/pnc/mapper/api/BuildPushReportMapper.java
model/src/main/resources/db-update/30200-build-push.sql
pnc-mock/src/main/java/org/jboss/pnc/mock/repository/BuildRecordRepositoryMock.java
rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildPushesEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/OperationEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest-client/src/main/java/org/jboss/pnc/restclient/AdvancedBuildClient.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildPushesEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/BuildPushPredicates.java
spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/BuildRecordRepository.java

Build Push API changes

---

rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java

Fix /build-pushes endpoint returning 404

---

facade/src/main/java/org/jboss/pnc/facade/rsql/RSQLProducerImpl.java

Remove TODOs since NCL-896{2,3} were closed

---

model/src/main/resources/db-update/30200-build-push.sql

Fix build push migration SQL script

---

model/src/main/resources/db-update/30301-from-3.1.5-to-3.2.0.sql

take into matter already existing rows and fill out defaults before enforcing non-nullability

fix 3.1.5 -> 3.2.0 db script

---

dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguBuildWorkDTO.java
dingrogu-client/src/main/java/org/jboss/pnc/dingroguclient/DingroguClientImpl.java

[NCL-9173] Send keep pod alive to dingrogu

---

notifications/src/main/java/org/jboss/pnc/notification/DefaultEventObserver.java

[NCL-9162] Also send BrewPushReport for new REST client and new bacon

---

pom.xml

Truly remove nexus-staging-maven-plugin

---

pom.xml
rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml

Hopefully this fixes deploying to maven central

---

constants/src/main/java/org/jboss/pnc/enums/BuildType.java
integration-test-rex/src/test/resources/pnc-config.json
integration-test/src/test/resources/pnc-config.json
pom.xml
rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml

[NCL-9178] introduce MVN_RPM build type

---

pom.xml

Use release pnc-api 3.2.3

---

rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml

Adjust openapi version

---

facade/src/main/java/org/jboss/pnc/facade/providers/BuildProviderImpl.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildPageInfo.java
facade/src/main/java/org/jboss/pnc/facade/providers/api/BuildProvider.java
integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ArtifactEndpointTest.java
rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ArtifactEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
rest-api/src/main/java/org/jboss/pnc/rest/api/parameters/BuildsBuildConfigFilterParameters.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ArtifactEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildConfigurationEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/BuildEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/GroupBuildEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/GroupConfigurationEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProductMilestoneEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/ProjectEndpointImpl.java
rest/src/main/java/org/jboss/pnc/rest/endpoints/UserEndpointImpl.java

[NCL-9245] Add filter for buildConfigName to /artifacts/ID/dependant-builds

---

rest-api/pnc-openapi.json
rest-api/pnc-openapi.yaml
rest/src/main/java/org/jboss/pnc/rest/JaxRsActivatorNew.java

Openapi pnc rest only
